<?php
/*
 * Copyright (c) 2017-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
namespace TencentCloud\Faceid\V20180301\Models;
use TencentCloud\Common\AbstractModel;

/**
 * BankCardVerification response structure.
 *
 * @method string getResult() Obtain Verification result code.
-Result code for charges
'0': 'Authentication passed'.
'-1': 'Authentication failed'.
'-5': 'Cardholder information is incorrect'.
'-6': 'Cardless payment not enabled'.
'-7': 'Card confiscated'.
'-8': 'Invalid card number'.
'-9': 'No corresponding issuing bank for this card'.
'-10': 'The card is uninitialized or a Sleep Card'.
'-11': 'Cheat card, card retention'.
'-12': 'Reported lost'.
'-13': 'The card has expired.'
'-14': 'Restricted card'.
'-15': 'Exceeded the number of password errors.'
'-16': 'Issuer does not support this transaction'.
'-20': 'Card status exception or card number error'.

-Result code with no charge
'-2': 'Name verification failed'.
'-3': 'Identity number error'.
'-4': 'Incorrect bank card number format'.
'-17': 'Verification Center Service busy'.
'-18': 'Exceeded verification attempts. Please retry the next day.'
'-19': 'The ID number is not currently supported for verification. Currently only support second-generation resident identity card.'	
 * @method void setResult(string $Result) Set Verification result code.
-Result code for charges
'0': 'Authentication passed'.
'-1': 'Authentication failed'.
'-5': 'Cardholder information is incorrect'.
'-6': 'Cardless payment not enabled'.
'-7': 'Card confiscated'.
'-8': 'Invalid card number'.
'-9': 'No corresponding issuing bank for this card'.
'-10': 'The card is uninitialized or a Sleep Card'.
'-11': 'Cheat card, card retention'.
'-12': 'Reported lost'.
'-13': 'The card has expired.'
'-14': 'Restricted card'.
'-15': 'Exceeded the number of password errors.'
'-16': 'Issuer does not support this transaction'.
'-20': 'Card status exception or card number error'.

-Result code with no charge
'-2': 'Name verification failed'.
'-3': 'Identity number error'.
'-4': 'Incorrect bank card number format'.
'-17': 'Verification Center Service busy'.
'-18': 'Exceeded verification attempts. Please retry the next day.'
'-19': 'The ID number is not currently supported for verification. Currently only support second-generation resident identity card.'	
 * @method string getDescription() Obtain Business result description.
 * @method void setDescription(string $Description) Set Business result description.
 * @method string getRequestId() Obtain The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
 * @method void setRequestId(string $RequestId) Set The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
 */
class BankCardVerificationResponse extends AbstractModel
{
    /**
     * @var string Verification result code.
-Result code for charges
'0': 'Authentication passed'.
'-1': 'Authentication failed'.
'-5': 'Cardholder information is incorrect'.
'-6': 'Cardless payment not enabled'.
'-7': 'Card confiscated'.
'-8': 'Invalid card number'.
'-9': 'No corresponding issuing bank for this card'.
'-10': 'The card is uninitialized or a Sleep Card'.
'-11': 'Cheat card, card retention'.
'-12': 'Reported lost'.
'-13': 'The card has expired.'
'-14': 'Restricted card'.
'-15': 'Exceeded the number of password errors.'
'-16': 'Issuer does not support this transaction'.
'-20': 'Card status exception or card number error'.

-Result code with no charge
'-2': 'Name verification failed'.
'-3': 'Identity number error'.
'-4': 'Incorrect bank card number format'.
'-17': 'Verification Center Service busy'.
'-18': 'Exceeded verification attempts. Please retry the next day.'
'-19': 'The ID number is not currently supported for verification. Currently only support second-generation resident identity card.'	
     */
    public $Result;

    /**
     * @var string Business result description.
     */
    public $Description;

    /**
     * @var string The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    public $RequestId;

    /**
     * @param string $Result Verification result code.
-Result code for charges
'0': 'Authentication passed'.
'-1': 'Authentication failed'.
'-5': 'Cardholder information is incorrect'.
'-6': 'Cardless payment not enabled'.
'-7': 'Card confiscated'.
'-8': 'Invalid card number'.
'-9': 'No corresponding issuing bank for this card'.
'-10': 'The card is uninitialized or a Sleep Card'.
'-11': 'Cheat card, card retention'.
'-12': 'Reported lost'.
'-13': 'The card has expired.'
'-14': 'Restricted card'.
'-15': 'Exceeded the number of password errors.'
'-16': 'Issuer does not support this transaction'.
'-20': 'Card status exception or card number error'.

-Result code with no charge
'-2': 'Name verification failed'.
'-3': 'Identity number error'.
'-4': 'Incorrect bank card number format'.
'-17': 'Verification Center Service busy'.
'-18': 'Exceeded verification attempts. Please retry the next day.'
'-19': 'The ID number is not currently supported for verification. Currently only support second-generation resident identity card.'	
     * @param string $Description Business result description.
     * @param string $RequestId The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    function __construct()
    {

    }

    /**
     * For internal only. DO NOT USE IT.
     */
    public function deserialize($param)
    {
        if ($param === null) {
            return;
        }
        if (array_key_exists("Result",$param) and $param["Result"] !== null) {
            $this->Result = $param["Result"];
        }

        if (array_key_exists("Description",$param) and $param["Description"] !== null) {
            $this->Description = $param["Description"];
        }

        if (array_key_exists("RequestId",$param) and $param["RequestId"] !== null) {
            $this->RequestId = $param["RequestId"];
        }
    }
}
