<?php
/*
 * Copyright (c) 2017-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
namespace TencentCloud\Faceid\V20180301\Models;
use TencentCloud\Common\AbstractModel;

/**
 * CheckBankCardInformation response structure.
 *
 * @method string getResult() Obtain Verification result code. Billing is as follows.
-Result code for charges
Query succeeded
-1: Not found
-5: Invalid card number

-Result code with no charge
-Verification Center Service is busy.
-3: Bank card not found.
-4: Authentication attempts exceeded the daily limit. Retry the next day.
-6: This bank card type is not currently supported

 * @method void setResult(string $Result) Set Verification result code. Billing is as follows.
-Result code for charges
Query succeeded
-1: Not found
-5: Invalid card number

-Result code with no charge
-Verification Center Service is busy.
-3: Bank card not found.
-4: Authentication attempts exceeded the daily limit. Retry the next day.
-6: This bank card type is not currently supported

 * @method string getDescription() Obtain Business result description.
 * @method void setDescription(string $Description) Set Business result description.
 * @method string getAccountBank() Obtain Account opening bank.
 * @method void setAccountBank(string $AccountBank) Set Account opening bank.
 * @method integer getAccountType() Obtain Card type.
-Value range:
1: Debit card.
2: Credit card.
3: Prepaid card.
4: Credit card
 * @method void setAccountType(integer $AccountType) Set Card type.
-Value range:
1: Debit card.
2: Credit card.
3: Prepaid card.
4: Credit card
 * @method string getRequestId() Obtain The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
 * @method void setRequestId(string $RequestId) Set The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
 */
class CheckBankCardInformationResponse extends AbstractModel
{
    /**
     * @var string Verification result code. Billing is as follows.
-Result code for charges
Query succeeded
-1: Not found
-5: Invalid card number

-Result code with no charge
-Verification Center Service is busy.
-3: Bank card not found.
-4: Authentication attempts exceeded the daily limit. Retry the next day.
-6: This bank card type is not currently supported

     */
    public $Result;

    /**
     * @var string Business result description.
     */
    public $Description;

    /**
     * @var string Account opening bank.
     */
    public $AccountBank;

    /**
     * @var integer Card type.
-Value range:
1: Debit card.
2: Credit card.
3: Prepaid card.
4: Credit card
     */
    public $AccountType;

    /**
     * @var string The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    public $RequestId;

    /**
     * @param string $Result Verification result code. Billing is as follows.
-Result code for charges
Query succeeded
-1: Not found
-5: Invalid card number

-Result code with no charge
-Verification Center Service is busy.
-3: Bank card not found.
-4: Authentication attempts exceeded the daily limit. Retry the next day.
-6: This bank card type is not currently supported

     * @param string $Description Business result description.
     * @param string $AccountBank Account opening bank.
     * @param integer $AccountType Card type.
-Value range:
1: Debit card.
2: Credit card.
3: Prepaid card.
4: Credit card
     * @param string $RequestId The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    function __construct()
    {

    }

    /**
     * For internal only. DO NOT USE IT.
     */
    public function deserialize($param)
    {
        if ($param === null) {
            return;
        }
        if (array_key_exists("Result",$param) and $param["Result"] !== null) {
            $this->Result = $param["Result"];
        }

        if (array_key_exists("Description",$param) and $param["Description"] !== null) {
            $this->Description = $param["Description"];
        }

        if (array_key_exists("AccountBank",$param) and $param["AccountBank"] !== null) {
            $this->AccountBank = $param["AccountBank"];
        }

        if (array_key_exists("AccountType",$param) and $param["AccountType"] !== null) {
            $this->AccountType = $param["AccountType"];
        }

        if (array_key_exists("RequestId",$param) and $param["RequestId"] !== null) {
            $this->RequestId = $param["RequestId"];
        }
    }
}
