<?php
/*
 * Copyright (c) 2017-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
namespace TencentCloud\Faceid\V20180301\Models;
use TencentCloud\Common\AbstractModel;

/**
 * CheckIdNameDate response structure.
 *
 * @method string getResult() Obtain Verification result code. Billing is as follows.

-Result code for charges
Same.
-1: Inconsistent.

-Result code with no charge
-2: Invalid ID number (incorrect length or check digit).
-3: Invalid name (incorrect length or format).
-4: Invalid validity period (incorrect length, format, etc.).
-5: Invalid identity information.
-6: Document library service exception.
-7: No ID card record found in the document library.
-8: Authentication attempts exceeded the daily limit. Retry the next day.
 * @method void setResult(string $Result) Set Verification result code. Billing is as follows.

-Result code for charges
Same.
-1: Inconsistent.

-Result code with no charge
-2: Invalid ID number (incorrect length or check digit).
-3: Invalid name (incorrect length or format).
-4: Invalid validity period (incorrect length, format, etc.).
-5: Invalid identity information.
-6: Document library service exception.
-7: No ID card record found in the document library.
-8: Authentication attempts exceeded the daily limit. Retry the next day.
 * @method string getDescription() Obtain Business result description.
 * @method void setDescription(string $Description) Set Business result description.
 * @method string getRequestId() Obtain The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
 * @method void setRequestId(string $RequestId) Set The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
 */
class CheckIdNameDateResponse extends AbstractModel
{
    /**
     * @var string Verification result code. Billing is as follows.

-Result code for charges
Same.
-1: Inconsistent.

-Result code with no charge
-2: Invalid ID number (incorrect length or check digit).
-3: Invalid name (incorrect length or format).
-4: Invalid validity period (incorrect length, format, etc.).
-5: Invalid identity information.
-6: Document library service exception.
-7: No ID card record found in the document library.
-8: Authentication attempts exceeded the daily limit. Retry the next day.
     */
    public $Result;

    /**
     * @var string Business result description.
     */
    public $Description;

    /**
     * @var string The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    public $RequestId;

    /**
     * @param string $Result Verification result code. Billing is as follows.

-Result code for charges
Same.
-1: Inconsistent.

-Result code with no charge
-2: Invalid ID number (incorrect length or check digit).
-3: Invalid name (incorrect length or format).
-4: Invalid validity period (incorrect length, format, etc.).
-5: Invalid identity information.
-6: Document library service exception.
-7: No ID card record found in the document library.
-8: Authentication attempts exceeded the daily limit. Retry the next day.
     * @param string $Description Business result description.
     * @param string $RequestId The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    function __construct()
    {

    }

    /**
     * For internal only. DO NOT USE IT.
     */
    public function deserialize($param)
    {
        if ($param === null) {
            return;
        }
        if (array_key_exists("Result",$param) and $param["Result"] !== null) {
            $this->Result = $param["Result"];
        }

        if (array_key_exists("Description",$param) and $param["Description"] !== null) {
            $this->Description = $param["Description"];
        }

        if (array_key_exists("RequestId",$param) and $param["RequestId"] !== null) {
            $this->RequestId = $param["RequestId"];
        }
    }
}
