<?php
/*
 * Copyright (c) 2017-2018 THL A29 Limited, a Tencent company. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
namespace TencentCloud\Faceid\V20180301\Models;
use TencentCloud\Common\AbstractModel;

/**
 * DetectReflectLivenessAndCompare request structure.
 *
 * @method string getLiveDataUrl() Obtain URL of the liveness detection data package generated by the SDK
 * @method void setLiveDataUrl(string $LiveDataUrl) Set URL of the liveness detection data package generated by the SDK
 * @method string getLiveDataMd5() Obtain MD5 hash value (32-bit) of the liveness detection data package generated by the SDK, which is used to verify the LiveData consistency.
 * @method void setLiveDataMd5(string $LiveDataMd5) Set MD5 hash value (32-bit) of the liveness detection data package generated by the SDK, which is used to verify the LiveData consistency.
 * @method string getImageUrl() Obtain URL of the target image for comparison
 * @method void setImageUrl(string $ImageUrl) Set URL of the target image for comparison
 * @method string getImageMd5() Obtain MD5 hash value (32-bit) of the target image for comparison, which is used to verify the `Image` consistency.
 * @method void setImageMd5(string $ImageMd5) Set MD5 hash value (32-bit) of the target image for comparison, which is used to verify the `Image` consistency.
 */
class DetectReflectLivenessAndCompareRequest extends AbstractModel
{
    /**
     * @var string URL of the liveness detection data package generated by the SDK
     */
    public $LiveDataUrl;

    /**
     * @var string MD5 hash value (32-bit) of the liveness detection data package generated by the SDK, which is used to verify the LiveData consistency.
     */
    public $LiveDataMd5;

    /**
     * @var string URL of the target image for comparison
     */
    public $ImageUrl;

    /**
     * @var string MD5 hash value (32-bit) of the target image for comparison, which is used to verify the `Image` consistency.
     */
    public $ImageMd5;

    /**
     * @param string $LiveDataUrl URL of the liveness detection data package generated by the SDK
     * @param string $LiveDataMd5 MD5 hash value (32-bit) of the liveness detection data package generated by the SDK, which is used to verify the LiveData consistency.
     * @param string $ImageUrl URL of the target image for comparison
     * @param string $ImageMd5 MD5 hash value (32-bit) of the target image for comparison, which is used to verify the `Image` consistency.
     */
    function __construct()
    {

    }

    /**
     * For internal only. DO NOT USE IT.
     */
    public function deserialize($param)
    {
        if ($param === null) {
            return;
        }
        if (array_key_exists("LiveDataUrl",$param) and $param["LiveDataUrl"] !== null) {
            $this->LiveDataUrl = $param["LiveDataUrl"];
        }

        if (array_key_exists("LiveDataMd5",$param) and $param["LiveDataMd5"] !== null) {
            $this->LiveDataMd5 = $param["LiveDataMd5"];
        }

        if (array_key_exists("ImageUrl",$param) and $param["ImageUrl"] !== null) {
            $this->ImageUrl = $param["ImageUrl"];
        }

        if (array_key_exists("ImageMd5",$param) and $param["ImageMd5"] !== null) {
            $this->ImageMd5 = $param["ImageMd5"];
        }
    }
}
