<?php
/*
 * Copyright (c) 2017-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
namespace TencentCloud\Faceid\V20180301\Models;
use TencentCloud\Common\AbstractModel;

/**
 * MobileStatus response structure.
 *
 * @method string getResult() Obtain Verification result code. Billing is as follows.
-Result code for charges
0: Success.

-Result code with no charge
-No results found.
-2: Invalid phone number format.
-3: Verification Center Service is busy.
-4: Authentication attempts exceeded the daily limit. Retry the next day.
 * @method void setResult(string $Result) Set Verification result code. Billing is as follows.
-Result code for charges
0: Success.

-Result code with no charge
-No results found.
-2: Invalid phone number format.
-3: Verification Center Service is busy.
-4: Authentication attempts exceeded the daily limit. Retry the next day.
 * @method string getDescription() Obtain Business result description.
 * @method void setDescription(string $Description) Set Business result description.
 * @method integer getStatusCode() Obtain Status code.
-Value range:
0: Normal.
1: Out of service.
2: Account cancellation.
4: Offline.
99: unknown status.
 * @method void setStatusCode(integer $StatusCode) Set Status code.
-Value range:
0: Normal.
1: Out of service.
2: Account cancellation.
4: Offline.
99: unknown status.
 * @method string getRequestId() Obtain The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
 * @method void setRequestId(string $RequestId) Set The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
 */
class MobileStatusResponse extends AbstractModel
{
    /**
     * @var string Verification result code. Billing is as follows.
-Result code for charges
0: Success.

-Result code with no charge
-No results found.
-2: Invalid phone number format.
-3: Verification Center Service is busy.
-4: Authentication attempts exceeded the daily limit. Retry the next day.
     */
    public $Result;

    /**
     * @var string Business result description.
     */
    public $Description;

    /**
     * @var integer Status code.
-Value range:
0: Normal.
1: Out of service.
2: Account cancellation.
4: Offline.
99: unknown status.
     */
    public $StatusCode;

    /**
     * @var string The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    public $RequestId;

    /**
     * @param string $Result Verification result code. Billing is as follows.
-Result code for charges
0: Success.

-Result code with no charge
-No results found.
-2: Invalid phone number format.
-3: Verification Center Service is busy.
-4: Authentication attempts exceeded the daily limit. Retry the next day.
     * @param string $Description Business result description.
     * @param integer $StatusCode Status code.
-Value range:
0: Normal.
1: Out of service.
2: Account cancellation.
4: Offline.
99: unknown status.
     * @param string $RequestId The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    function __construct()
    {

    }

    /**
     * For internal only. DO NOT USE IT.
     */
    public function deserialize($param)
    {
        if ($param === null) {
            return;
        }
        if (array_key_exists("Result",$param) and $param["Result"] !== null) {
            $this->Result = $param["Result"];
        }

        if (array_key_exists("Description",$param) and $param["Description"] !== null) {
            $this->Description = $param["Description"];
        }

        if (array_key_exists("StatusCode",$param) and $param["StatusCode"] !== null) {
            $this->StatusCode = $param["StatusCode"];
        }

        if (array_key_exists("RequestId",$param) and $param["RequestId"] !== null) {
            $this->RequestId = $param["RequestId"];
        }
    }
}
