<?php
/*
 * Copyright (c) 2017-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
namespace TencentCloud\Faceid\V20180301\Models;
use TencentCloud\Common\AbstractModel;

/**
 * PhoneVerification response structure.
 *
 * @method string getResult() Obtain Verification result code.
-Fee result code
Three-element information consistency.
-4: Three-element information inconsistency.

-No charge result code
-6: Invalid phone number.
-7: Identity number error.
-8: Name verification failed.
-9: No records.
-11: The Verification Center Service is busy.
-12: Authentication attempts exceeded the daily limit. Retry the next day.
-13: The number range is unsupported for verification.
 * @method void setResult(string $Result) Set Verification result code.
-Fee result code
Three-element information consistency.
-4: Three-element information inconsistency.

-No charge result code
-6: Invalid phone number.
-7: Identity number error.
-8: Name verification failed.
-9: No records.
-11: The Verification Center Service is busy.
-12: Authentication attempts exceeded the daily limit. Retry the next day.
-13: The number range is unsupported for verification.
 * @method string getDescription() Obtain Business result description.
 * @method void setDescription(string $Description) Set Business result description.
 * @method string getIsp() Obtain ISP name.
-Valid values: ["", "mobile", "telecom", "cucc"]
 * @method void setIsp(string $Isp) Set ISP name.
-Valid values: ["", "mobile", "telecom", "cucc"]
 * @method string getRequestId() Obtain The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
 * @method void setRequestId(string $RequestId) Set The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
 */
class PhoneVerificationResponse extends AbstractModel
{
    /**
     * @var string Verification result code.
-Fee result code
Three-element information consistency.
-4: Three-element information inconsistency.

-No charge result code
-6: Invalid phone number.
-7: Identity number error.
-8: Name verification failed.
-9: No records.
-11: The Verification Center Service is busy.
-12: Authentication attempts exceeded the daily limit. Retry the next day.
-13: The number range is unsupported for verification.
     */
    public $Result;

    /**
     * @var string Business result description.
     */
    public $Description;

    /**
     * @var string ISP name.
-Valid values: ["", "mobile", "telecom", "cucc"]
     */
    public $Isp;

    /**
     * @var string The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    public $RequestId;

    /**
     * @param string $Result Verification result code.
-Fee result code
Three-element information consistency.
-4: Three-element information inconsistency.

-No charge result code
-6: Invalid phone number.
-7: Identity number error.
-8: Name verification failed.
-9: No records.
-11: The Verification Center Service is busy.
-12: Authentication attempts exceeded the daily limit. Retry the next day.
-13: The number range is unsupported for verification.
     * @param string $Description Business result description.
     * @param string $Isp ISP name.
-Valid values: ["", "mobile", "telecom", "cucc"]
     * @param string $RequestId The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    function __construct()
    {

    }

    /**
     * For internal only. DO NOT USE IT.
     */
    public function deserialize($param)
    {
        if ($param === null) {
            return;
        }
        if (array_key_exists("Result",$param) and $param["Result"] !== null) {
            $this->Result = $param["Result"];
        }

        if (array_key_exists("Description",$param) and $param["Description"] !== null) {
            $this->Description = $param["Description"];
        }

        if (array_key_exists("Isp",$param) and $param["Isp"] !== null) {
            $this->Isp = $param["Isp"];
        }

        if (array_key_exists("RequestId",$param) and $param["RequestId"] !== null) {
            $this->RequestId = $param["RequestId"];
        }
    }
}
