<?php
/*
 * Copyright (c) 2017-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
namespace TencentCloud\Faceid\V20180301\Models;
use TencentCloud\Common\AbstractModel;

/**
 * RunAMLNameScreening response structure.
 *
 * @method string getScreeningResult() Obtain <p>Filtering results: NO-HITS (not hit) / HAS-HITS (hit)</p>
 * @method void setScreeningResult(string $ScreeningResult) Set <p>Filtering results: NO-HITS (not hit) / HAS-HITS (hit)</p>
 * @method array getAMLTypes() Obtain <p>Return on hit, the hit AML type list (deduplicated)</p>
 * @method void setAMLTypes(array $AMLTypes) Set <p>Return on hit, the hit AML type list (deduplicated)</p>
 * @method string getHitDetail() Obtain <p>Return on cache hit, hit risk detail list</p>
 * @method void setHitDetail(string $HitDetail) Set <p>Return on cache hit, hit risk detail list</p>
 * @method string getResult() Obtain <p>Returned results</p>
 * @method void setResult(string $Result) Set <p>Returned results</p>
 * @method string getDescription() Obtain <p>Description of results returned</p>
 * @method void setDescription(string $Description) Set <p>Description of results returned</p>
 * @method string getScreeningId() Obtain <p>The unique identifier of a case generated by one hit screening</p>
 * @method void setScreeningId(string $ScreeningId) Set <p>The unique identifier of a case generated by one hit screening</p>
 * @method boolean getEnableOngoingScreening() Obtain <p>Whether continuous monitoring and screening is enabled. Default value: false</p><p>Default value: false</p>
 * @method void setEnableOngoingScreening(boolean $EnableOngoingScreening) Set <p>Whether continuous monitoring and screening is enabled. Default value: false</p><p>Default value: false</p>
 * @method string getRequestId() Obtain The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
 * @method void setRequestId(string $RequestId) Set The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
 */
class RunAMLNameScreeningResponse extends AbstractModel
{
    /**
     * @var string <p>Filtering results: NO-HITS (not hit) / HAS-HITS (hit)</p>
     */
    public $ScreeningResult;

    /**
     * @var array <p>Return on hit, the hit AML type list (deduplicated)</p>
     */
    public $AMLTypes;

    /**
     * @var string <p>Return on cache hit, hit risk detail list</p>
     */
    public $HitDetail;

    /**
     * @var string <p>Returned results</p>
     */
    public $Result;

    /**
     * @var string <p>Description of results returned</p>
     */
    public $Description;

    /**
     * @var string <p>The unique identifier of a case generated by one hit screening</p>
     */
    public $ScreeningId;

    /**
     * @var boolean <p>Whether continuous monitoring and screening is enabled. Default value: false</p><p>Default value: false</p>
     */
    public $EnableOngoingScreening;

    /**
     * @var string The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    public $RequestId;

    /**
     * @param string $ScreeningResult <p>Filtering results: NO-HITS (not hit) / HAS-HITS (hit)</p>
     * @param array $AMLTypes <p>Return on hit, the hit AML type list (deduplicated)</p>
     * @param string $HitDetail <p>Return on cache hit, hit risk detail list</p>
     * @param string $Result <p>Returned results</p>
     * @param string $Description <p>Description of results returned</p>
     * @param string $ScreeningId <p>The unique identifier of a case generated by one hit screening</p>
     * @param boolean $EnableOngoingScreening <p>Whether continuous monitoring and screening is enabled. Default value: false</p><p>Default value: false</p>
     * @param string $RequestId The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    function __construct()
    {

    }

    /**
     * For internal only. DO NOT USE IT.
     */
    public function deserialize($param)
    {
        if ($param === null) {
            return;
        }
        if (array_key_exists("ScreeningResult",$param) and $param["ScreeningResult"] !== null) {
            $this->ScreeningResult = $param["ScreeningResult"];
        }

        if (array_key_exists("AMLTypes",$param) and $param["AMLTypes"] !== null) {
            $this->AMLTypes = $param["AMLTypes"];
        }

        if (array_key_exists("HitDetail",$param) and $param["HitDetail"] !== null) {
            $this->HitDetail = $param["HitDetail"];
        }

        if (array_key_exists("Result",$param) and $param["Result"] !== null) {
            $this->Result = $param["Result"];
        }

        if (array_key_exists("Description",$param) and $param["Description"] !== null) {
            $this->Description = $param["Description"];
        }

        if (array_key_exists("ScreeningId",$param) and $param["ScreeningId"] !== null) {
            $this->ScreeningId = $param["ScreeningId"];
        }

        if (array_key_exists("EnableOngoingScreening",$param) and $param["EnableOngoingScreening"] !== null) {
            $this->EnableOngoingScreening = $param["EnableOngoingScreening"];
        }

        if (array_key_exists("RequestId",$param) and $param["RequestId"] !== null) {
            $this->RequestId = $param["RequestId"];
        }
    }
}
