<?php
/*
 * Copyright (c) 2017-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
namespace TencentCloud\Tcss\V20201101\Models;
use TencentCloud\Common\AbstractModel;

/**
 * AddAssetImageRegistryRegistryDetail response structure.
 *
 * @method string getHealthCheckErr() Obtain Connection error message
 * @method void setHealthCheckErr(string $HealthCheckErr) Set Connection error message
 * @method string getNameRepeatErr() Obtain Error message of the name
 * @method void setNameRepeatErr(string $NameRepeatErr) Set Error message of the name
 * @method integer getRegistryId() Obtain Repository unique id
 * @method void setRegistryId(integer $RegistryId) Set Repository unique id
 * @method string getRequestId() Obtain The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
 * @method void setRequestId(string $RequestId) Set The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
 */
class AddAssetImageRegistryRegistryDetailResponse extends AbstractModel
{
    /**
     * @var string Connection error message
     */
    public $HealthCheckErr;

    /**
     * @var string Error message of the name
     */
    public $NameRepeatErr;

    /**
     * @var integer Repository unique id
     */
    public $RegistryId;

    /**
     * @var string The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    public $RequestId;

    /**
     * @param string $HealthCheckErr Connection error message
     * @param string $NameRepeatErr Error message of the name
     * @param integer $RegistryId Repository unique id
     * @param string $RequestId The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    function __construct()
    {

    }

    /**
     * For internal only. DO NOT USE IT.
     */
    public function deserialize($param)
    {
        if ($param === null) {
            return;
        }
        if (array_key_exists("HealthCheckErr",$param) and $param["HealthCheckErr"] !== null) {
            $this->HealthCheckErr = $param["HealthCheckErr"];
        }

        if (array_key_exists("NameRepeatErr",$param) and $param["NameRepeatErr"] !== null) {
            $this->NameRepeatErr = $param["NameRepeatErr"];
        }

        if (array_key_exists("RegistryId",$param) and $param["RegistryId"] !== null) {
            $this->RegistryId = $param["RegistryId"];
        }

        if (array_key_exists("RequestId",$param) and $param["RequestId"] !== null) {
            $this->RequestId = $param["RequestId"];
        }
    }
}
