<?php
/*
 * Copyright (c) 2017-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
namespace TencentCloud\Tcss\V20201101\Models;
use TencentCloud\Common\AbstractModel;

/**
 * DescribeAssetImageRegistryRegistryDetail response structure.
 *
 * @method string getName() Obtain Repository name
 * @method void setName(string $Name) Set Repository name
 * @method string getUsername() Obtain Username
 * @method void setUsername(string $Username) Set Username
 * @method string getPassword() Obtain Password
 * @method void setPassword(string $Password) Set Password
 * @method string getUrl() Obtain Repository URL
 * @method void setUrl(string $Url) Set Repository URL
 * @method string getRegistryType() Obtain Repository type, which can be `harbor`.
 * @method void setRegistryType(string $RegistryType) Set Repository type, which can be `harbor`.
 * @method string getRegistryVersion() Obtain warehouse version
 * @method void setRegistryVersion(string $RegistryVersion) Set warehouse version
 * @method string getNetType() Obtain Network type, which can be `public` (public network).
 * @method void setNetType(string $NetType) Set Network type, which can be `public` (public network).
 * @method string getRegistryRegion() Obtain Region, list: default
 * @method void setRegistryRegion(string $RegistryRegion) Set Region, list: default
 * @method integer getSpeedLimit() Obtain rate limiting
 * @method void setSpeedLimit(integer $SpeedLimit) Set rate limiting
 * @method integer getInsecure() Obtain 0: Secure Mode (Certificate Verification) (Default); 1: Insecure Mode (Skip Certificate Verification)
 * @method void setInsecure(integer $Insecure) Set 0: Secure Mode (Certificate Verification) (Default); 1: Insecure Mode (Skip Certificate Verification)
 * @method array getConnDetectDetail() Obtain 
 * @method void setConnDetectDetail(array $ConnDetectDetail) Set 
 * @method string getInstanceID() Obtain 
 * @method void setInstanceID(string $InstanceID) Set 
 * @method integer getSyncMode() Obtain Synchronization method. 0: full synchronization; 1: incremental synchronization.
 * @method void setSyncMode(integer $SyncMode) Set Synchronization method. 0: full synchronization; 1: incremental synchronization.
 * @method boolean getNeedScan() Obtain Whether authorization and scanning are performed automatically. For full synchronization, only images of the latest version are involved. For incremental synchronization, all new images are involved.
 * @method void setNeedScan(boolean $NeedScan) Set Whether authorization and scanning are performed automatically. For full synchronization, only images of the latest version are involved. For incremental synchronization, all new images are involved.
 * @method string getWebhookUrl() Obtain Webhook access address.
 * @method void setWebhookUrl(string $WebhookUrl) Set Webhook access address.
 * @method string getWebhookToken() Obtain Webhook access token.	
 * @method void setWebhookToken(string $WebhookToken) Set Webhook access token.	
 * @method string getRequestId() Obtain The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
 * @method void setRequestId(string $RequestId) Set The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
 */
class DescribeAssetImageRegistryRegistryDetailResponse extends AbstractModel
{
    /**
     * @var string Repository name
     */
    public $Name;

    /**
     * @var string Username
     */
    public $Username;

    /**
     * @var string Password
     */
    public $Password;

    /**
     * @var string Repository URL
     */
    public $Url;

    /**
     * @var string Repository type, which can be `harbor`.
     */
    public $RegistryType;

    /**
     * @var string warehouse version
     */
    public $RegistryVersion;

    /**
     * @var string Network type, which can be `public` (public network).
     */
    public $NetType;

    /**
     * @var string Region, list: default
     */
    public $RegistryRegion;

    /**
     * @var integer rate limiting
     */
    public $SpeedLimit;

    /**
     * @var integer 0: Secure Mode (Certificate Verification) (Default); 1: Insecure Mode (Skip Certificate Verification)
     */
    public $Insecure;

    /**
     * @var array 
     */
    public $ConnDetectDetail;

    /**
     * @var string 
     */
    public $InstanceID;

    /**
     * @var integer Synchronization method. 0: full synchronization; 1: incremental synchronization.
     */
    public $SyncMode;

    /**
     * @var boolean Whether authorization and scanning are performed automatically. For full synchronization, only images of the latest version are involved. For incremental synchronization, all new images are involved.
     */
    public $NeedScan;

    /**
     * @var string Webhook access address.
     */
    public $WebhookUrl;

    /**
     * @var string Webhook access token.	
     */
    public $WebhookToken;

    /**
     * @var string The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    public $RequestId;

    /**
     * @param string $Name Repository name
     * @param string $Username Username
     * @param string $Password Password
     * @param string $Url Repository URL
     * @param string $RegistryType Repository type, which can be `harbor`.
     * @param string $RegistryVersion warehouse version
     * @param string $NetType Network type, which can be `public` (public network).
     * @param string $RegistryRegion Region, list: default
     * @param integer $SpeedLimit rate limiting
     * @param integer $Insecure 0: Secure Mode (Certificate Verification) (Default); 1: Insecure Mode (Skip Certificate Verification)
     * @param array $ConnDetectDetail 
     * @param string $InstanceID 
     * @param integer $SyncMode Synchronization method. 0: full synchronization; 1: incremental synchronization.
     * @param boolean $NeedScan Whether authorization and scanning are performed automatically. For full synchronization, only images of the latest version are involved. For incremental synchronization, all new images are involved.
     * @param string $WebhookUrl Webhook access address.
     * @param string $WebhookToken Webhook access token.	
     * @param string $RequestId The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    function __construct()
    {

    }

    /**
     * For internal only. DO NOT USE IT.
     */
    public function deserialize($param)
    {
        if ($param === null) {
            return;
        }
        if (array_key_exists("Name",$param) and $param["Name"] !== null) {
            $this->Name = $param["Name"];
        }

        if (array_key_exists("Username",$param) and $param["Username"] !== null) {
            $this->Username = $param["Username"];
        }

        if (array_key_exists("Password",$param) and $param["Password"] !== null) {
            $this->Password = $param["Password"];
        }

        if (array_key_exists("Url",$param) and $param["Url"] !== null) {
            $this->Url = $param["Url"];
        }

        if (array_key_exists("RegistryType",$param) and $param["RegistryType"] !== null) {
            $this->RegistryType = $param["RegistryType"];
        }

        if (array_key_exists("RegistryVersion",$param) and $param["RegistryVersion"] !== null) {
            $this->RegistryVersion = $param["RegistryVersion"];
        }

        if (array_key_exists("NetType",$param) and $param["NetType"] !== null) {
            $this->NetType = $param["NetType"];
        }

        if (array_key_exists("RegistryRegion",$param) and $param["RegistryRegion"] !== null) {
            $this->RegistryRegion = $param["RegistryRegion"];
        }

        if (array_key_exists("SpeedLimit",$param) and $param["SpeedLimit"] !== null) {
            $this->SpeedLimit = $param["SpeedLimit"];
        }

        if (array_key_exists("Insecure",$param) and $param["Insecure"] !== null) {
            $this->Insecure = $param["Insecure"];
        }

        if (array_key_exists("ConnDetectDetail",$param) and $param["ConnDetectDetail"] !== null) {
            $this->ConnDetectDetail = [];
            foreach ($param["ConnDetectDetail"] as $key => $value){
                $obj = new RegistryConnDetectResult();
                $obj->deserialize($value);
                array_push($this->ConnDetectDetail, $obj);
            }
        }

        if (array_key_exists("InstanceID",$param) and $param["InstanceID"] !== null) {
            $this->InstanceID = $param["InstanceID"];
        }

        if (array_key_exists("SyncMode",$param) and $param["SyncMode"] !== null) {
            $this->SyncMode = $param["SyncMode"];
        }

        if (array_key_exists("NeedScan",$param) and $param["NeedScan"] !== null) {
            $this->NeedScan = $param["NeedScan"];
        }

        if (array_key_exists("WebhookUrl",$param) and $param["WebhookUrl"] !== null) {
            $this->WebhookUrl = $param["WebhookUrl"];
        }

        if (array_key_exists("WebhookToken",$param) and $param["WebhookToken"] !== null) {
            $this->WebhookToken = $param["WebhookToken"];
        }

        if (array_key_exists("RequestId",$param) and $param["RequestId"] !== null) {
            $this->RequestId = $param["RequestId"];
        }
    }
}
