<?php
/*
 * Copyright (c) 2017-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
namespace TencentCloud\Tcss\V20201101\Models;
use TencentCloud\Common\AbstractModel;

/**
 * DescribeImageRegistryTimingScanTask response structure.
 *
 * @method boolean getEnable() Obtain Scheduled scan switch
 * @method void setEnable(boolean $Enable) Set Scheduled scan switch
 * @method string getScanTime() Obtain Scheduled scan time
 * @method void setScanTime(string $ScanTime) Set Scheduled scan time
 * @method integer getScanPeriod() Obtain Scheduled scan interval
 * @method void setScanPeriod(integer $ScanPeriod) Set Scheduled scan interval
 * @method array getScanType() Obtain Scan type array
 * @method void setScanType(array $ScanType) Set Scan type array
 * @method boolean getAll() Obtain Scan of all images
 * @method void setAll(boolean $All) Set Scan of all images
 * @method array getImages() Obtain Custom scan mirror
 * @method void setImages(array $Images) Set Custom scan mirror
 * @method array getId() Obtain Automatically scan the image ID.
 * @method void setId(array $Id) Set Automatically scan the image ID.
 * @method boolean getLatest() Obtain Whether to Scan the Latest Version of Images
 * @method void setLatest(boolean $Latest) Set Whether to Scan the Latest Version of Images
 * @method string getScanEndTime() Obtain Scan end time
 * @method void setScanEndTime(string $ScanEndTime) Set Scan end time
 * @method array getRegistryType() Obtain The registry type
 * @method void setRegistryType(array $RegistryType) Set The registry type
 * @method boolean getContainerRunning() Obtain Is container Running
 * @method void setContainerRunning(boolean $ContainerRunning) Set Is container Running
 * @method integer getScanScope() Obtain The scan scope
 * @method void setScanScope(integer $ScanScope) Set The scan scope
 * @method array getNamespace() Obtain The namespace of image
 * @method void setNamespace(array $Namespace) Set The namespace of image
 * @method array getExcludeImageAssetIds() Obtain IDs of excluded image assets.
 * @method void setExcludeImageAssetIds(array $ExcludeImageAssetIds) Set IDs of excluded image assets.
 * @method string getLastScanTime() Obtain Last scan time
 * @method void setLastScanTime(string $LastScanTime) Set Last scan time
 * @method string getScanResult() Obtain Scanning result. Valid values: Success, InsufficientLicense, ImageNeedIsEmpty, and InternalError.
 * @method void setScanResult(string $ScanResult) Set Scanning result. Valid values: Success, InsufficientLicense, ImageNeedIsEmpty, and InternalError.
 * @method string getRequestId() Obtain The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
 * @method void setRequestId(string $RequestId) Set The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
 */
class DescribeImageRegistryTimingScanTaskResponse extends AbstractModel
{
    /**
     * @var boolean Scheduled scan switch
     */
    public $Enable;

    /**
     * @var string Scheduled scan time
     */
    public $ScanTime;

    /**
     * @var integer Scheduled scan interval
     */
    public $ScanPeriod;

    /**
     * @var array Scan type array
     */
    public $ScanType;

    /**
     * @var boolean Scan of all images
     * @deprecated
     */
    public $All;

    /**
     * @var array Custom scan mirror
     */
    public $Images;

    /**
     * @var array Automatically scan the image ID.
     */
    public $Id;

    /**
     * @var boolean Whether to Scan the Latest Version of Images
     */
    public $Latest;

    /**
     * @var string Scan end time
     */
    public $ScanEndTime;

    /**
     * @var array The registry type
     */
    public $RegistryType;

    /**
     * @var boolean Is container Running
     */
    public $ContainerRunning;

    /**
     * @var integer The scan scope
     */
    public $ScanScope;

    /**
     * @var array The namespace of image
     */
    public $Namespace;

    /**
     * @var array IDs of excluded image assets.
     */
    public $ExcludeImageAssetIds;

    /**
     * @var string Last scan time
     */
    public $LastScanTime;

    /**
     * @var string Scanning result. Valid values: Success, InsufficientLicense, ImageNeedIsEmpty, and InternalError.
     */
    public $ScanResult;

    /**
     * @var string The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    public $RequestId;

    /**
     * @param boolean $Enable Scheduled scan switch
     * @param string $ScanTime Scheduled scan time
     * @param integer $ScanPeriod Scheduled scan interval
     * @param array $ScanType Scan type array
     * @param boolean $All Scan of all images
     * @param array $Images Custom scan mirror
     * @param array $Id Automatically scan the image ID.
     * @param boolean $Latest Whether to Scan the Latest Version of Images
     * @param string $ScanEndTime Scan end time
     * @param array $RegistryType The registry type
     * @param boolean $ContainerRunning Is container Running
     * @param integer $ScanScope The scan scope
     * @param array $Namespace The namespace of image
     * @param array $ExcludeImageAssetIds IDs of excluded image assets.
     * @param string $LastScanTime Last scan time
     * @param string $ScanResult Scanning result. Valid values: Success, InsufficientLicense, ImageNeedIsEmpty, and InternalError.
     * @param string $RequestId The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    function __construct()
    {

    }

    /**
     * For internal only. DO NOT USE IT.
     */
    public function deserialize($param)
    {
        if ($param === null) {
            return;
        }
        if (array_key_exists("Enable",$param) and $param["Enable"] !== null) {
            $this->Enable = $param["Enable"];
        }

        if (array_key_exists("ScanTime",$param) and $param["ScanTime"] !== null) {
            $this->ScanTime = $param["ScanTime"];
        }

        if (array_key_exists("ScanPeriod",$param) and $param["ScanPeriod"] !== null) {
            $this->ScanPeriod = $param["ScanPeriod"];
        }

        if (array_key_exists("ScanType",$param) and $param["ScanType"] !== null) {
            $this->ScanType = $param["ScanType"];
        }

        if (array_key_exists("All",$param) and $param["All"] !== null) {
            $this->All = $param["All"];
        }

        if (array_key_exists("Images",$param) and $param["Images"] !== null) {
            $this->Images = [];
            foreach ($param["Images"] as $key => $value){
                $obj = new ImageInfo();
                $obj->deserialize($value);
                array_push($this->Images, $obj);
            }
        }

        if (array_key_exists("Id",$param) and $param["Id"] !== null) {
            $this->Id = $param["Id"];
        }

        if (array_key_exists("Latest",$param) and $param["Latest"] !== null) {
            $this->Latest = $param["Latest"];
        }

        if (array_key_exists("ScanEndTime",$param) and $param["ScanEndTime"] !== null) {
            $this->ScanEndTime = $param["ScanEndTime"];
        }

        if (array_key_exists("RegistryType",$param) and $param["RegistryType"] !== null) {
            $this->RegistryType = $param["RegistryType"];
        }

        if (array_key_exists("ContainerRunning",$param) and $param["ContainerRunning"] !== null) {
            $this->ContainerRunning = $param["ContainerRunning"];
        }

        if (array_key_exists("ScanScope",$param) and $param["ScanScope"] !== null) {
            $this->ScanScope = $param["ScanScope"];
        }

        if (array_key_exists("Namespace",$param) and $param["Namespace"] !== null) {
            $this->Namespace = $param["Namespace"];
        }

        if (array_key_exists("ExcludeImageAssetIds",$param) and $param["ExcludeImageAssetIds"] !== null) {
            $this->ExcludeImageAssetIds = $param["ExcludeImageAssetIds"];
        }

        if (array_key_exists("LastScanTime",$param) and $param["LastScanTime"] !== null) {
            $this->LastScanTime = $param["LastScanTime"];
        }

        if (array_key_exists("ScanResult",$param) and $param["ScanResult"] !== null) {
            $this->ScanResult = $param["ScanResult"];
        }

        if (array_key_exists("RequestId",$param) and $param["RequestId"] !== null) {
            $this->RequestId = $param["RequestId"];
        }
    }
}
