<?php
/*
 * Copyright (c) 2017-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
namespace TencentCloud\Mps\V20190612\Models;
use TencentCloud\Common\AbstractModel;

/**
 * DescribeBlindWatermarkTemplates response structure.
 *
 * @method integer getTotalCount() Obtain Total number of records that meet the filtering conditions.
 * @method void setTotalCount(integer $TotalCount) Set Total number of records that meet the filtering conditions.
 * @method array getBlindWatermarkTemplateSet() Obtain List of digital watermark template details.
 * @method void setBlindWatermarkTemplateSet(array $BlindWatermarkTemplateSet) Set List of digital watermark template details.
 * @method string getRequestId() Obtain The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
 * @method void setRequestId(string $RequestId) Set The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
 */
class DescribeBlindWatermarkTemplatesResponse extends AbstractModel
{
    /**
     * @var integer Total number of records that meet the filtering conditions.
     */
    public $TotalCount;

    /**
     * @var array List of digital watermark template details.
     */
    public $BlindWatermarkTemplateSet;

    /**
     * @var string The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    public $RequestId;

    /**
     * @param integer $TotalCount Total number of records that meet the filtering conditions.
     * @param array $BlindWatermarkTemplateSet List of digital watermark template details.
     * @param string $RequestId The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    function __construct()
    {

    }

    /**
     * For internal only. DO NOT USE IT.
     */
    public function deserialize($param)
    {
        if ($param === null) {
            return;
        }
        if (array_key_exists("TotalCount",$param) and $param["TotalCount"] !== null) {
            $this->TotalCount = $param["TotalCount"];
        }

        if (array_key_exists("BlindWatermarkTemplateSet",$param) and $param["BlindWatermarkTemplateSet"] !== null) {
            $this->BlindWatermarkTemplateSet = [];
            foreach ($param["BlindWatermarkTemplateSet"] as $key => $value){
                $obj = new BlindWatermarkTemplate();
                $obj->deserialize($value);
                array_push($this->BlindWatermarkTemplateSet, $obj);
            }
        }

        if (array_key_exists("RequestId",$param) and $param["RequestId"] !== null) {
            $this->RequestId = $param["RequestId"];
        }
    }
}
