<?php
/*
 * Copyright (c) 2017-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
namespace TencentCloud\Mps\V20190612\Models;
use TencentCloud\Common\AbstractModel;

/**
 * DetectVideoWatermark response structure.
 *
 * @method float getConfidence() Obtain <p>Confidence of watermark presence.</p><p>Value range: [0, 100].</p>
 * @method void setConfidence(float $Confidence) Set <p>Confidence of watermark presence.</p><p>Value range: [0, 100].</p>
 * @method boolean getHasWatermark() Obtain <p>Indicates whether a watermark is present in the video.</p>
 * @method void setHasWatermark(boolean $HasWatermark) Set <p>Indicates whether a watermark is present in the video.</p>
 * @method string getDescription() Obtain <p>Watermark description.</p>
 * @method void setDescription(string $Description) Set <p>Watermark description.</p>
 * @method string getRequestId() Obtain The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
 * @method void setRequestId(string $RequestId) Set The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
 */
class DetectVideoWatermarkResponse extends AbstractModel
{
    /**
     * @var float <p>Confidence of watermark presence.</p><p>Value range: [0, 100].</p>
     */
    public $Confidence;

    /**
     * @var boolean <p>Indicates whether a watermark is present in the video.</p>
     */
    public $HasWatermark;

    /**
     * @var string <p>Watermark description.</p>
     */
    public $Description;

    /**
     * @var string The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    public $RequestId;

    /**
     * @param float $Confidence <p>Confidence of watermark presence.</p><p>Value range: [0, 100].</p>
     * @param boolean $HasWatermark <p>Indicates whether a watermark is present in the video.</p>
     * @param string $Description <p>Watermark description.</p>
     * @param string $RequestId The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    function __construct()
    {

    }

    /**
     * For internal only. DO NOT USE IT.
     */
    public function deserialize($param)
    {
        if ($param === null) {
            return;
        }
        if (array_key_exists("Confidence",$param) and $param["Confidence"] !== null) {
            $this->Confidence = $param["Confidence"];
        }

        if (array_key_exists("HasWatermark",$param) and $param["HasWatermark"] !== null) {
            $this->HasWatermark = $param["HasWatermark"];
        }

        if (array_key_exists("Description",$param) and $param["Description"] !== null) {
            $this->Description = $param["Description"];
        }

        if (array_key_exists("RequestId",$param) and $param["RequestId"] !== null) {
            $this->RequestId = $param["RequestId"];
        }
    }
}
