<?php
/*
 * Copyright (c) 2017-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
namespace TencentCloud\Mps\V20190612\Models;
use TencentCloud\Common\AbstractModel;

/**
 * SyncDubbing response structure.
 *
 * @method integer getErrorCode() Obtain <p>Error code. 0 is returned if the request is successful.</p>
 * @method void setErrorCode(integer $ErrorCode) Set <p>Error code. 0 is returned if the request is successful.</p>
 * @method string getMsg() Obtain <p>Error message. success is returned if the request is successful.</p>
 * @method void setMsg(string $Msg) Set <p>Error message. success is returned if the request is successful.</p>
 * @method string getAudioData() Obtain <p>Synthetic audio in Base64 encoding and WAV format.</p>
Note: This field may return null, indicating that no valid values can be obtained.
 * @method void setAudioData(string $AudioData) Set <p>Synthetic audio in Base64 encoding and WAV format.</p>
Note: This field may return null, indicating that no valid values can be obtained.
 * @method string getAudioUrl() Obtain <p>Synthetic audio URL. It is valid for 24 hours.</p>
 * @method void setAudioUrl(string $AudioUrl) Set <p>Synthetic audio URL. It is valid for 24 hours.</p>
 * @method string getVoiceId() Obtain <p>Cloned voice ID.</p>
Note: This field may return null, indicating that no valid values can be obtained.
 * @method void setVoiceId(string $VoiceId) Set <p>Cloned voice ID.</p>
Note: This field may return null, indicating that no valid values can be obtained.
 * @method string getExtInfo() Obtain <p>Extended information in the format of a JSON string. </p><p>duration: Duration of the resulting audio, in seconds.</p>
 * @method void setExtInfo(string $ExtInfo) Set <p>Extended information in the format of a JSON string. </p><p>duration: Duration of the resulting audio, in seconds.</p>
 * @method string getRequestId() Obtain The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
 * @method void setRequestId(string $RequestId) Set The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
 */
class SyncDubbingResponse extends AbstractModel
{
    /**
     * @var integer <p>Error code. 0 is returned if the request is successful.</p>
     */
    public $ErrorCode;

    /**
     * @var string <p>Error message. success is returned if the request is successful.</p>
     */
    public $Msg;

    /**
     * @var string <p>Synthetic audio in Base64 encoding and WAV format.</p>
Note: This field may return null, indicating that no valid values can be obtained.
     */
    public $AudioData;

    /**
     * @var string <p>Synthetic audio URL. It is valid for 24 hours.</p>
     */
    public $AudioUrl;

    /**
     * @var string <p>Cloned voice ID.</p>
Note: This field may return null, indicating that no valid values can be obtained.
     */
    public $VoiceId;

    /**
     * @var string <p>Extended information in the format of a JSON string. </p><p>duration: Duration of the resulting audio, in seconds.</p>
     */
    public $ExtInfo;

    /**
     * @var string The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    public $RequestId;

    /**
     * @param integer $ErrorCode <p>Error code. 0 is returned if the request is successful.</p>
     * @param string $Msg <p>Error message. success is returned if the request is successful.</p>
     * @param string $AudioData <p>Synthetic audio in Base64 encoding and WAV format.</p>
Note: This field may return null, indicating that no valid values can be obtained.
     * @param string $AudioUrl <p>Synthetic audio URL. It is valid for 24 hours.</p>
     * @param string $VoiceId <p>Cloned voice ID.</p>
Note: This field may return null, indicating that no valid values can be obtained.
     * @param string $ExtInfo <p>Extended information in the format of a JSON string. </p><p>duration: Duration of the resulting audio, in seconds.</p>
     * @param string $RequestId The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    function __construct()
    {

    }

    /**
     * For internal only. DO NOT USE IT.
     */
    public function deserialize($param)
    {
        if ($param === null) {
            return;
        }
        if (array_key_exists("ErrorCode",$param) and $param["ErrorCode"] !== null) {
            $this->ErrorCode = $param["ErrorCode"];
        }

        if (array_key_exists("Msg",$param) and $param["Msg"] !== null) {
            $this->Msg = $param["Msg"];
        }

        if (array_key_exists("AudioData",$param) and $param["AudioData"] !== null) {
            $this->AudioData = $param["AudioData"];
        }

        if (array_key_exists("AudioUrl",$param) and $param["AudioUrl"] !== null) {
            $this->AudioUrl = $param["AudioUrl"];
        }

        if (array_key_exists("VoiceId",$param) and $param["VoiceId"] !== null) {
            $this->VoiceId = $param["VoiceId"];
        }

        if (array_key_exists("ExtInfo",$param) and $param["ExtInfo"] !== null) {
            $this->ExtInfo = $param["ExtInfo"];
        }

        if (array_key_exists("RequestId",$param) and $param["RequestId"] !== null) {
            $this->RequestId = $param["RequestId"];
        }
    }
}
