<?php
/*
 * Copyright (c) 2017-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
namespace TencentCloud\Mps\V20190612\Models;
use TencentCloud\Common\AbstractModel;

/**
 * SyncDubbing response structure.
 *
 * @method integer getErrorCode() Obtain Error code. 0 is returned if the request is successful.
 * @method void setErrorCode(integer $ErrorCode) Set Error code. 0 is returned if the request is successful.
 * @method string getMsg() Obtain Error message. success is returned if the request is successful.
 * @method void setMsg(string $Msg) Set Error message. success is returned if the request is successful.
 * @method string getAudioData() Obtain Synthetic audio in Base64 encoding and WAV format.
Note: This field may return null, indicating that no valid values can be obtained.
 * @method void setAudioData(string $AudioData) Set Synthetic audio in Base64 encoding and WAV format.
Note: This field may return null, indicating that no valid values can be obtained.
 * @method string getVoiceId() Obtain Cloned voice type ID.
Note: This field may return null, indicating that no valid values can be obtained.
 * @method void setVoiceId(string $VoiceId) Set Cloned voice type ID.
Note: This field may return null, indicating that no valid values can be obtained.
 * @method string getRequestId() Obtain The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
 * @method void setRequestId(string $RequestId) Set The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
 */
class SyncDubbingResponse extends AbstractModel
{
    /**
     * @var integer Error code. 0 is returned if the request is successful.
     */
    public $ErrorCode;

    /**
     * @var string Error message. success is returned if the request is successful.
     */
    public $Msg;

    /**
     * @var string Synthetic audio in Base64 encoding and WAV format.
Note: This field may return null, indicating that no valid values can be obtained.
     */
    public $AudioData;

    /**
     * @var string Cloned voice type ID.
Note: This field may return null, indicating that no valid values can be obtained.
     */
    public $VoiceId;

    /**
     * @var string The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    public $RequestId;

    /**
     * @param integer $ErrorCode Error code. 0 is returned if the request is successful.
     * @param string $Msg Error message. success is returned if the request is successful.
     * @param string $AudioData Synthetic audio in Base64 encoding and WAV format.
Note: This field may return null, indicating that no valid values can be obtained.
     * @param string $VoiceId Cloned voice type ID.
Note: This field may return null, indicating that no valid values can be obtained.
     * @param string $RequestId The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    function __construct()
    {

    }

    /**
     * For internal only. DO NOT USE IT.
     */
    public function deserialize($param)
    {
        if ($param === null) {
            return;
        }
        if (array_key_exists("ErrorCode",$param) and $param["ErrorCode"] !== null) {
            $this->ErrorCode = $param["ErrorCode"];
        }

        if (array_key_exists("Msg",$param) and $param["Msg"] !== null) {
            $this->Msg = $param["Msg"];
        }

        if (array_key_exists("AudioData",$param) and $param["AudioData"] !== null) {
            $this->AudioData = $param["AudioData"];
        }

        if (array_key_exists("VoiceId",$param) and $param["VoiceId"] !== null) {
            $this->VoiceId = $param["VoiceId"];
        }

        if (array_key_exists("RequestId",$param) and $param["RequestId"] !== null) {
            $this->RequestId = $param["RequestId"];
        }
    }
}
