<?php
/*
 * Copyright (c) 2017-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
namespace TencentCloud\Cynosdb\V20190107\Models;
use TencentCloud\Common\AbstractModel;

/**
 * DescribeClusterStorageAutoExpand response structure.
 *
 * @method integer getStorageUsageThreshold() Obtain <p>Storage utilization threshold</p>
 * @method void setStorageUsageThreshold(integer $StorageUsageThreshold) Set <p>Storage utilization threshold</p>
 * @method integer getExpandStep() Obtain <p>Scaling increment</p>
 * @method void setExpandStep(integer $ExpandStep) Set <p>Scaling increment</p>
 * @method integer getMaxStorageLimit() Obtain <p>Maximum storage capacity limit</p>
 * @method void setMaxStorageLimit(integer $MaxStorageLimit) Set <p>Maximum storage capacity limit</p>
 * @method string getStorageAutoExpand() Obtain <p>Whether to enable: yes-enabled, no-disabled</p>
 * @method void setStorageAutoExpand(string $StorageAutoExpand) Set <p>Whether to enable: yes-enabled, no-disabled</p>
 * @method string getRequestId() Obtain The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
 * @method void setRequestId(string $RequestId) Set The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
 */
class DescribeClusterStorageAutoExpandResponse extends AbstractModel
{
    /**
     * @var integer <p>Storage utilization threshold</p>
     */
    public $StorageUsageThreshold;

    /**
     * @var integer <p>Scaling increment</p>
     */
    public $ExpandStep;

    /**
     * @var integer <p>Maximum storage capacity limit</p>
     */
    public $MaxStorageLimit;

    /**
     * @var string <p>Whether to enable: yes-enabled, no-disabled</p>
     */
    public $StorageAutoExpand;

    /**
     * @var string The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    public $RequestId;

    /**
     * @param integer $StorageUsageThreshold <p>Storage utilization threshold</p>
     * @param integer $ExpandStep <p>Scaling increment</p>
     * @param integer $MaxStorageLimit <p>Maximum storage capacity limit</p>
     * @param string $StorageAutoExpand <p>Whether to enable: yes-enabled, no-disabled</p>
     * @param string $RequestId The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    function __construct()
    {

    }

    /**
     * For internal only. DO NOT USE IT.
     */
    public function deserialize($param)
    {
        if ($param === null) {
            return;
        }
        if (array_key_exists("StorageUsageThreshold",$param) and $param["StorageUsageThreshold"] !== null) {
            $this->StorageUsageThreshold = $param["StorageUsageThreshold"];
        }

        if (array_key_exists("ExpandStep",$param) and $param["ExpandStep"] !== null) {
            $this->ExpandStep = $param["ExpandStep"];
        }

        if (array_key_exists("MaxStorageLimit",$param) and $param["MaxStorageLimit"] !== null) {
            $this->MaxStorageLimit = $param["MaxStorageLimit"];
        }

        if (array_key_exists("StorageAutoExpand",$param) and $param["StorageAutoExpand"] !== null) {
            $this->StorageAutoExpand = $param["StorageAutoExpand"];
        }

        if (array_key_exists("RequestId",$param) and $param["RequestId"] !== null) {
            $this->RequestId = $param["RequestId"];
        }
    }
}
