<?php
/*
 * Copyright (c) 2017-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
namespace TencentCloud\Cynosdb\V20190107\Models;
use TencentCloud\Common\AbstractModel;

/**
 * DescribeLibraDBClusterAccountAllPrivileges response structure.
 *
 * @method array getPrivilegeStatements() Obtain Permission statement
Note: This field may return null, indicating that no valid values can be obtained.
 * @method void setPrivilegeStatements(array $PrivilegeStatements) Set Permission statement
Note: This field may return null, indicating that no valid values can be obtained.
 * @method array getGlobalPrivileges() Obtain Global permission
Note: This field may return null, indicating that no valid values can be obtained.
 * @method void setGlobalPrivileges(array $GlobalPrivileges) Set Global permission
Note: This field may return null, indicating that no valid values can be obtained.
 * @method array getDatabasePrivileges() Obtain Database permission
Note: This field may return null, indicating that no valid values can be obtained.
 * @method void setDatabasePrivileges(array $DatabasePrivileges) Set Database permission
Note: This field may return null, indicating that no valid values can be obtained.
 * @method array getTablePrivileges() Obtain Table permission
Note: This field may return null, indicating that no valid values can be obtained.
 * @method void setTablePrivileges(array $TablePrivileges) Set Table permission
Note: This field may return null, indicating that no valid values can be obtained.
 * @method string getRequestId() Obtain The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
 * @method void setRequestId(string $RequestId) Set The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
 */
class DescribeLibraDBClusterAccountAllPrivilegesResponse extends AbstractModel
{
    /**
     * @var array Permission statement
Note: This field may return null, indicating that no valid values can be obtained.
     */
    public $PrivilegeStatements;

    /**
     * @var array Global permission
Note: This field may return null, indicating that no valid values can be obtained.
     */
    public $GlobalPrivileges;

    /**
     * @var array Database permission
Note: This field may return null, indicating that no valid values can be obtained.
     */
    public $DatabasePrivileges;

    /**
     * @var array Table permission
Note: This field may return null, indicating that no valid values can be obtained.
     */
    public $TablePrivileges;

    /**
     * @var string The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    public $RequestId;

    /**
     * @param array $PrivilegeStatements Permission statement
Note: This field may return null, indicating that no valid values can be obtained.
     * @param array $GlobalPrivileges Global permission
Note: This field may return null, indicating that no valid values can be obtained.
     * @param array $DatabasePrivileges Database permission
Note: This field may return null, indicating that no valid values can be obtained.
     * @param array $TablePrivileges Table permission
Note: This field may return null, indicating that no valid values can be obtained.
     * @param string $RequestId The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    function __construct()
    {

    }

    /**
     * For internal only. DO NOT USE IT.
     */
    public function deserialize($param)
    {
        if ($param === null) {
            return;
        }
        if (array_key_exists("PrivilegeStatements",$param) and $param["PrivilegeStatements"] !== null) {
            $this->PrivilegeStatements = $param["PrivilegeStatements"];
        }

        if (array_key_exists("GlobalPrivileges",$param) and $param["GlobalPrivileges"] !== null) {
            $this->GlobalPrivileges = $param["GlobalPrivileges"];
        }

        if (array_key_exists("DatabasePrivileges",$param) and $param["DatabasePrivileges"] !== null) {
            $this->DatabasePrivileges = [];
            foreach ($param["DatabasePrivileges"] as $key => $value){
                $obj = new DatabasePrivileges();
                $obj->deserialize($value);
                array_push($this->DatabasePrivileges, $obj);
            }
        }

        if (array_key_exists("TablePrivileges",$param) and $param["TablePrivileges"] !== null) {
            $this->TablePrivileges = [];
            foreach ($param["TablePrivileges"] as $key => $value){
                $obj = new TablePrivileges();
                $obj->deserialize($value);
                array_push($this->TablePrivileges, $obj);
            }
        }

        if (array_key_exists("RequestId",$param) and $param["RequestId"] !== null) {
            $this->RequestId = $param["RequestId"];
        }
    }
}
