<?php
/*
 * Copyright (c) 2017-2018 THL A29 Limited, a Tencent company. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
namespace TencentCloud\Antiddos\V20200309\Models;
use TencentCloud\Common\AbstractModel;

/**
 * DescribeCcGeoIPBlockConfigList response structure.
 *
 * @method integer getTotal() Obtain Number of policy lists
 * @method void setTotal(integer $Total) Set Number of policy lists
 * @method array getCcGeoIpPolicyList() Obtain Information of the policy list
 * @method void setCcGeoIpPolicyList(array $CcGeoIpPolicyList) Set Information of the policy list
 * @method string getRequestId() Obtain The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
 * @method void setRequestId(string $RequestId) Set The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
 */
class DescribeCcGeoIPBlockConfigListResponse extends AbstractModel
{
    /**
     * @var integer Number of policy lists
     */
    public $Total;

    /**
     * @var array Information of the policy list
     */
    public $CcGeoIpPolicyList;

    /**
     * @var string The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    public $RequestId;

    /**
     * @param integer $Total Number of policy lists
     * @param array $CcGeoIpPolicyList Information of the policy list
     * @param string $RequestId The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    function __construct()
    {

    }

    /**
     * For internal only. DO NOT USE IT.
     */
    public function deserialize($param)
    {
        if ($param === null) {
            return;
        }
        if (array_key_exists("Total",$param) and $param["Total"] !== null) {
            $this->Total = $param["Total"];
        }

        if (array_key_exists("CcGeoIpPolicyList",$param) and $param["CcGeoIpPolicyList"] !== null) {
            $this->CcGeoIpPolicyList = [];
            foreach ($param["CcGeoIpPolicyList"] as $key => $value){
                $obj = new CcGeoIpPolicyNew();
                $obj->deserialize($value);
                array_push($this->CcGeoIpPolicyList, $obj);
            }
        }

        if (array_key_exists("RequestId",$param) and $param["RequestId"] !== null) {
            $this->RequestId = $param["RequestId"];
        }
    }
}
