<?php
/*
 * Copyright (c) 2017-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
namespace TencentCloud\Billing\V20180709\Models;
use TencentCloud\Common\AbstractModel;

/**
 * CreateInstance request structure.
 *
 * @method string getClientToken() Obtain ClientToken is an unique, case-sensitive string generated by the client with no more than 64 ASCII characters. for example, ClientToken=123e4567-e89b-12d3-a456-42665544****.
 * @method void setClientToken(string $ClientToken) Set ClientToken is an unique, case-sensitive string generated by the client with no more than 64 ASCII characters. for example, ClientToken=123e4567-e89b-12d3-a456-42665544****.
 * @method string getProductCode() Obtain Product code.
 * @method void setProductCode(string $ProductCode) Set Product code.
 * @method string getSubProductCode() Obtain Sub-product code.
 * @method void setSubProductCode(string $SubProductCode) Set Sub-product code.
 * @method string getRegionCode() Obtain Region code.
 * @method void setRegionCode(string $RegionCode) Set Region code.
 * @method string getZoneCode() Obtain Availability zone code.
 * @method void setZoneCode(string $ZoneCode) Set Availability zone code.
 * @method string getPayMode() Obtain Payment mode. Available values: PrePay: upfront charge.
 * @method void setPayMode(string $PayMode) Set Payment mode. Available values: PrePay: upfront charge.
 * @method string getParameter() Obtain Product detailed information.
 * @method void setParameter(string $Parameter) Set Product detailed information.
 * @method integer getQuantity() Obtain Product quantity, default value is 1.
 * @method void setQuantity(integer $Quantity) Set Product quantity, default value is 1.
 * @method integer getProjectId() Obtain Project id, default value is 0.
 * @method void setProjectId(integer $ProjectId) Set Project id, default value is 0.
 * @method integer getPeriod() Obtain Purchase duration, max number is 36, default value is 1.
 * @method void setPeriod(integer $Period) Set Purchase duration, max number is 36, default value is 1.
 * @method string getPeriodUnit() Obtain Purchase duration unit. valid values: 
m: month,
y: year. 
default value is: m.
 * @method void setPeriodUnit(string $PeriodUnit) Set Purchase duration unit. valid values: 
m: month,
y: year. 
default value is: m.
 * @method string getRenewFlag() Obtain Auto-renewal flag. valid values: NOTIFY_AND_MANUAL_RENEW: manually renew, NOTIFY_AND_AUTO_RENEW: automatically renew, DISABLE_NOTIFY_AND_MANUAL_RENEW: renewal is disabled. 
default value is NOTIFY_AND_MANUAL_RENEW.
 * @method void setRenewFlag(string $RenewFlag) Set Auto-renewal flag. valid values: NOTIFY_AND_MANUAL_RENEW: manually renew, NOTIFY_AND_AUTO_RENEW: automatically renew, DISABLE_NOTIFY_AND_MANUAL_RENEW: renewal is disabled. 
default value is NOTIFY_AND_MANUAL_RENEW.
 */
class CreateInstanceRequest extends AbstractModel
{
    /**
     * @var string ClientToken is an unique, case-sensitive string generated by the client with no more than 64 ASCII characters. for example, ClientToken=123e4567-e89b-12d3-a456-42665544****.
     */
    public $ClientToken;

    /**
     * @var string Product code.
     */
    public $ProductCode;

    /**
     * @var string Sub-product code.
     */
    public $SubProductCode;

    /**
     * @var string Region code.
     */
    public $RegionCode;

    /**
     * @var string Availability zone code.
     */
    public $ZoneCode;

    /**
     * @var string Payment mode. Available values: PrePay: upfront charge.
     */
    public $PayMode;

    /**
     * @var string Product detailed information.
     */
    public $Parameter;

    /**
     * @var integer Product quantity, default value is 1.
     */
    public $Quantity;

    /**
     * @var integer Project id, default value is 0.
     */
    public $ProjectId;

    /**
     * @var integer Purchase duration, max number is 36, default value is 1.
     */
    public $Period;

    /**
     * @var string Purchase duration unit. valid values: 
m: month,
y: year. 
default value is: m.
     */
    public $PeriodUnit;

    /**
     * @var string Auto-renewal flag. valid values: NOTIFY_AND_MANUAL_RENEW: manually renew, NOTIFY_AND_AUTO_RENEW: automatically renew, DISABLE_NOTIFY_AND_MANUAL_RENEW: renewal is disabled. 
default value is NOTIFY_AND_MANUAL_RENEW.
     */
    public $RenewFlag;

    /**
     * @param string $ClientToken ClientToken is an unique, case-sensitive string generated by the client with no more than 64 ASCII characters. for example, ClientToken=123e4567-e89b-12d3-a456-42665544****.
     * @param string $ProductCode Product code.
     * @param string $SubProductCode Sub-product code.
     * @param string $RegionCode Region code.
     * @param string $ZoneCode Availability zone code.
     * @param string $PayMode Payment mode. Available values: PrePay: upfront charge.
     * @param string $Parameter Product detailed information.
     * @param integer $Quantity Product quantity, default value is 1.
     * @param integer $ProjectId Project id, default value is 0.
     * @param integer $Period Purchase duration, max number is 36, default value is 1.
     * @param string $PeriodUnit Purchase duration unit. valid values: 
m: month,
y: year. 
default value is: m.
     * @param string $RenewFlag Auto-renewal flag. valid values: NOTIFY_AND_MANUAL_RENEW: manually renew, NOTIFY_AND_AUTO_RENEW: automatically renew, DISABLE_NOTIFY_AND_MANUAL_RENEW: renewal is disabled. 
default value is NOTIFY_AND_MANUAL_RENEW.
     */
    function __construct()
    {

    }

    /**
     * For internal only. DO NOT USE IT.
     */
    public function deserialize($param)
    {
        if ($param === null) {
            return;
        }
        if (array_key_exists("ClientToken",$param) and $param["ClientToken"] !== null) {
            $this->ClientToken = $param["ClientToken"];
        }

        if (array_key_exists("ProductCode",$param) and $param["ProductCode"] !== null) {
            $this->ProductCode = $param["ProductCode"];
        }

        if (array_key_exists("SubProductCode",$param) and $param["SubProductCode"] !== null) {
            $this->SubProductCode = $param["SubProductCode"];
        }

        if (array_key_exists("RegionCode",$param) and $param["RegionCode"] !== null) {
            $this->RegionCode = $param["RegionCode"];
        }

        if (array_key_exists("ZoneCode",$param) and $param["ZoneCode"] !== null) {
            $this->ZoneCode = $param["ZoneCode"];
        }

        if (array_key_exists("PayMode",$param) and $param["PayMode"] !== null) {
            $this->PayMode = $param["PayMode"];
        }

        if (array_key_exists("Parameter",$param) and $param["Parameter"] !== null) {
            $this->Parameter = $param["Parameter"];
        }

        if (array_key_exists("Quantity",$param) and $param["Quantity"] !== null) {
            $this->Quantity = $param["Quantity"];
        }

        if (array_key_exists("ProjectId",$param) and $param["ProjectId"] !== null) {
            $this->ProjectId = $param["ProjectId"];
        }

        if (array_key_exists("Period",$param) and $param["Period"] !== null) {
            $this->Period = $param["Period"];
        }

        if (array_key_exists("PeriodUnit",$param) and $param["PeriodUnit"] !== null) {
            $this->PeriodUnit = $param["PeriodUnit"];
        }

        if (array_key_exists("RenewFlag",$param) and $param["RenewFlag"] !== null) {
            $this->RenewFlag = $param["RenewFlag"];
        }
    }
}
