<?php
/*
 * Copyright (c) 2017-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
namespace TencentCloud\Billing\V20180709\Models;
use TencentCloud\Common\AbstractModel;

/**
 * DescribeCostExplorerSummary response structure.
 *
 * @method integer getTotal() Obtain Number of data records
 * @method void setTotal(integer $Total) Set Number of data records
 * @method AnalyseHeaderDetail getHeader() Obtain Header information.
 * @method void setHeader(AnalyseHeaderDetail $Header) Set Header information.
 * @method array getDetail() Obtain Data details
 * @method void setDetail(array $Detail) Set Data details
 * @method AnalyseDetail getTotalDetail() Obtain data total
 * @method void setTotalDetail(AnalyseDetail $TotalDetail) Set data total
 * @method AnalyseConditionDetail getConditionValue() Obtain filtering box
 * @method void setConditionValue(AnalyseConditionDetail $ConditionValue) Set filtering box
 * @method string getRequestId() Obtain The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
 * @method void setRequestId(string $RequestId) Set The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
 */
class DescribeCostExplorerSummaryResponse extends AbstractModel
{
    /**
     * @var integer Number of data records
     */
    public $Total;

    /**
     * @var AnalyseHeaderDetail Header information.
     */
    public $Header;

    /**
     * @var array Data details
     */
    public $Detail;

    /**
     * @var AnalyseDetail data total
     */
    public $TotalDetail;

    /**
     * @var AnalyseConditionDetail filtering box
     */
    public $ConditionValue;

    /**
     * @var string The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    public $RequestId;

    /**
     * @param integer $Total Number of data records
     * @param AnalyseHeaderDetail $Header Header information.
     * @param array $Detail Data details
     * @param AnalyseDetail $TotalDetail data total
     * @param AnalyseConditionDetail $ConditionValue filtering box
     * @param string $RequestId The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    function __construct()
    {

    }

    /**
     * For internal only. DO NOT USE IT.
     */
    public function deserialize($param)
    {
        if ($param === null) {
            return;
        }
        if (array_key_exists("Total",$param) and $param["Total"] !== null) {
            $this->Total = $param["Total"];
        }

        if (array_key_exists("Header",$param) and $param["Header"] !== null) {
            $this->Header = new AnalyseHeaderDetail();
            $this->Header->deserialize($param["Header"]);
        }

        if (array_key_exists("Detail",$param) and $param["Detail"] !== null) {
            $this->Detail = [];
            foreach ($param["Detail"] as $key => $value){
                $obj = new AnalyseDetail();
                $obj->deserialize($value);
                array_push($this->Detail, $obj);
            }
        }

        if (array_key_exists("TotalDetail",$param) and $param["TotalDetail"] !== null) {
            $this->TotalDetail = new AnalyseDetail();
            $this->TotalDetail->deserialize($param["TotalDetail"]);
        }

        if (array_key_exists("ConditionValue",$param) and $param["ConditionValue"] !== null) {
            $this->ConditionValue = new AnalyseConditionDetail();
            $this->ConditionValue->deserialize($param["ConditionValue"]);
        }

        if (array_key_exists("RequestId",$param) and $param["RequestId"] !== null) {
            $this->RequestId = $param["RequestId"];
        }
    }
}
