<?php
/*
 * Copyright (c) 2017-2018 THL A29 Limited, a Tencent company. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
namespace TencentCloud\Billing\V20180709\Models;
use TencentCloud\Common\AbstractModel;

/**
 * DescribeAllocationRuleDetail response structure.
 *
 * @method integer getId() Obtain Sharing rule ID.
 * @method void setId(integer $Id) Set Sharing rule ID.
 * @method string getUin() Obtain Sharing rule ownership UIN.
 * @method void setUin(string $Uin) Set Sharing rule ownership UIN.
 * @method string getName() Obtain Sharing rule name.
 * @method void setName(string $Name) Set Sharing rule name.
 * @method integer getType() Obtain Specifies the public area policy type. the enumeration values are as follows:.
1 - custom sharing proportion. 
2 - proportional allocation. 
3 - allocation by proportion.
 * @method void setType(integer $Type) Set Specifies the public area policy type. the enumeration values are as follows:.
1 - custom sharing proportion. 
2 - proportional allocation. 
3 - allocation by proportion.
 * @method AllocationRuleExpression getRuleDetail() Obtain Public sharing rule expression.
 * @method void setRuleDetail(AllocationRuleExpression $RuleDetail) Set Public sharing rule expression.
 * @method array getRatioDetail() Obtain Sharing proportion expression. returns when Type is 1 or 2.
 * @method void setRatioDetail(array $RatioDetail) Set Sharing proportion expression. returns when Type is 1 or 2.
 * @method string getRequestId() Obtain The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
 * @method void setRequestId(string $RequestId) Set The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
 */
class DescribeAllocationRuleDetailResponse extends AbstractModel
{
    /**
     * @var integer Sharing rule ID.
     */
    public $Id;

    /**
     * @var string Sharing rule ownership UIN.
     */
    public $Uin;

    /**
     * @var string Sharing rule name.
     */
    public $Name;

    /**
     * @var integer Specifies the public area policy type. the enumeration values are as follows:.
1 - custom sharing proportion. 
2 - proportional allocation. 
3 - allocation by proportion.
     */
    public $Type;

    /**
     * @var AllocationRuleExpression Public sharing rule expression.
     */
    public $RuleDetail;

    /**
     * @var array Sharing proportion expression. returns when Type is 1 or 2.
     */
    public $RatioDetail;

    /**
     * @var string The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    public $RequestId;

    /**
     * @param integer $Id Sharing rule ID.
     * @param string $Uin Sharing rule ownership UIN.
     * @param string $Name Sharing rule name.
     * @param integer $Type Specifies the public area policy type. the enumeration values are as follows:.
1 - custom sharing proportion. 
2 - proportional allocation. 
3 - allocation by proportion.
     * @param AllocationRuleExpression $RuleDetail Public sharing rule expression.
     * @param array $RatioDetail Sharing proportion expression. returns when Type is 1 or 2.
     * @param string $RequestId The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    function __construct()
    {

    }

    /**
     * For internal only. DO NOT USE IT.
     */
    public function deserialize($param)
    {
        if ($param === null) {
            return;
        }
        if (array_key_exists("Id",$param) and $param["Id"] !== null) {
            $this->Id = $param["Id"];
        }

        if (array_key_exists("Uin",$param) and $param["Uin"] !== null) {
            $this->Uin = $param["Uin"];
        }

        if (array_key_exists("Name",$param) and $param["Name"] !== null) {
            $this->Name = $param["Name"];
        }

        if (array_key_exists("Type",$param) and $param["Type"] !== null) {
            $this->Type = $param["Type"];
        }

        if (array_key_exists("RuleDetail",$param) and $param["RuleDetail"] !== null) {
            $this->RuleDetail = new AllocationRuleExpression();
            $this->RuleDetail->deserialize($param["RuleDetail"]);
        }

        if (array_key_exists("RatioDetail",$param) and $param["RatioDetail"] !== null) {
            $this->RatioDetail = [];
            foreach ($param["RatioDetail"] as $key => $value){
                $obj = new AllocationRationExpression();
                $obj->deserialize($value);
                array_push($this->RatioDetail, $obj);
            }
        }

        if (array_key_exists("RequestId",$param) and $param["RequestId"] !== null) {
            $this->RequestId = $param["RequestId"];
        }
    }
}
