<?php
/*
 * Copyright (c) 2017-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
namespace TencentCloud\Billing\V20180709\Models;
use TencentCloud\Common\AbstractModel;

/**
 * RefundInstance request structure.
 *
 * @method string getClientToken() Obtain ClientToken is a unique, case-sensitive string generated by the client, no more than 64 ASCII characters. for example, ClientToken=123e4567-e89b-12d3-a456-42665544****.
 * @method void setClientToken(string $ClientToken) Set ClientToken is a unique, case-sensitive string generated by the client, no more than 64 ASCII characters. for example, ClientToken=123e4567-e89b-12d3-a456-42665544****.
 * @method string getProductCode() Obtain Product code.
 * @method void setProductCode(string $ProductCode) Set Product code.
 * @method string getSubProductCode() Obtain Sub-product code.
 * @method void setSubProductCode(string $SubProductCode) Set Sub-product code.
 * @method string getInstanceId() Obtain Instance ID.
 * @method void setInstanceId(string $InstanceId) Set Instance ID.
 * @method string getRegionCode() Obtain Region code.
 * @method void setRegionCode(string $RegionCode) Set Region code.
 */
class RefundInstanceRequest extends AbstractModel
{
    /**
     * @var string ClientToken is a unique, case-sensitive string generated by the client, no more than 64 ASCII characters. for example, ClientToken=123e4567-e89b-12d3-a456-42665544****.
     */
    public $ClientToken;

    /**
     * @var string Product code.
     */
    public $ProductCode;

    /**
     * @var string Sub-product code.
     */
    public $SubProductCode;

    /**
     * @var string Instance ID.
     */
    public $InstanceId;

    /**
     * @var string Region code.
     */
    public $RegionCode;

    /**
     * @param string $ClientToken ClientToken is a unique, case-sensitive string generated by the client, no more than 64 ASCII characters. for example, ClientToken=123e4567-e89b-12d3-a456-42665544****.
     * @param string $ProductCode Product code.
     * @param string $SubProductCode Sub-product code.
     * @param string $InstanceId Instance ID.
     * @param string $RegionCode Region code.
     */
    function __construct()
    {

    }

    /**
     * For internal only. DO NOT USE IT.
     */
    public function deserialize($param)
    {
        if ($param === null) {
            return;
        }
        if (array_key_exists("ClientToken",$param) and $param["ClientToken"] !== null) {
            $this->ClientToken = $param["ClientToken"];
        }

        if (array_key_exists("ProductCode",$param) and $param["ProductCode"] !== null) {
            $this->ProductCode = $param["ProductCode"];
        }

        if (array_key_exists("SubProductCode",$param) and $param["SubProductCode"] !== null) {
            $this->SubProductCode = $param["SubProductCode"];
        }

        if (array_key_exists("InstanceId",$param) and $param["InstanceId"] !== null) {
            $this->InstanceId = $param["InstanceId"];
        }

        if (array_key_exists("RegionCode",$param) and $param["RegionCode"] !== null) {
            $this->RegionCode = $param["RegionCode"];
        }
    }
}
