<?php
/*
 * Copyright (c) 2017-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
namespace TencentCloud\Cwp\V20180228\Models;
use TencentCloud\Common\AbstractModel;

/**
 * DescribePatchInfo response structure.
 *
 * @method string getKbNo() Obtain kb No.
 * @method void setKbNo(string $KbNo) Set kb No.
 * @method string getPatchName() Obtain kb name
 * @method void setPatchName(string $PatchName) Set kb name
 * @method string getPublishTime() Obtain kb release date
 * @method void setPublishTime(string $PublishTime) Set kb release date
 * @method string getReferUrl() Obtain Reference link
 * @method void setReferUrl(string $ReferUrl) Set Reference link
 * @method integer getVulCount() Obtain Number of vulnerabilities
 * @method void setVulCount(integer $VulCount) Set Number of vulnerabilities
 * @method array getRelateVulInfoList() Obtain List of vulnerability details associated with the patch
 * @method void setRelateVulInfoList(array $RelateVulInfoList) Set List of vulnerability details associated with the patch
 * @method integer getKbId() Obtain Patch ID
 * @method void setKbId(integer $KbId) Set Patch ID
 * @method string getRelateVulCveId() Obtain Associated vulnerability CveId, multiple IDs split by ","
 * @method void setRelateVulCveId(string $RelateVulCveId) Set Associated vulnerability CveId, multiple IDs split by ","
 * @method string getRequestId() Obtain The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
 * @method void setRequestId(string $RequestId) Set The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
 */
class DescribePatchInfoResponse extends AbstractModel
{
    /**
     * @var string kb No.
     */
    public $KbNo;

    /**
     * @var string kb name
     */
    public $PatchName;

    /**
     * @var string kb release date
     */
    public $PublishTime;

    /**
     * @var string Reference link
     */
    public $ReferUrl;

    /**
     * @var integer Number of vulnerabilities
     */
    public $VulCount;

    /**
     * @var array List of vulnerability details associated with the patch
     */
    public $RelateVulInfoList;

    /**
     * @var integer Patch ID
     */
    public $KbId;

    /**
     * @var string Associated vulnerability CveId, multiple IDs split by ","
     */
    public $RelateVulCveId;

    /**
     * @var string The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    public $RequestId;

    /**
     * @param string $KbNo kb No.
     * @param string $PatchName kb name
     * @param string $PublishTime kb release date
     * @param string $ReferUrl Reference link
     * @param integer $VulCount Number of vulnerabilities
     * @param array $RelateVulInfoList List of vulnerability details associated with the patch
     * @param integer $KbId Patch ID
     * @param string $RelateVulCveId Associated vulnerability CveId, multiple IDs split by ","
     * @param string $RequestId The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    function __construct()
    {

    }

    /**
     * For internal only. DO NOT USE IT.
     */
    public function deserialize($param)
    {
        if ($param === null) {
            return;
        }
        if (array_key_exists("KbNo",$param) and $param["KbNo"] !== null) {
            $this->KbNo = $param["KbNo"];
        }

        if (array_key_exists("PatchName",$param) and $param["PatchName"] !== null) {
            $this->PatchName = $param["PatchName"];
        }

        if (array_key_exists("PublishTime",$param) and $param["PublishTime"] !== null) {
            $this->PublishTime = $param["PublishTime"];
        }

        if (array_key_exists("ReferUrl",$param) and $param["ReferUrl"] !== null) {
            $this->ReferUrl = $param["ReferUrl"];
        }

        if (array_key_exists("VulCount",$param) and $param["VulCount"] !== null) {
            $this->VulCount = $param["VulCount"];
        }

        if (array_key_exists("RelateVulInfoList",$param) and $param["RelateVulInfoList"] !== null) {
            $this->RelateVulInfoList = [];
            foreach ($param["RelateVulInfoList"] as $key => $value){
                $obj = new RelateVulInfo();
                $obj->deserialize($value);
                array_push($this->RelateVulInfoList, $obj);
            }
        }

        if (array_key_exists("KbId",$param) and $param["KbId"] !== null) {
            $this->KbId = $param["KbId"];
        }

        if (array_key_exists("RelateVulCveId",$param) and $param["RelateVulCveId"] !== null) {
            $this->RelateVulCveId = $param["RelateVulCveId"];
        }

        if (array_key_exists("RequestId",$param) and $param["RequestId"] !== null) {
            $this->RequestId = $param["RequestId"];
        }
    }
}
