<?php
/*
 * Copyright (c) 2017-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
namespace TencentCloud\Cwp\V20180228\Models;
use TencentCloud\Common\AbstractModel;

/**
 * DescribeUndoVulCounts response structure.
 *
 * @method integer getUndoVulCount() Obtain Number of unfixed vulnerabilities
 * @method void setUndoVulCount(integer $UndoVulCount) Set Number of unfixed vulnerabilities
 * @method integer getUndoHostCount() Obtain Number of Unprocessed Hosts
 * @method void setUndoHostCount(integer $UndoHostCount) Set Number of Unprocessed Hosts
 * @method integer getNotProfessionCount() Obtain Number of Standard Edition hosts
 * @method void setNotProfessionCount(integer $NotProfessionCount) Set Number of Standard Edition hosts
 * @method string getRequestId() Obtain The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
 * @method void setRequestId(string $RequestId) Set The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
 */
class DescribeUndoVulCountsResponse extends AbstractModel
{
    /**
     * @var integer Number of unfixed vulnerabilities
     */
    public $UndoVulCount;

    /**
     * @var integer Number of Unprocessed Hosts
     */
    public $UndoHostCount;

    /**
     * @var integer Number of Standard Edition hosts
     */
    public $NotProfessionCount;

    /**
     * @var string The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    public $RequestId;

    /**
     * @param integer $UndoVulCount Number of unfixed vulnerabilities
     * @param integer $UndoHostCount Number of Unprocessed Hosts
     * @param integer $NotProfessionCount Number of Standard Edition hosts
     * @param string $RequestId The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    function __construct()
    {

    }

    /**
     * For internal only. DO NOT USE IT.
     */
    public function deserialize($param)
    {
        if ($param === null) {
            return;
        }
        if (array_key_exists("UndoVulCount",$param) and $param["UndoVulCount"] !== null) {
            $this->UndoVulCount = $param["UndoVulCount"];
        }

        if (array_key_exists("UndoHostCount",$param) and $param["UndoHostCount"] !== null) {
            $this->UndoHostCount = $param["UndoHostCount"];
        }

        if (array_key_exists("NotProfessionCount",$param) and $param["NotProfessionCount"] !== null) {
            $this->NotProfessionCount = $param["NotProfessionCount"];
        }

        if (array_key_exists("RequestId",$param) and $param["RequestId"] !== null) {
            $this->RequestId = $param["RequestId"];
        }
    }
}
