<?php
/*
 * Copyright (c) 2017-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
namespace TencentCloud\Cwp\V20180228\Models;
use TencentCloud\Common\AbstractModel;

/**
 * DescribeBanStatus response structure.
 *
 * @method integer getStatus() Obtain (Abandoned) Block switch status: 0 -- Off 1 -- Advanced blocking 2 -- Basic block (blocklist IPs in the intelligence database)
 * @method void setStatus(integer $Status) Set (Abandoned) Block switch status: 0 -- Off 1 -- Advanced blocking 2 -- Basic block (blocklist IPs in the intelligence database)
 * @method boolean getShowTips() Obtain Whether to display the pop-up prompt. False: no; true: yes.
 * @method void setShowTips(boolean $ShowTips) Set Whether to display the pop-up prompt. False: no; true: yes.
 * @method boolean getOpenSmartMode() Obtain Whether to enable intelligent over-allowing mode
 * @method void setOpenSmartMode(boolean $OpenSmartMode) Set Whether to enable intelligent over-allowing mode
 * @method boolean getBanBlackIp() Obtain Whether intelligence IP blocking is enabled
 * @method void setBanBlackIp(boolean $BanBlackIp) Set Whether intelligence IP blocking is enabled
 * @method boolean getBanVulIp() Obtain Whether vulnerability IP blocking is enabled
 * @method void setBanVulIp(boolean $BanVulIp) Set Whether vulnerability IP blocking is enabled
 * @method boolean getBanByRule() Obtain Whether to enable rule blocking
 * @method void setBanByRule(boolean $BanByRule) Set Whether to enable rule blocking
 * @method string getRequestId() Obtain The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
 * @method void setRequestId(string $RequestId) Set The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
 */
class DescribeBanStatusResponse extends AbstractModel
{
    /**
     * @var integer (Abandoned) Block switch status: 0 -- Off 1 -- Advanced blocking 2 -- Basic block (blocklist IPs in the intelligence database)
     */
    public $Status;

    /**
     * @var boolean Whether to display the pop-up prompt. False: no; true: yes.
     */
    public $ShowTips;

    /**
     * @var boolean Whether to enable intelligent over-allowing mode
     */
    public $OpenSmartMode;

    /**
     * @var boolean Whether intelligence IP blocking is enabled
     */
    public $BanBlackIp;

    /**
     * @var boolean Whether vulnerability IP blocking is enabled
     */
    public $BanVulIp;

    /**
     * @var boolean Whether to enable rule blocking
     */
    public $BanByRule;

    /**
     * @var string The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    public $RequestId;

    /**
     * @param integer $Status (Abandoned) Block switch status: 0 -- Off 1 -- Advanced blocking 2 -- Basic block (blocklist IPs in the intelligence database)
     * @param boolean $ShowTips Whether to display the pop-up prompt. False: no; true: yes.
     * @param boolean $OpenSmartMode Whether to enable intelligent over-allowing mode
     * @param boolean $BanBlackIp Whether intelligence IP blocking is enabled
     * @param boolean $BanVulIp Whether vulnerability IP blocking is enabled
     * @param boolean $BanByRule Whether to enable rule blocking
     * @param string $RequestId The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    function __construct()
    {

    }

    /**
     * For internal only. DO NOT USE IT.
     */
    public function deserialize($param)
    {
        if ($param === null) {
            return;
        }
        if (array_key_exists("Status",$param) and $param["Status"] !== null) {
            $this->Status = $param["Status"];
        }

        if (array_key_exists("ShowTips",$param) and $param["ShowTips"] !== null) {
            $this->ShowTips = $param["ShowTips"];
        }

        if (array_key_exists("OpenSmartMode",$param) and $param["OpenSmartMode"] !== null) {
            $this->OpenSmartMode = $param["OpenSmartMode"];
        }

        if (array_key_exists("BanBlackIp",$param) and $param["BanBlackIp"] !== null) {
            $this->BanBlackIp = $param["BanBlackIp"];
        }

        if (array_key_exists("BanVulIp",$param) and $param["BanVulIp"] !== null) {
            $this->BanVulIp = $param["BanVulIp"];
        }

        if (array_key_exists("BanByRule",$param) and $param["BanByRule"] !== null) {
            $this->BanByRule = $param["BanByRule"];
        }

        if (array_key_exists("RequestId",$param) and $param["RequestId"] !== null) {
            $this->RequestId = $param["RequestId"];
        }
    }
}
