<?php
/*
 * Copyright (c) 2017-2018 THL A29 Limited, a Tencent company. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
namespace TencentCloud\Cwp\V20180228\Models;
use TencentCloud\Common\AbstractModel;

/**
 * DescribeVulDefenceSetting response structure.
 *
 * @method integer getEnable() Obtain Defense switch: 0 - off; 1 - on
 * @method void setEnable(integer $Enable) Set Defense switch: 0 - off; 1 - on
 * @method integer getScope() Obtain Scope of impact: 1 - all ultimate edition hosts across the network; 0 - hosts in the QUUID list
 * @method void setScope(integer $Scope) Set Scope of impact: 1 - all ultimate edition hosts across the network; 0 - hosts in the QUUID list
 * @method array getQuuids() Obtain List of affected host QUUIDs
Note: This field may return null, indicating that no valid values can be obtained.
 * @method void setQuuids(array $Quuids) Set List of affected host QUUIDs
Note: This field may return null, indicating that no valid values can be obtained.
 * @method integer getFlagshipCount() Obtain Current number of ultimate edition hosts
 * @method void setFlagshipCount(integer $FlagshipCount) Set Current number of ultimate edition hosts
 * @method array getInstanceIds() Obtain List of affected host IDs
Note: This field may return null, indicating that no valid values can be obtained.
 * @method void setInstanceIds(array $InstanceIds) Set List of affected host IDs
Note: This field may return null, indicating that no valid values can be obtained.
 * @method integer getAutoInclude() Obtain Whether new ultimate edition hosts automatically join: 1 - yes; 0 - no
 * @method void setAutoInclude(integer $AutoInclude) Set Whether new ultimate edition hosts automatically join: 1 - yes; 0 - no
 * @method array getExcludeInstanceIds() Obtain List of excluded host IDs
Note: This field may return null, indicating that no valid values can be obtained.
 * @method void setExcludeInstanceIds(array $ExcludeInstanceIds) Set List of excluded host IDs
Note: This field may return null, indicating that no valid values can be obtained.
 * @method string getRequestId() Obtain The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
 * @method void setRequestId(string $RequestId) Set The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
 */
class DescribeVulDefenceSettingResponse extends AbstractModel
{
    /**
     * @var integer Defense switch: 0 - off; 1 - on
     */
    public $Enable;

    /**
     * @var integer Scope of impact: 1 - all ultimate edition hosts across the network; 0 - hosts in the QUUID list
     */
    public $Scope;

    /**
     * @var array List of affected host QUUIDs
Note: This field may return null, indicating that no valid values can be obtained.
     */
    public $Quuids;

    /**
     * @var integer Current number of ultimate edition hosts
     */
    public $FlagshipCount;

    /**
     * @var array List of affected host IDs
Note: This field may return null, indicating that no valid values can be obtained.
     */
    public $InstanceIds;

    /**
     * @var integer Whether new ultimate edition hosts automatically join: 1 - yes; 0 - no
     */
    public $AutoInclude;

    /**
     * @var array List of excluded host IDs
Note: This field may return null, indicating that no valid values can be obtained.
     */
    public $ExcludeInstanceIds;

    /**
     * @var string The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    public $RequestId;

    /**
     * @param integer $Enable Defense switch: 0 - off; 1 - on
     * @param integer $Scope Scope of impact: 1 - all ultimate edition hosts across the network; 0 - hosts in the QUUID list
     * @param array $Quuids List of affected host QUUIDs
Note: This field may return null, indicating that no valid values can be obtained.
     * @param integer $FlagshipCount Current number of ultimate edition hosts
     * @param array $InstanceIds List of affected host IDs
Note: This field may return null, indicating that no valid values can be obtained.
     * @param integer $AutoInclude Whether new ultimate edition hosts automatically join: 1 - yes; 0 - no
     * @param array $ExcludeInstanceIds List of excluded host IDs
Note: This field may return null, indicating that no valid values can be obtained.
     * @param string $RequestId The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    function __construct()
    {

    }

    /**
     * For internal only. DO NOT USE IT.
     */
    public function deserialize($param)
    {
        if ($param === null) {
            return;
        }
        if (array_key_exists("Enable",$param) and $param["Enable"] !== null) {
            $this->Enable = $param["Enable"];
        }

        if (array_key_exists("Scope",$param) and $param["Scope"] !== null) {
            $this->Scope = $param["Scope"];
        }

        if (array_key_exists("Quuids",$param) and $param["Quuids"] !== null) {
            $this->Quuids = $param["Quuids"];
        }

        if (array_key_exists("FlagshipCount",$param) and $param["FlagshipCount"] !== null) {
            $this->FlagshipCount = $param["FlagshipCount"];
        }

        if (array_key_exists("InstanceIds",$param) and $param["InstanceIds"] !== null) {
            $this->InstanceIds = $param["InstanceIds"];
        }

        if (array_key_exists("AutoInclude",$param) and $param["AutoInclude"] !== null) {
            $this->AutoInclude = $param["AutoInclude"];
        }

        if (array_key_exists("ExcludeInstanceIds",$param) and $param["ExcludeInstanceIds"] !== null) {
            $this->ExcludeInstanceIds = $param["ExcludeInstanceIds"];
        }

        if (array_key_exists("RequestId",$param) and $param["RequestId"] !== null) {
            $this->RequestId = $param["RequestId"];
        }
    }
}
