<?php
/*
 * Copyright (c) 2017-2018 THL A29 Limited, a Tencent company. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
namespace TencentCloud\Cwp\V20180228\Models;
use TencentCloud\Common\AbstractModel;

/**
 * DescribeBaselineStrategyDetail response structure.
 *
 * @method integer getPassRate() Obtain Policy scan pass rate
Note: This field may return null, indicating that no valid values can be obtained.
 * @method void setPassRate(integer $PassRate) Set Policy scan pass rate
Note: This field may return null, indicating that no valid values can be obtained.
 * @method string getStrategyName() Obtain Policy name
Note: This field may return null, indicating that no valid values can be obtained.
 * @method void setStrategyName(string $StrategyName) Set Policy name
Note: This field may return null, indicating that no valid values can be obtained.
 * @method string getScanCycle() Obtain policy scan cycle (days)
Note: This field may return null, indicating that no valid values can be obtained.
 * @method void setScanCycle(string $ScanCycle) Set policy scan cycle (days)
Note: This field may return null, indicating that no valid values can be obtained.
 * @method string getScanAt() Obtain Regular scan time. The scan task is triggered at this time.
Note: This field may return null, indicating that no valid values can be obtained.
 * @method void setScanAt(string $ScanAt) Set Regular scan time. The scan task is triggered at this time.
Note: This field may return null, indicating that no valid values can be obtained.
 * @method integer getIsGlobal() Obtain Whether all hosts are scanned. 1: yes; 0: no. If the value is 1, all Pro Edition hosts are scanned.Note: This field may return null, indicating that no valid values can be obtained.
 * @method void setIsGlobal(integer $IsGlobal) Set Whether all hosts are scanned. 1: yes; 0: no. If the value is 1, all Pro Edition hosts are scanned.Note: This field may return null, indicating that no valid values can be obtained.
 * @method string getMachineType() Obtain Machine type:
cvm: Tencent Cloud Virtual Machine
bm: BM
ecm: Edge Computing Machine
lh: Lighthouse
other: Hybrid Cloud Machine
Note: This field may return null, indicating that no valid values can be obtained.
 * @method void setMachineType(string $MachineType) Set Machine type:
cvm: Tencent Cloud Virtual Machine
bm: BM
ecm: Edge Computing Machine
lh: Lighthouse
other: Hybrid Cloud Machine
Note: This field may return null, indicating that no valid values can be obtained.
 * @method string getRegion() Obtain Host region
Note: This field may return null, indicating that no valid values can be obtained.
 * @method void setRegion(string $Region) Set Host region
Note: This field may return null, indicating that no valid values can be obtained.
 * @method array getQuuids() Obtain IDs of all user hosts involved in this policy
Note: This field may return null, indicating that no valid values can be obtained.
 * @method void setQuuids(array $Quuids) Set IDs of all user hosts involved in this policy
Note: This field may return null, indicating that no valid values can be obtained.
 * @method array getCategoryIds() Obtain IDs of all user baselines involved in this policy
Note: This field may return null, indicating that no valid values can be obtained.
 * @method void setCategoryIds(array $CategoryIds) Set IDs of all user baselines involved in this policy
Note: This field may return null, indicating that no valid values can be obtained.
 * @method integer getIfScanned() Obtain 1: scanned; 0: not scanned.Note: This field may return null, indicating that no valid values can be obtained.
 * @method void setIfScanned(integer $IfScanned) Set 1: scanned; 0: not scanned.Note: This field may return null, indicating that no valid values can be obtained.
 * @method string getRequestId() Obtain The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
 * @method void setRequestId(string $RequestId) Set The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
 */
class DescribeBaselineStrategyDetailResponse extends AbstractModel
{
    /**
     * @var integer Policy scan pass rate
Note: This field may return null, indicating that no valid values can be obtained.
     */
    public $PassRate;

    /**
     * @var string Policy name
Note: This field may return null, indicating that no valid values can be obtained.
     */
    public $StrategyName;

    /**
     * @var string policy scan cycle (days)
Note: This field may return null, indicating that no valid values can be obtained.
     */
    public $ScanCycle;

    /**
     * @var string Regular scan time. The scan task is triggered at this time.
Note: This field may return null, indicating that no valid values can be obtained.
     */
    public $ScanAt;

    /**
     * @var integer Whether all hosts are scanned. 1: yes; 0: no. If the value is 1, all Pro Edition hosts are scanned.Note: This field may return null, indicating that no valid values can be obtained.
     */
    public $IsGlobal;

    /**
     * @var string Machine type:
cvm: Tencent Cloud Virtual Machine
bm: BM
ecm: Edge Computing Machine
lh: Lighthouse
other: Hybrid Cloud Machine
Note: This field may return null, indicating that no valid values can be obtained.
     */
    public $MachineType;

    /**
     * @var string Host region
Note: This field may return null, indicating that no valid values can be obtained.
     */
    public $Region;

    /**
     * @var array IDs of all user hosts involved in this policy
Note: This field may return null, indicating that no valid values can be obtained.
     */
    public $Quuids;

    /**
     * @var array IDs of all user baselines involved in this policy
Note: This field may return null, indicating that no valid values can be obtained.
     */
    public $CategoryIds;

    /**
     * @var integer 1: scanned; 0: not scanned.Note: This field may return null, indicating that no valid values can be obtained.
     */
    public $IfScanned;

    /**
     * @var string The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    public $RequestId;

    /**
     * @param integer $PassRate Policy scan pass rate
Note: This field may return null, indicating that no valid values can be obtained.
     * @param string $StrategyName Policy name
Note: This field may return null, indicating that no valid values can be obtained.
     * @param string $ScanCycle policy scan cycle (days)
Note: This field may return null, indicating that no valid values can be obtained.
     * @param string $ScanAt Regular scan time. The scan task is triggered at this time.
Note: This field may return null, indicating that no valid values can be obtained.
     * @param integer $IsGlobal Whether all hosts are scanned. 1: yes; 0: no. If the value is 1, all Pro Edition hosts are scanned.Note: This field may return null, indicating that no valid values can be obtained.
     * @param string $MachineType Machine type:
cvm: Tencent Cloud Virtual Machine
bm: BM
ecm: Edge Computing Machine
lh: Lighthouse
other: Hybrid Cloud Machine
Note: This field may return null, indicating that no valid values can be obtained.
     * @param string $Region Host region
Note: This field may return null, indicating that no valid values can be obtained.
     * @param array $Quuids IDs of all user hosts involved in this policy
Note: This field may return null, indicating that no valid values can be obtained.
     * @param array $CategoryIds IDs of all user baselines involved in this policy
Note: This field may return null, indicating that no valid values can be obtained.
     * @param integer $IfScanned 1: scanned; 0: not scanned.Note: This field may return null, indicating that no valid values can be obtained.
     * @param string $RequestId The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    function __construct()
    {

    }

    /**
     * For internal only. DO NOT USE IT.
     */
    public function deserialize($param)
    {
        if ($param === null) {
            return;
        }
        if (array_key_exists("PassRate",$param) and $param["PassRate"] !== null) {
            $this->PassRate = $param["PassRate"];
        }

        if (array_key_exists("StrategyName",$param) and $param["StrategyName"] !== null) {
            $this->StrategyName = $param["StrategyName"];
        }

        if (array_key_exists("ScanCycle",$param) and $param["ScanCycle"] !== null) {
            $this->ScanCycle = $param["ScanCycle"];
        }

        if (array_key_exists("ScanAt",$param) and $param["ScanAt"] !== null) {
            $this->ScanAt = $param["ScanAt"];
        }

        if (array_key_exists("IsGlobal",$param) and $param["IsGlobal"] !== null) {
            $this->IsGlobal = $param["IsGlobal"];
        }

        if (array_key_exists("MachineType",$param) and $param["MachineType"] !== null) {
            $this->MachineType = $param["MachineType"];
        }

        if (array_key_exists("Region",$param) and $param["Region"] !== null) {
            $this->Region = $param["Region"];
        }

        if (array_key_exists("Quuids",$param) and $param["Quuids"] !== null) {
            $this->Quuids = $param["Quuids"];
        }

        if (array_key_exists("CategoryIds",$param) and $param["CategoryIds"] !== null) {
            $this->CategoryIds = $param["CategoryIds"];
        }

        if (array_key_exists("IfScanned",$param) and $param["IfScanned"] !== null) {
            $this->IfScanned = $param["IfScanned"];
        }

        if (array_key_exists("RequestId",$param) and $param["RequestId"] !== null) {
            $this->RequestId = $param["RequestId"];
        }
    }
}
