<?php
/*
 * Copyright (c) 2017-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
namespace TencentCloud\Cwp\V20180228\Models;
use TencentCloud\Common\AbstractModel;

/**
 * DescribeBaselineStrategyDetail response structure.
 *
 * @method integer getPassRate() Obtain Policy scan pass rate
 * @method void setPassRate(integer $PassRate) Set Policy scan pass rate
 * @method string getStrategyName() Obtain Policy name
 * @method void setStrategyName(string $StrategyName) Set Policy name
 * @method string getScanCycle() Obtain Policy scan cycle (days)
 * @method void setScanCycle(string $ScanCycle) Set Policy scan cycle (days)
 * @method string getScanAt() Obtain Regular scan time. The scan task is triggered at this time.
 * @method void setScanAt(string $ScanAt) Set Regular scan time. The scan task is triggered at this time.
 * @method integer getIsGlobal() Obtain Whether all servers are scanned: 1: yes; 0 :no. If the value is 1, all Professional Edition hosts are scanned.
 * @method void setIsGlobal(integer $IsGlobal) Set Whether all servers are scanned: 1: yes; 0 :no. If the value is 1, all Professional Edition hosts are scanned.
 * @method string getMachineType() Obtain Machine type:
cvm: Tencent Cloud Virtual Machine
bm: bare metal server
ecm: edge computing host
Lightweight Application Server
Hybrid cloud machine
 * @method void setMachineType(string $MachineType) Set Machine type:
cvm: Tencent Cloud Virtual Machine
bm: bare metal server
ecm: edge computing host
Lightweight Application Server
Hybrid cloud machine
 * @method string getRegion() Obtain Host region
 * @method void setRegion(string $Region) Set Host region
 * @method array getQuuids() Obtain IDs of all user hosts under this policy
 * @method void setQuuids(array $Quuids) Set IDs of all user hosts under this policy
 * @method array getCategoryIds() Obtain User baseline IDs under this policy
 * @method void setCategoryIds(array $CategoryIds) Set User baseline IDs under this policy
 * @method integer getIfScanned() Obtain 1 means scanned, 0 means not scanned
 * @method void setIfScanned(integer $IfScanned) Set 1 means scanned, 0 means not scanned
 * @method string getRequestId() Obtain The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
 * @method void setRequestId(string $RequestId) Set The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
 */
class DescribeBaselineStrategyDetailResponse extends AbstractModel
{
    /**
     * @var integer Policy scan pass rate
     */
    public $PassRate;

    /**
     * @var string Policy name
     */
    public $StrategyName;

    /**
     * @var string Policy scan cycle (days)
     */
    public $ScanCycle;

    /**
     * @var string Regular scan time. The scan task is triggered at this time.
     */
    public $ScanAt;

    /**
     * @var integer Whether all servers are scanned: 1: yes; 0 :no. If the value is 1, all Professional Edition hosts are scanned.
     */
    public $IsGlobal;

    /**
     * @var string Machine type:
cvm: Tencent Cloud Virtual Machine
bm: bare metal server
ecm: edge computing host
Lightweight Application Server
Hybrid cloud machine
     */
    public $MachineType;

    /**
     * @var string Host region
     */
    public $Region;

    /**
     * @var array IDs of all user hosts under this policy
     */
    public $Quuids;

    /**
     * @var array User baseline IDs under this policy
     */
    public $CategoryIds;

    /**
     * @var integer 1 means scanned, 0 means not scanned
     */
    public $IfScanned;

    /**
     * @var string The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    public $RequestId;

    /**
     * @param integer $PassRate Policy scan pass rate
     * @param string $StrategyName Policy name
     * @param string $ScanCycle Policy scan cycle (days)
     * @param string $ScanAt Regular scan time. The scan task is triggered at this time.
     * @param integer $IsGlobal Whether all servers are scanned: 1: yes; 0 :no. If the value is 1, all Professional Edition hosts are scanned.
     * @param string $MachineType Machine type:
cvm: Tencent Cloud Virtual Machine
bm: bare metal server
ecm: edge computing host
Lightweight Application Server
Hybrid cloud machine
     * @param string $Region Host region
     * @param array $Quuids IDs of all user hosts under this policy
     * @param array $CategoryIds User baseline IDs under this policy
     * @param integer $IfScanned 1 means scanned, 0 means not scanned
     * @param string $RequestId The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    function __construct()
    {

    }

    /**
     * For internal only. DO NOT USE IT.
     */
    public function deserialize($param)
    {
        if ($param === null) {
            return;
        }
        if (array_key_exists("PassRate",$param) and $param["PassRate"] !== null) {
            $this->PassRate = $param["PassRate"];
        }

        if (array_key_exists("StrategyName",$param) and $param["StrategyName"] !== null) {
            $this->StrategyName = $param["StrategyName"];
        }

        if (array_key_exists("ScanCycle",$param) and $param["ScanCycle"] !== null) {
            $this->ScanCycle = $param["ScanCycle"];
        }

        if (array_key_exists("ScanAt",$param) and $param["ScanAt"] !== null) {
            $this->ScanAt = $param["ScanAt"];
        }

        if (array_key_exists("IsGlobal",$param) and $param["IsGlobal"] !== null) {
            $this->IsGlobal = $param["IsGlobal"];
        }

        if (array_key_exists("MachineType",$param) and $param["MachineType"] !== null) {
            $this->MachineType = $param["MachineType"];
        }

        if (array_key_exists("Region",$param) and $param["Region"] !== null) {
            $this->Region = $param["Region"];
        }

        if (array_key_exists("Quuids",$param) and $param["Quuids"] !== null) {
            $this->Quuids = $param["Quuids"];
        }

        if (array_key_exists("CategoryIds",$param) and $param["CategoryIds"] !== null) {
            $this->CategoryIds = $param["CategoryIds"];
        }

        if (array_key_exists("IfScanned",$param) and $param["IfScanned"] !== null) {
            $this->IfScanned = $param["IfScanned"];
        }

        if (array_key_exists("RequestId",$param) and $param["RequestId"] !== null) {
            $this->RequestId = $param["RequestId"];
        }
    }
}
