<?php
/*
 * Copyright (c) 2017-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
namespace TencentCloud\Cwp\V20180228\Models;
use TencentCloud\Common\AbstractModel;

/**
 * DescribeReverseShellSystemPolicyConfig response structure.
 *
 * @method boolean getInnerNetAlarmShow() Obtain <p>Display intranet alerts</p>
 * @method void setInnerNetAlarmShow(boolean $InnerNetAlarmShow) Set <p>Display intranet alerts</p>
 * @method boolean getInnerIPShow() Obtain <p>Display intranet IP addresses</p>
 * @method void setInnerIPShow(boolean $InnerIPShow) Set <p>Display intranet IP addresses</p>
 * @method string getRequestId() Obtain The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
 * @method void setRequestId(string $RequestId) Set The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
 */
class DescribeReverseShellSystemPolicyConfigResponse extends AbstractModel
{
    /**
     * @var boolean <p>Display intranet alerts</p>
     */
    public $InnerNetAlarmShow;

    /**
     * @var boolean <p>Display intranet IP addresses</p>
     */
    public $InnerIPShow;

    /**
     * @var string The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    public $RequestId;

    /**
     * @param boolean $InnerNetAlarmShow <p>Display intranet alerts</p>
     * @param boolean $InnerIPShow <p>Display intranet IP addresses</p>
     * @param string $RequestId The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    function __construct()
    {

    }

    /**
     * For internal only. DO NOT USE IT.
     */
    public function deserialize($param)
    {
        if ($param === null) {
            return;
        }
        if (array_key_exists("InnerNetAlarmShow",$param) and $param["InnerNetAlarmShow"] !== null) {
            $this->InnerNetAlarmShow = $param["InnerNetAlarmShow"];
        }

        if (array_key_exists("InnerIPShow",$param) and $param["InnerIPShow"] !== null) {
            $this->InnerIPShow = $param["InnerIPShow"];
        }

        if (array_key_exists("RequestId",$param) and $param["RequestId"] !== null) {
            $this->RequestId = $param["RequestId"];
        }
    }
}
