<?php
/*
 * Copyright (c) 2017-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
namespace TencentCloud\Lkeap\V20240522\Models;
use TencentCloud\Common\AbstractModel;

/**
 * ChatCompletions response structure.
 *
 * @method integer getCreated() Obtain Unix timestamp, in seconds.
 * @method void setCreated(integer $Created) Set Unix timestamp, in seconds.
 * @method ChatUsage getUsage() Obtain Token statistical information.
Charges are based on the total Token quantity.
 * @method void setUsage(ChatUsage $Usage) Set Token statistical information.
Charges are based on the total Token quantity.
 * @method string getId() Obtain RequestId for this request.
 * @method void setId(string $Id) Set RequestId for this request.
 * @method array getChoices() Obtain Response content.
 * @method void setChoices(array $Choices) Set Response content.
 * @method string getModel() Obtain Model name.
 * @method void setModel(string $Model) Set Model name.
 * @method string getRequestId() Obtain The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem. As a streaming response API, when the request is successfully completed, the RequestId will be placed in the Header "X-TC-RequestId" of the HTTP response.
 * @method void setRequestId(string $RequestId) Set The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem. As a streaming response API, when the request is successfully completed, the RequestId will be placed in the Header "X-TC-RequestId" of the HTTP response.
 */
class ChatCompletionsResponse extends AbstractModel
{
    /**
     * @var integer Unix timestamp, in seconds.
     */
    public $Created;

    /**
     * @var ChatUsage Token statistical information.
Charges are based on the total Token quantity.
     */
    public $Usage;

    /**
     * @var string RequestId for this request.
     */
    public $Id;

    /**
     * @var array Response content.
     */
    public $Choices;

    /**
     * @var string Model name.
     */
    public $Model;

    /**
     * @var string The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem. As a streaming response API, when the request is successfully completed, the RequestId will be placed in the Header "X-TC-RequestId" of the HTTP response.
     */
    public $RequestId;

    /**
     * @param integer $Created Unix timestamp, in seconds.
     * @param ChatUsage $Usage Token statistical information.
Charges are based on the total Token quantity.
     * @param string $Id RequestId for this request.
     * @param array $Choices Response content.
     * @param string $Model Model name.
     * @param string $RequestId The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem. As a streaming response API, when the request is successfully completed, the RequestId will be placed in the Header "X-TC-RequestId" of the HTTP response.
     */
    function __construct()
    {

    }

    /**
     * For internal only. DO NOT USE IT.
     */
    public function deserialize($param)
    {
        if ($param === null) {
            return;
        }
        if (array_key_exists("Created",$param) and $param["Created"] !== null) {
            $this->Created = $param["Created"];
        }

        if (array_key_exists("Usage",$param) and $param["Usage"] !== null) {
            $this->Usage = new ChatUsage();
            $this->Usage->deserialize($param["Usage"]);
        }

        if (array_key_exists("Id",$param) and $param["Id"] !== null) {
            $this->Id = $param["Id"];
        }

        if (array_key_exists("Choices",$param) and $param["Choices"] !== null) {
            $this->Choices = [];
            foreach ($param["Choices"] as $key => $value){
                $obj = new Choice();
                $obj->deserialize($value);
                array_push($this->Choices, $obj);
            }
        }

        if (array_key_exists("Model",$param) and $param["Model"] !== null) {
            $this->Model = $param["Model"];
        }

        if (array_key_exists("RequestId",$param) and $param["RequestId"] !== null) {
            $this->RequestId = $param["RequestId"];
        }
    }
}
