<?php
/*
 * Copyright (c) 2017-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
namespace TencentCloud\Edgezone\V20260401\Models;
use TencentCloud\Common\AbstractModel;

/**
 * TerminateInstances response structure.
 *
 * @method array getInstanceIdSet() Obtain List of instance IDs successfully terminated.
 * @method void setInstanceIdSet(array $InstanceIdSet) Set List of instance IDs successfully terminated.
 * @method array getFailedInstanceSet() Obtain List of instances with termination failed (returned when partially successful).
Note: This field may return null, indicating that no valid values can be obtained.
 * @method void setFailedInstanceSet(array $FailedInstanceSet) Set List of instances with termination failed (returned when partially successful).
Note: This field may return null, indicating that no valid values can be obtained.
 * @method string getRequestId() Obtain The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
 * @method void setRequestId(string $RequestId) Set The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
 */
class TerminateInstancesResponse extends AbstractModel
{
    /**
     * @var array List of instance IDs successfully terminated.
     */
    public $InstanceIdSet;

    /**
     * @var array List of instances with termination failed (returned when partially successful).
Note: This field may return null, indicating that no valid values can be obtained.
     */
    public $FailedInstanceSet;

    /**
     * @var string The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    public $RequestId;

    /**
     * @param array $InstanceIdSet List of instance IDs successfully terminated.
     * @param array $FailedInstanceSet List of instances with termination failed (returned when partially successful).
Note: This field may return null, indicating that no valid values can be obtained.
     * @param string $RequestId The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    function __construct()
    {

    }

    /**
     * For internal only. DO NOT USE IT.
     */
    public function deserialize($param)
    {
        if ($param === null) {
            return;
        }
        if (array_key_exists("InstanceIdSet",$param) and $param["InstanceIdSet"] !== null) {
            $this->InstanceIdSet = $param["InstanceIdSet"];
        }

        if (array_key_exists("FailedInstanceSet",$param) and $param["FailedInstanceSet"] !== null) {
            $this->FailedInstanceSet = [];
            foreach ($param["FailedInstanceSet"] as $key => $value){
                $obj = new FailedInstance();
                $obj->deserialize($value);
                array_push($this->FailedInstanceSet, $obj);
            }
        }

        if (array_key_exists("RequestId",$param) and $param["RequestId"] !== null) {
            $this->RequestId = $param["RequestId"];
        }
    }
}
