<?php
/*
 * Copyright (c) 2017-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
namespace TencentCloud\Controlcenter\V20230110\Models;
use TencentCloud\Common\AbstractModel;

/**
 * GetAccountFactoryBaseline response structure.
 *
 * @method integer getOwnerUin() Obtain Specifies the uin of the main account to which the resource belongs.
 * @method void setOwnerUin(integer $OwnerUin) Set Specifies the uin of the main account to which the resource belongs.
 * @method string getName() Obtain Specifies the baseline item name, which must be unique and can only contain a combination of english letters, digits, chinese characters, and symbols @, &_[]-, with a length of 1-25 chinese or english characters.
 * @method void setName(string $Name) Set Specifies the baseline item name, which must be unique and can only contain a combination of english letters, digits, chinese characters, and symbols @, &_[]-, with a length of 1-25 chinese or english characters.
 * @method array getBaselineConfigItems() Obtain List of baseline item configurations.
 * @method void setBaselineConfigItems(array $BaselineConfigItems) Set List of baseline item configurations.
 * @method string getCreateTime() Obtain Creation time, represented in ISO8601 standard format as yyyy-MM-dd hh:MM:ss.
 * @method void setCreateTime(string $CreateTime) Set Creation time, represented in ISO8601 standard format as yyyy-MM-dd hh:MM:ss.
 * @method string getUpdateTime() Obtain Specifies the last update time in ISO8601 standard representation with format yyyy-MM-dd hh:MM:ss.
 * @method void setUpdateTime(string $UpdateTime) Set Specifies the last update time in ISO8601 standard representation with format yyyy-MM-dd hh:MM:ss.
 * @method string getRequestId() Obtain The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
 * @method void setRequestId(string $RequestId) Set The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
 */
class GetAccountFactoryBaselineResponse extends AbstractModel
{
    /**
     * @var integer Specifies the uin of the main account to which the resource belongs.
     */
    public $OwnerUin;

    /**
     * @var string Specifies the baseline item name, which must be unique and can only contain a combination of english letters, digits, chinese characters, and symbols @, &_[]-, with a length of 1-25 chinese or english characters.
     */
    public $Name;

    /**
     * @var array List of baseline item configurations.
     */
    public $BaselineConfigItems;

    /**
     * @var string Creation time, represented in ISO8601 standard format as yyyy-MM-dd hh:MM:ss.
     */
    public $CreateTime;

    /**
     * @var string Specifies the last update time in ISO8601 standard representation with format yyyy-MM-dd hh:MM:ss.
     */
    public $UpdateTime;

    /**
     * @var string The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    public $RequestId;

    /**
     * @param integer $OwnerUin Specifies the uin of the main account to which the resource belongs.
     * @param string $Name Specifies the baseline item name, which must be unique and can only contain a combination of english letters, digits, chinese characters, and symbols @, &_[]-, with a length of 1-25 chinese or english characters.
     * @param array $BaselineConfigItems List of baseline item configurations.
     * @param string $CreateTime Creation time, represented in ISO8601 standard format as yyyy-MM-dd hh:MM:ss.
     * @param string $UpdateTime Specifies the last update time in ISO8601 standard representation with format yyyy-MM-dd hh:MM:ss.
     * @param string $RequestId The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    function __construct()
    {

    }

    /**
     * For internal only. DO NOT USE IT.
     */
    public function deserialize($param)
    {
        if ($param === null) {
            return;
        }
        if (array_key_exists("OwnerUin",$param) and $param["OwnerUin"] !== null) {
            $this->OwnerUin = $param["OwnerUin"];
        }

        if (array_key_exists("Name",$param) and $param["Name"] !== null) {
            $this->Name = $param["Name"];
        }

        if (array_key_exists("BaselineConfigItems",$param) and $param["BaselineConfigItems"] !== null) {
            $this->BaselineConfigItems = [];
            foreach ($param["BaselineConfigItems"] as $key => $value){
                $obj = new BaselineInfoItem();
                $obj->deserialize($value);
                array_push($this->BaselineConfigItems, $obj);
            }
        }

        if (array_key_exists("CreateTime",$param) and $param["CreateTime"] !== null) {
            $this->CreateTime = $param["CreateTime"];
        }

        if (array_key_exists("UpdateTime",$param) and $param["UpdateTime"] !== null) {
            $this->UpdateTime = $param["UpdateTime"];
        }

        if (array_key_exists("RequestId",$param) and $param["RequestId"] !== null) {
            $this->RequestId = $param["RequestId"];
        }
    }
}
