<?php
/*
 * Copyright (c) 2017-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
namespace TencentCloud\Cdz\V20221123\Models;
use TencentCloud\Common\AbstractModel;

/**
 * DescribeCloudDedicatedZoneResourceSummary response structure.
 *
 * @method array getResourceSummarySet() Obtain Resource utilization.
 * @method void setResourceSummarySet(array $ResourceSummarySet) Set Resource utilization.
 * @method ExtraInfo getExtraInfo() Obtain Extended information of resource utilization.
 * @method void setExtraInfo(ExtraInfo $ExtraInfo) Set Extended information of resource utilization.
 * @method string getRequestId() Obtain The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
 * @method void setRequestId(string $RequestId) Set The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
 */
class DescribeCloudDedicatedZoneResourceSummaryResponse extends AbstractModel
{
    /**
     * @var array Resource utilization.
     */
    public $ResourceSummarySet;

    /**
     * @var ExtraInfo Extended information of resource utilization.
     */
    public $ExtraInfo;

    /**
     * @var string The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    public $RequestId;

    /**
     * @param array $ResourceSummarySet Resource utilization.
     * @param ExtraInfo $ExtraInfo Extended information of resource utilization.
     * @param string $RequestId The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    function __construct()
    {

    }

    /**
     * For internal only. DO NOT USE IT.
     */
    public function deserialize($param)
    {
        if ($param === null) {
            return;
        }
        if (array_key_exists("ResourceSummarySet",$param) and $param["ResourceSummarySet"] !== null) {
            $this->ResourceSummarySet = [];
            foreach ($param["ResourceSummarySet"] as $key => $value){
                $obj = new CloudDedicatedZoneResourceSummaryInfo();
                $obj->deserialize($value);
                array_push($this->ResourceSummarySet, $obj);
            }
        }

        if (array_key_exists("ExtraInfo",$param) and $param["ExtraInfo"] !== null) {
            $this->ExtraInfo = new ExtraInfo();
            $this->ExtraInfo->deserialize($param["ExtraInfo"]);
        }

        if (array_key_exists("RequestId",$param) and $param["RequestId"] !== null) {
            $this->RequestId = $param["RequestId"];
        }
    }
}
