<?php
/*
 * Copyright (c) 2017-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
namespace TencentCloud\Monitor\V20180724\Models;
use TencentCloud\Common\AbstractModel;

/**
 * DeleteOnCallForms response structure.
 *
 * @method array getFailedOnCallFormIDs() Obtain On-call schedule IDs failed to be deleted.
 * @method void setFailedOnCallFormIDs(array $FailedOnCallFormIDs) Set On-call schedule IDs failed to be deleted.
 * @method array getSuccessOnCallFormIDs() Obtain On-call schedule IDs deleted successfully.
 * @method void setSuccessOnCallFormIDs(array $SuccessOnCallFormIDs) Set On-call schedule IDs deleted successfully.
 * @method string getRequestId() Obtain The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
 * @method void setRequestId(string $RequestId) Set The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
 */
class DeleteOnCallFormsResponse extends AbstractModel
{
    /**
     * @var array On-call schedule IDs failed to be deleted.
     */
    public $FailedOnCallFormIDs;

    /**
     * @var array On-call schedule IDs deleted successfully.
     */
    public $SuccessOnCallFormIDs;

    /**
     * @var string The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    public $RequestId;

    /**
     * @param array $FailedOnCallFormIDs On-call schedule IDs failed to be deleted.
     * @param array $SuccessOnCallFormIDs On-call schedule IDs deleted successfully.
     * @param string $RequestId The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    function __construct()
    {

    }

    /**
     * For internal only. DO NOT USE IT.
     */
    public function deserialize($param)
    {
        if ($param === null) {
            return;
        }
        if (array_key_exists("FailedOnCallFormIDs",$param) and $param["FailedOnCallFormIDs"] !== null) {
            $this->FailedOnCallFormIDs = $param["FailedOnCallFormIDs"];
        }

        if (array_key_exists("SuccessOnCallFormIDs",$param) and $param["SuccessOnCallFormIDs"] !== null) {
            $this->SuccessOnCallFormIDs = $param["SuccessOnCallFormIDs"];
        }

        if (array_key_exists("RequestId",$param) and $param["RequestId"] !== null) {
            $this->RequestId = $param["RequestId"];
        }
    }
}
