<?php
/*
 * Copyright (c) 2017-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
namespace TencentCloud\Ccc\V20200210\Models;
use TencentCloud\Common\AbstractModel;

/**
 * DescribeAIAgentInfoList response structure.
 *
 * @method array getAIAgentInfoList() Obtain Intelligent agent information list.
 * @method void setAIAgentInfoList(array $AIAgentInfoList) Set Intelligent agent information list.
 * @method integer getTotalCount() Obtain Total number of intelligent agents.
 * @method void setTotalCount(integer $TotalCount) Set Total number of intelligent agents.
 * @method string getRequestId() Obtain The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
 * @method void setRequestId(string $RequestId) Set The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
 */
class DescribeAIAgentInfoListResponse extends AbstractModel
{
    /**
     * @var array Intelligent agent information list.
     */
    public $AIAgentInfoList;

    /**
     * @var integer Total number of intelligent agents.
     */
    public $TotalCount;

    /**
     * @var string The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    public $RequestId;

    /**
     * @param array $AIAgentInfoList Intelligent agent information list.
     * @param integer $TotalCount Total number of intelligent agents.
     * @param string $RequestId The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    function __construct()
    {

    }

    /**
     * For internal only. DO NOT USE IT.
     */
    public function deserialize($param)
    {
        if ($param === null) {
            return;
        }
        if (array_key_exists("AIAgentInfoList",$param) and $param["AIAgentInfoList"] !== null) {
            $this->AIAgentInfoList = [];
            foreach ($param["AIAgentInfoList"] as $key => $value){
                $obj = new AIAgentInfo();
                $obj->deserialize($value);
                array_push($this->AIAgentInfoList, $obj);
            }
        }

        if (array_key_exists("TotalCount",$param) and $param["TotalCount"] !== null) {
            $this->TotalCount = $param["TotalCount"];
        }

        if (array_key_exists("RequestId",$param) and $param["RequestId"] !== null) {
            $this->RequestId = $param["RequestId"];
        }
    }
}
