<?php
/*
 * Copyright (c) 2017-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
namespace TencentCloud\Tokenhub\V20260322\Models;
use TencentCloud\Common\AbstractModel;

/**
 * DescribeGlossaryEntries response structure.
 *
 * @method array getEntries() Obtain Terminology entry list.
 * @method void setEntries(array $Entries) Set Terminology entry list.
 * @method integer getTotal() Obtain Total number of eligible terminology entries.
 * @method void setTotal(integer $Total) Set Total number of eligible terminology entries.
 * @method integer getPage() Obtain Current page.
 * @method void setPage(integer $Page) Set Current page.
 * @method integer getPageSize() Obtain Size per page
 * @method void setPageSize(integer $PageSize) Set Size per page
 * @method string getRequestId() Obtain The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
 * @method void setRequestId(string $RequestId) Set The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
 */
class DescribeGlossaryEntriesResponse extends AbstractModel
{
    /**
     * @var array Terminology entry list.
     */
    public $Entries;

    /**
     * @var integer Total number of eligible terminology entries.
     */
    public $Total;

    /**
     * @var integer Current page.
     */
    public $Page;

    /**
     * @var integer Size per page
     */
    public $PageSize;

    /**
     * @var string The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    public $RequestId;

    /**
     * @param array $Entries Terminology entry list.
     * @param integer $Total Total number of eligible terminology entries.
     * @param integer $Page Current page.
     * @param integer $PageSize Size per page
     * @param string $RequestId The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    function __construct()
    {

    }

    /**
     * For internal only. DO NOT USE IT.
     */
    public function deserialize($param)
    {
        if ($param === null) {
            return;
        }
        if (array_key_exists("Entries",$param) and $param["Entries"] !== null) {
            $this->Entries = [];
            foreach ($param["Entries"] as $key => $value){
                $obj = new GlossaryEntryItem();
                $obj->deserialize($value);
                array_push($this->Entries, $obj);
            }
        }

        if (array_key_exists("Total",$param) and $param["Total"] !== null) {
            $this->Total = $param["Total"];
        }

        if (array_key_exists("Page",$param) and $param["Page"] !== null) {
            $this->Page = $param["Page"];
        }

        if (array_key_exists("PageSize",$param) and $param["PageSize"] !== null) {
            $this->PageSize = $param["PageSize"];
        }

        if (array_key_exists("RequestId",$param) and $param["RequestId"] !== null) {
            $this->RequestId = $param["RequestId"];
        }
    }
}
