<?php
/*
 * Copyright (c) 2017-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
namespace TencentCloud\Tokenhub\V20260322\Models;
use TencentCloud\Common\AbstractModel;

/**
 * DescribeApiKey response structure.
 *
 * @method string getApiKeyId() Obtain API Key ID.
 * @method void setApiKeyId(string $ApiKeyId) Set API Key ID.
 * @method string getName() Obtain Name
 * @method void setName(string $Name) Set Name
 * @method string getApiKey() Obtain API Key value (plaintext).
 * @method void setApiKey(string $ApiKey) Set API Key value (plaintext).
 * @method string getRemark() Obtain Remarks.
 * @method void setRemark(string $Remark) Set Remarks.
 * @method string getPlatform() Obtain Platform type. Enumerate: maas.
 * @method void setPlatform(string $Platform) Set Platform type. Enumerate: maas.
 * @method string getUin() Obtain Root account.
 * @method void setUin(string $Uin) Set Root account.
 * @method string getSubUin() Obtain Sub-account.
 * @method void setSubUin(string $SubUin) Set Sub-account.
 * @method string getStatus() Obtain Status. Valid values: enable, disable.
 * @method void setStatus(string $Status) Set Status. Valid values: enable, disable.
 * @method string getBindType() Obtain Binding type. Value: all (all models and access points), model_all_endpoint_custom (all models + custom access point), model_custom_endpoint_all (custom model + all access points), model_custom_endpoint_custom (custom model + custom access point).
 * @method void setBindType(string $BindType) Set Binding type. Value: all (all models and access points), model_all_endpoint_custom (all models + custom access point), model_custom_endpoint_all (custom model + all access points), model_custom_endpoint_custom (custom model + custom access point).
 * @method string getCreateTime() Obtain Creation time. Format: YYYY-MM-DD HH:mm:ss.
 * @method void setCreateTime(string $CreateTime) Set Creation time. Format: YYYY-MM-DD HH:mm:ss.
 * @method string getUpdateTime() Obtain Last update time. Format: YYYY-MM-DD HH:mm:ss.
 * @method void setUpdateTime(string $UpdateTime) Set Last update time. Format: YYYY-MM-DD HH:mm:ss.
 * @method string getAppId() Obtain App ID.
 * @method void setAppId(string $AppId) Set App ID.
 * @method boolean getEditable() Obtain Whether it is editable. true means editable, false means non-editable.
 * @method void setEditable(boolean $Editable) Set Whether it is editable. true means editable, false means non-editable.
 * @method array getBindingItems() Obtain List of bound resources, case-sensitive for endpoint and model kind.
 * @method void setBindingItems(array $BindingItems) Set List of bound resources, case-sensitive for endpoint and model kind.
 * @method array getIpWhitelist() Obtain IP allowlist. Supports IPv4 and CIDR format. Empty array indicates no restriction.
 * @method void setIpWhitelist(array $IpWhitelist) Set IP allowlist. Supports IPv4 and CIDR format. Empty array indicates no restriction.
 * @method string getCreator() Obtain This field is empty when Platform is maas.
 * @method void setCreator(string $Creator) Set This field is empty when Platform is maas.
 * @method array getQuotaSet() Obtain Multi-dimensional information of Token quota. This field is not returned when unconfigured.
 * @method void setQuotaSet(array $QuotaSet) Set Multi-dimensional information of Token quota. This field is not returned when unconfigured.
 * @method string getQuotaStatus() Obtain Token quota status. An empty string means no configuration. active means configured with current availability. inactive means configured but quota exhausted.
 * @method void setQuotaStatus(string $QuotaStatus) Set Token quota status. An empty string means no configuration. active means configured with current availability. inactive means configured but quota exhausted.
 * @method string getRequestId() Obtain The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
 * @method void setRequestId(string $RequestId) Set The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
 */
class DescribeApiKeyResponse extends AbstractModel
{
    /**
     * @var string API Key ID.
     */
    public $ApiKeyId;

    /**
     * @var string Name
     */
    public $Name;

    /**
     * @var string API Key value (plaintext).
     */
    public $ApiKey;

    /**
     * @var string Remarks.
     */
    public $Remark;

    /**
     * @var string Platform type. Enumerate: maas.
     */
    public $Platform;

    /**
     * @var string Root account.
     */
    public $Uin;

    /**
     * @var string Sub-account.
     */
    public $SubUin;

    /**
     * @var string Status. Valid values: enable, disable.
     */
    public $Status;

    /**
     * @var string Binding type. Value: all (all models and access points), model_all_endpoint_custom (all models + custom access point), model_custom_endpoint_all (custom model + all access points), model_custom_endpoint_custom (custom model + custom access point).
     */
    public $BindType;

    /**
     * @var string Creation time. Format: YYYY-MM-DD HH:mm:ss.
     */
    public $CreateTime;

    /**
     * @var string Last update time. Format: YYYY-MM-DD HH:mm:ss.
     */
    public $UpdateTime;

    /**
     * @var string App ID.
     */
    public $AppId;

    /**
     * @var boolean Whether it is editable. true means editable, false means non-editable.
     */
    public $Editable;

    /**
     * @var array List of bound resources, case-sensitive for endpoint and model kind.
     */
    public $BindingItems;

    /**
     * @var array IP allowlist. Supports IPv4 and CIDR format. Empty array indicates no restriction.
     */
    public $IpWhitelist;

    /**
     * @var string This field is empty when Platform is maas.
     */
    public $Creator;

    /**
     * @var array Multi-dimensional information of Token quota. This field is not returned when unconfigured.
     */
    public $QuotaSet;

    /**
     * @var string Token quota status. An empty string means no configuration. active means configured with current availability. inactive means configured but quota exhausted.
     */
    public $QuotaStatus;

    /**
     * @var string The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    public $RequestId;

    /**
     * @param string $ApiKeyId API Key ID.
     * @param string $Name Name
     * @param string $ApiKey API Key value (plaintext).
     * @param string $Remark Remarks.
     * @param string $Platform Platform type. Enumerate: maas.
     * @param string $Uin Root account.
     * @param string $SubUin Sub-account.
     * @param string $Status Status. Valid values: enable, disable.
     * @param string $BindType Binding type. Value: all (all models and access points), model_all_endpoint_custom (all models + custom access point), model_custom_endpoint_all (custom model + all access points), model_custom_endpoint_custom (custom model + custom access point).
     * @param string $CreateTime Creation time. Format: YYYY-MM-DD HH:mm:ss.
     * @param string $UpdateTime Last update time. Format: YYYY-MM-DD HH:mm:ss.
     * @param string $AppId App ID.
     * @param boolean $Editable Whether it is editable. true means editable, false means non-editable.
     * @param array $BindingItems List of bound resources, case-sensitive for endpoint and model kind.
     * @param array $IpWhitelist IP allowlist. Supports IPv4 and CIDR format. Empty array indicates no restriction.
     * @param string $Creator This field is empty when Platform is maas.
     * @param array $QuotaSet Multi-dimensional information of Token quota. This field is not returned when unconfigured.
     * @param string $QuotaStatus Token quota status. An empty string means no configuration. active means configured with current availability. inactive means configured but quota exhausted.
     * @param string $RequestId The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    function __construct()
    {

    }

    /**
     * For internal only. DO NOT USE IT.
     */
    public function deserialize($param)
    {
        if ($param === null) {
            return;
        }
        if (array_key_exists("ApiKeyId",$param) and $param["ApiKeyId"] !== null) {
            $this->ApiKeyId = $param["ApiKeyId"];
        }

        if (array_key_exists("Name",$param) and $param["Name"] !== null) {
            $this->Name = $param["Name"];
        }

        if (array_key_exists("ApiKey",$param) and $param["ApiKey"] !== null) {
            $this->ApiKey = $param["ApiKey"];
        }

        if (array_key_exists("Remark",$param) and $param["Remark"] !== null) {
            $this->Remark = $param["Remark"];
        }

        if (array_key_exists("Platform",$param) and $param["Platform"] !== null) {
            $this->Platform = $param["Platform"];
        }

        if (array_key_exists("Uin",$param) and $param["Uin"] !== null) {
            $this->Uin = $param["Uin"];
        }

        if (array_key_exists("SubUin",$param) and $param["SubUin"] !== null) {
            $this->SubUin = $param["SubUin"];
        }

        if (array_key_exists("Status",$param) and $param["Status"] !== null) {
            $this->Status = $param["Status"];
        }

        if (array_key_exists("BindType",$param) and $param["BindType"] !== null) {
            $this->BindType = $param["BindType"];
        }

        if (array_key_exists("CreateTime",$param) and $param["CreateTime"] !== null) {
            $this->CreateTime = $param["CreateTime"];
        }

        if (array_key_exists("UpdateTime",$param) and $param["UpdateTime"] !== null) {
            $this->UpdateTime = $param["UpdateTime"];
        }

        if (array_key_exists("AppId",$param) and $param["AppId"] !== null) {
            $this->AppId = $param["AppId"];
        }

        if (array_key_exists("Editable",$param) and $param["Editable"] !== null) {
            $this->Editable = $param["Editable"];
        }

        if (array_key_exists("BindingItems",$param) and $param["BindingItems"] !== null) {
            $this->BindingItems = [];
            foreach ($param["BindingItems"] as $key => $value){
                $obj = new BindingItem();
                $obj->deserialize($value);
                array_push($this->BindingItems, $obj);
            }
        }

        if (array_key_exists("IpWhitelist",$param) and $param["IpWhitelist"] !== null) {
            $this->IpWhitelist = $param["IpWhitelist"];
        }

        if (array_key_exists("Creator",$param) and $param["Creator"] !== null) {
            $this->Creator = $param["Creator"];
        }

        if (array_key_exists("QuotaSet",$param) and $param["QuotaSet"] !== null) {
            $this->QuotaSet = [];
            foreach ($param["QuotaSet"] as $key => $value){
                $obj = new QuotaInfo();
                $obj->deserialize($value);
                array_push($this->QuotaSet, $obj);
            }
        }

        if (array_key_exists("QuotaStatus",$param) and $param["QuotaStatus"] !== null) {
            $this->QuotaStatus = $param["QuotaStatus"];
        }

        if (array_key_exists("RequestId",$param) and $param["RequestId"] !== null) {
            $this->RequestId = $param["RequestId"];
        }
    }
}
