<?php
/*
 * Copyright (c) 2017-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
namespace TencentCloud\Tokenhub\V20260322\Models;
use TencentCloud\Common\AbstractModel;

/**
 * DescribeUsageRankList response structure.
 *
 * @method string getDimension() Obtain <p>Statistical dimension of the backfill request.</p>
 * @method void setDimension(string $Dimension) Set <p>Statistical dimension of the backfill request.</p>
 * @method string getMetricType() Obtain <p>Metrics family of the backfill request: tokens / search.</p>
 * @method void setMetricType(string $MetricType) Set <p>Metrics family of the backfill request: tokens / search.</p>
 * @method array getMetricKeys() Obtain <p>List of metric keys actually included in Stats / Series / PageStats / TotalStats in this response, case-sensitive by MetricType: tokens=[Total,Input,Output,Cache], search=[SearchRequestCount,SearchCount]</p>
 * @method void setMetricKeys(array $MetricKeys) Set <p>List of metric keys actually included in Stats / Series / PageStats / TotalStats in this response, case-sensitive by MetricType: tokens=[Total,Input,Output,Cache], search=[SearchRequestCount,SearchCount]</p>
 * @method string getViewName() Obtain <p>View (data source)</p>
 * @method void setViewName(string $ViewName) Set <p>View (data source)</p>
 * @method integer getPeriod() Obtain <p>Statistical granularity (in seconds) of the backfill request. It is 0 when ShowAll=true.</p>
 * @method void setPeriod(integer $Period) Set <p>Statistical granularity (in seconds) of the backfill request. It is 0 when ShowAll=true.</p>
 * @method string getStartTime() Obtain <p>Backfill the start time of the request.</p>
 * @method void setStartTime(string $StartTime) Set <p>Backfill the start time of the request.</p>
 * @method string getEndTime() Obtain <p>End time of the backfill request.</p>
 * @method void setEndTime(string $EndTime) Set <p>End time of the backfill request.</p>
 * @method integer getTotal() Obtain <p>Total number of objects.</p>
 * @method void setTotal(integer $Total) Set <p>Total number of objects.</p>
 * @method integer getOffset() Obtain <p>Backfill the pagination starting point of the request. It is 0 when ShowAll=true.</p>
 * @method void setOffset(integer $Offset) Set <p>Backfill the pagination starting point of the request. It is 0 when ShowAll=true.</p>
 * @method integer getLimit() Obtain <p>Page size. It is always 10. When ShowAll=true, it is Total.</p>
 * @method void setLimit(integer $Limit) Set <p>Page size. It is always 10. When ShowAll=true, it is Total.</p>
 * @method array getTimestamps() Obtain <p>Timestamp sequence corresponding to the Series array (Unix seconds). Empty array when ShowAll=true.</p>
 * @method void setTimestamps(array $Timestamps) Set <p>Timestamp sequence corresponding to the Series array (Unix seconds). Empty array when ShowAll=true.</p>
 * @method array getTopList() Obtain <p>Object ranking list, sorted by <code>MetricKeys[0]</code> in descending order. When ShowAll=false, it is the 10 objects on the current page (including Series); when ShowAll=true, it is all objects (excluding Series, used for CSV export).</p>
 * @method void setTopList(array $TopList) Set <p>Object ranking list, sorted by <code>MetricKeys[0]</code> in descending order. When ShowAll=false, it is the 10 objects on the current page (including Series); when ShowAll=true, it is all objects (excluding Series, used for CSV export).</p>
 * @method UsageStats getPageStats() Obtain <p>Pagination statistics result</p>
 * @method void setPageStats(UsageStats $PageStats) Set <p>Pagination statistics result</p>
 * @method UsageStats getTotalStats() Obtain <p>Total statistics result</p>
 * @method void setTotalStats(UsageStats $TotalStats) Set <p>Total statistics result</p>
 * @method string getRequestId() Obtain The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
 * @method void setRequestId(string $RequestId) Set The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
 */
class DescribeUsageRankListResponse extends AbstractModel
{
    /**
     * @var string <p>Statistical dimension of the backfill request.</p>
     */
    public $Dimension;

    /**
     * @var string <p>Metrics family of the backfill request: tokens / search.</p>
     */
    public $MetricType;

    /**
     * @var array <p>List of metric keys actually included in Stats / Series / PageStats / TotalStats in this response, case-sensitive by MetricType: tokens=[Total,Input,Output,Cache], search=[SearchRequestCount,SearchCount]</p>
     */
    public $MetricKeys;

    /**
     * @var string <p>View (data source)</p>
     */
    public $ViewName;

    /**
     * @var integer <p>Statistical granularity (in seconds) of the backfill request. It is 0 when ShowAll=true.</p>
     */
    public $Period;

    /**
     * @var string <p>Backfill the start time of the request.</p>
     */
    public $StartTime;

    /**
     * @var string <p>End time of the backfill request.</p>
     */
    public $EndTime;

    /**
     * @var integer <p>Total number of objects.</p>
     */
    public $Total;

    /**
     * @var integer <p>Backfill the pagination starting point of the request. It is 0 when ShowAll=true.</p>
     */
    public $Offset;

    /**
     * @var integer <p>Page size. It is always 10. When ShowAll=true, it is Total.</p>
     */
    public $Limit;

    /**
     * @var array <p>Timestamp sequence corresponding to the Series array (Unix seconds). Empty array when ShowAll=true.</p>
     */
    public $Timestamps;

    /**
     * @var array <p>Object ranking list, sorted by <code>MetricKeys[0]</code> in descending order. When ShowAll=false, it is the 10 objects on the current page (including Series); when ShowAll=true, it is all objects (excluding Series, used for CSV export).</p>
     */
    public $TopList;

    /**
     * @var UsageStats <p>Pagination statistics result</p>
     */
    public $PageStats;

    /**
     * @var UsageStats <p>Total statistics result</p>
     */
    public $TotalStats;

    /**
     * @var string The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    public $RequestId;

    /**
     * @param string $Dimension <p>Statistical dimension of the backfill request.</p>
     * @param string $MetricType <p>Metrics family of the backfill request: tokens / search.</p>
     * @param array $MetricKeys <p>List of metric keys actually included in Stats / Series / PageStats / TotalStats in this response, case-sensitive by MetricType: tokens=[Total,Input,Output,Cache], search=[SearchRequestCount,SearchCount]</p>
     * @param string $ViewName <p>View (data source)</p>
     * @param integer $Period <p>Statistical granularity (in seconds) of the backfill request. It is 0 when ShowAll=true.</p>
     * @param string $StartTime <p>Backfill the start time of the request.</p>
     * @param string $EndTime <p>End time of the backfill request.</p>
     * @param integer $Total <p>Total number of objects.</p>
     * @param integer $Offset <p>Backfill the pagination starting point of the request. It is 0 when ShowAll=true.</p>
     * @param integer $Limit <p>Page size. It is always 10. When ShowAll=true, it is Total.</p>
     * @param array $Timestamps <p>Timestamp sequence corresponding to the Series array (Unix seconds). Empty array when ShowAll=true.</p>
     * @param array $TopList <p>Object ranking list, sorted by <code>MetricKeys[0]</code> in descending order. When ShowAll=false, it is the 10 objects on the current page (including Series); when ShowAll=true, it is all objects (excluding Series, used for CSV export).</p>
     * @param UsageStats $PageStats <p>Pagination statistics result</p>
     * @param UsageStats $TotalStats <p>Total statistics result</p>
     * @param string $RequestId The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    function __construct()
    {

    }

    /**
     * For internal only. DO NOT USE IT.
     */
    public function deserialize($param)
    {
        if ($param === null) {
            return;
        }
        if (array_key_exists("Dimension",$param) and $param["Dimension"] !== null) {
            $this->Dimension = $param["Dimension"];
        }

        if (array_key_exists("MetricType",$param) and $param["MetricType"] !== null) {
            $this->MetricType = $param["MetricType"];
        }

        if (array_key_exists("MetricKeys",$param) and $param["MetricKeys"] !== null) {
            $this->MetricKeys = $param["MetricKeys"];
        }

        if (array_key_exists("ViewName",$param) and $param["ViewName"] !== null) {
            $this->ViewName = $param["ViewName"];
        }

        if (array_key_exists("Period",$param) and $param["Period"] !== null) {
            $this->Period = $param["Period"];
        }

        if (array_key_exists("StartTime",$param) and $param["StartTime"] !== null) {
            $this->StartTime = $param["StartTime"];
        }

        if (array_key_exists("EndTime",$param) and $param["EndTime"] !== null) {
            $this->EndTime = $param["EndTime"];
        }

        if (array_key_exists("Total",$param) and $param["Total"] !== null) {
            $this->Total = $param["Total"];
        }

        if (array_key_exists("Offset",$param) and $param["Offset"] !== null) {
            $this->Offset = $param["Offset"];
        }

        if (array_key_exists("Limit",$param) and $param["Limit"] !== null) {
            $this->Limit = $param["Limit"];
        }

        if (array_key_exists("Timestamps",$param) and $param["Timestamps"] !== null) {
            $this->Timestamps = $param["Timestamps"];
        }

        if (array_key_exists("TopList",$param) and $param["TopList"] !== null) {
            $this->TopList = [];
            foreach ($param["TopList"] as $key => $value){
                $obj = new UsageRankItem();
                $obj->deserialize($value);
                array_push($this->TopList, $obj);
            }
        }

        if (array_key_exists("PageStats",$param) and $param["PageStats"] !== null) {
            $this->PageStats = new UsageStats();
            $this->PageStats->deserialize($param["PageStats"]);
        }

        if (array_key_exists("TotalStats",$param) and $param["TotalStats"] !== null) {
            $this->TotalStats = new UsageStats();
            $this->TotalStats->deserialize($param["TotalStats"]);
        }

        if (array_key_exists("RequestId",$param) and $param["RequestId"] !== null) {
            $this->RequestId = $param["RequestId"];
        }
    }
}
