<?php
/*
 * Copyright (c) 2017-2018 THL A29 Limited, a Tencent company. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
namespace TencentCloud\Cdwdoris\V20211228\Models;
use TencentCloud\Common\AbstractModel;

/**
 * DescribeInstanceNodesInfo response structure.
 *
 * @method array getBeNodes() Obtain Be node
Note: This field may return null, indicating that no valid values can be obtained.
 * @method void setBeNodes(array $BeNodes) Set Be node
Note: This field may return null, indicating that no valid values can be obtained.
 * @method array getFeNodes() Obtain Fe node
Note: This field may return null, indicating that no valid values can be obtained.
 * @method void setFeNodes(array $FeNodes) Set Fe node
Note: This field may return null, indicating that no valid values can be obtained.
 * @method string getFeMaster() Obtain Fe master node
 * @method void setFeMaster(string $FeMaster) Set Fe master node
 * @method array getBeNodeInfos() Obtain Be node information
Note: This field may return null, indicating that no valid values can be obtained.
 * @method void setBeNodeInfos(array $BeNodeInfos) Set Be node information
Note: This field may return null, indicating that no valid values can be obtained.
 * @method array getFeNodeInfos() Obtain Fe node information
Note: This field may return null, indicating that no valid values can be obtained.
 * @method void setFeNodeInfos(array $FeNodeInfos) Set Fe node information
Note: This field may return null, indicating that no valid values can be obtained.
 * @method string getRequestId() Obtain The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
 * @method void setRequestId(string $RequestId) Set The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
 */
class DescribeInstanceNodesInfoResponse extends AbstractModel
{
    /**
     * @var array Be node
Note: This field may return null, indicating that no valid values can be obtained.
     */
    public $BeNodes;

    /**
     * @var array Fe node
Note: This field may return null, indicating that no valid values can be obtained.
     */
    public $FeNodes;

    /**
     * @var string Fe master node
     */
    public $FeMaster;

    /**
     * @var array Be node information
Note: This field may return null, indicating that no valid values can be obtained.
     */
    public $BeNodeInfos;

    /**
     * @var array Fe node information
Note: This field may return null, indicating that no valid values can be obtained.
     */
    public $FeNodeInfos;

    /**
     * @var string The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    public $RequestId;

    /**
     * @param array $BeNodes Be node
Note: This field may return null, indicating that no valid values can be obtained.
     * @param array $FeNodes Fe node
Note: This field may return null, indicating that no valid values can be obtained.
     * @param string $FeMaster Fe master node
     * @param array $BeNodeInfos Be node information
Note: This field may return null, indicating that no valid values can be obtained.
     * @param array $FeNodeInfos Fe node information
Note: This field may return null, indicating that no valid values can be obtained.
     * @param string $RequestId The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    function __construct()
    {

    }

    /**
     * For internal only. DO NOT USE IT.
     */
    public function deserialize($param)
    {
        if ($param === null) {
            return;
        }
        if (array_key_exists("BeNodes",$param) and $param["BeNodes"] !== null) {
            $this->BeNodes = $param["BeNodes"];
        }

        if (array_key_exists("FeNodes",$param) and $param["FeNodes"] !== null) {
            $this->FeNodes = $param["FeNodes"];
        }

        if (array_key_exists("FeMaster",$param) and $param["FeMaster"] !== null) {
            $this->FeMaster = $param["FeMaster"];
        }

        if (array_key_exists("BeNodeInfos",$param) and $param["BeNodeInfos"] !== null) {
            $this->BeNodeInfos = [];
            foreach ($param["BeNodeInfos"] as $key => $value){
                $obj = new NodeInfo();
                $obj->deserialize($value);
                array_push($this->BeNodeInfos, $obj);
            }
        }

        if (array_key_exists("FeNodeInfos",$param) and $param["FeNodeInfos"] !== null) {
            $this->FeNodeInfos = [];
            foreach ($param["FeNodeInfos"] as $key => $value){
                $obj = new NodeInfo();
                $obj->deserialize($value);
                array_push($this->FeNodeInfos, $obj);
            }
        }

        if (array_key_exists("RequestId",$param) and $param["RequestId"] !== null) {
            $this->RequestId = $param["RequestId"];
        }
    }
}
