<?php
/*
 * Copyright (c) 2017-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
namespace TencentCloud\Cdb\V20170320\Models;
use TencentCloud\Common\AbstractModel;

/**
 * DescribeProxySupportParam response structure.
 *
 * @method string getProxyVersion() Obtain Proxy supports the maximum version
 * @method void setProxyVersion(string $ProxyVersion) Set Proxy supports the maximum version
 * @method boolean getSupportPool() Obtain Whether connection pool is supported
 * @method void setSupportPool(boolean $SupportPool) Set Whether connection pool is supported
 * @method integer getPoolMin() Obtain Minimum value of the connection pool
 * @method void setPoolMin(integer $PoolMin) Set Minimum value of the connection pool
 * @method integer getPoolMax() Obtain Maximum value of connection pool
 * @method void setPoolMax(integer $PoolMax) Set Maximum value of connection pool
 * @method boolean getSupportTransSplit() Obtain Whether transaction split is supported
 * @method void setSupportTransSplit(boolean $SupportTransSplit) Set Whether transaction split is supported
 * @method string getSupportPoolMinVersion() Obtain Minimum proxy version that supports connection pool
 * @method void setSupportPoolMinVersion(string $SupportPoolMinVersion) Set Minimum proxy version that supports connection pool
 * @method string getSupportTransSplitMinVersion() Obtain Minimum proxy version supporting transaction split
 * @method void setSupportTransSplitMinVersion(string $SupportTransSplitMinVersion) Set Minimum proxy version supporting transaction split
 * @method boolean getSupportReadOnly() Obtain Whether setting as read-only is supported.
 * @method void setSupportReadOnly(boolean $SupportReadOnly) Set Whether setting as read-only is supported.
 * @method boolean getSupportAutoLoadBalance() Obtain Whether to automatically balance the load
 * @method void setSupportAutoLoadBalance(boolean $SupportAutoLoadBalance) Set Whether to automatically balance the load
 * @method boolean getSupportAccessMode() Obtain Whether support access mode
 * @method void setSupportAccessMode(boolean $SupportAccessMode) Set Whether support access mode
 * @method string getRequestId() Obtain The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
 * @method void setRequestId(string $RequestId) Set The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
 */
class DescribeProxySupportParamResponse extends AbstractModel
{
    /**
     * @var string Proxy supports the maximum version
     */
    public $ProxyVersion;

    /**
     * @var boolean Whether connection pool is supported
     */
    public $SupportPool;

    /**
     * @var integer Minimum value of the connection pool
     */
    public $PoolMin;

    /**
     * @var integer Maximum value of connection pool
     */
    public $PoolMax;

    /**
     * @var boolean Whether transaction split is supported
     */
    public $SupportTransSplit;

    /**
     * @var string Minimum proxy version that supports connection pool
     */
    public $SupportPoolMinVersion;

    /**
     * @var string Minimum proxy version supporting transaction split
     */
    public $SupportTransSplitMinVersion;

    /**
     * @var boolean Whether setting as read-only is supported.
     */
    public $SupportReadOnly;

    /**
     * @var boolean Whether to automatically balance the load
     */
    public $SupportAutoLoadBalance;

    /**
     * @var boolean Whether support access mode
     */
    public $SupportAccessMode;

    /**
     * @var string The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    public $RequestId;

    /**
     * @param string $ProxyVersion Proxy supports the maximum version
     * @param boolean $SupportPool Whether connection pool is supported
     * @param integer $PoolMin Minimum value of the connection pool
     * @param integer $PoolMax Maximum value of connection pool
     * @param boolean $SupportTransSplit Whether transaction split is supported
     * @param string $SupportPoolMinVersion Minimum proxy version that supports connection pool
     * @param string $SupportTransSplitMinVersion Minimum proxy version supporting transaction split
     * @param boolean $SupportReadOnly Whether setting as read-only is supported.
     * @param boolean $SupportAutoLoadBalance Whether to automatically balance the load
     * @param boolean $SupportAccessMode Whether support access mode
     * @param string $RequestId The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    function __construct()
    {

    }

    /**
     * For internal only. DO NOT USE IT.
     */
    public function deserialize($param)
    {
        if ($param === null) {
            return;
        }
        if (array_key_exists("ProxyVersion",$param) and $param["ProxyVersion"] !== null) {
            $this->ProxyVersion = $param["ProxyVersion"];
        }

        if (array_key_exists("SupportPool",$param) and $param["SupportPool"] !== null) {
            $this->SupportPool = $param["SupportPool"];
        }

        if (array_key_exists("PoolMin",$param) and $param["PoolMin"] !== null) {
            $this->PoolMin = $param["PoolMin"];
        }

        if (array_key_exists("PoolMax",$param) and $param["PoolMax"] !== null) {
            $this->PoolMax = $param["PoolMax"];
        }

        if (array_key_exists("SupportTransSplit",$param) and $param["SupportTransSplit"] !== null) {
            $this->SupportTransSplit = $param["SupportTransSplit"];
        }

        if (array_key_exists("SupportPoolMinVersion",$param) and $param["SupportPoolMinVersion"] !== null) {
            $this->SupportPoolMinVersion = $param["SupportPoolMinVersion"];
        }

        if (array_key_exists("SupportTransSplitMinVersion",$param) and $param["SupportTransSplitMinVersion"] !== null) {
            $this->SupportTransSplitMinVersion = $param["SupportTransSplitMinVersion"];
        }

        if (array_key_exists("SupportReadOnly",$param) and $param["SupportReadOnly"] !== null) {
            $this->SupportReadOnly = $param["SupportReadOnly"];
        }

        if (array_key_exists("SupportAutoLoadBalance",$param) and $param["SupportAutoLoadBalance"] !== null) {
            $this->SupportAutoLoadBalance = $param["SupportAutoLoadBalance"];
        }

        if (array_key_exists("SupportAccessMode",$param) and $param["SupportAccessMode"] !== null) {
            $this->SupportAccessMode = $param["SupportAccessMode"];
        }

        if (array_key_exists("RequestId",$param) and $param["RequestId"] !== null) {
            $this->RequestId = $param["RequestId"];
        }
    }
}
