<?php
/*
 * Copyright (c) 2017-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
namespace TencentCloud\Cdb\V20170320\Models;
use TencentCloud\Common\AbstractModel;

/**
 * DescribeClusterInfo response structure.
 *
 * @method string getClusterName() Obtain Instance name.
 * @method void setClusterName(string $ClusterName) Set Instance name.
 * @method AddressInfo getReadWriteAddress() Obtain Address information for reading and writing of the cloud disk edition instance.
 * @method void setReadWriteAddress(AddressInfo $ReadWriteAddress) Set Address information for reading and writing of the cloud disk edition instance.
 * @method array getReadOnlyAddress() Obtain Read-only address information of the cloud disk edition instance.
 * @method void setReadOnlyAddress(array $ReadOnlyAddress) Set Read-only address information of the cloud disk edition instance.
 * @method array getNodeList() Obtain Node list information of the Cloud Disk Edition instance.
 * @method void setNodeList(array $NodeList) Set Node list information of the Cloud Disk Edition instance.
 * @method integer getReadonlyLimit() Obtain Read-only space protection threshold, GB
 * @method void setReadonlyLimit(integer $ReadonlyLimit) Set Read-only space protection threshold, GB
 * @method integer getNodeCount() Obtain Number of instance nodes.
 * @method void setNodeCount(integer $NodeCount) Set Number of instance nodes.
 * @method string getRequestId() Obtain The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
 * @method void setRequestId(string $RequestId) Set The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
 */
class DescribeClusterInfoResponse extends AbstractModel
{
    /**
     * @var string Instance name.
     */
    public $ClusterName;

    /**
     * @var AddressInfo Address information for reading and writing of the cloud disk edition instance.
     */
    public $ReadWriteAddress;

    /**
     * @var array Read-only address information of the cloud disk edition instance.
     */
    public $ReadOnlyAddress;

    /**
     * @var array Node list information of the Cloud Disk Edition instance.
     */
    public $NodeList;

    /**
     * @var integer Read-only space protection threshold, GB
     */
    public $ReadonlyLimit;

    /**
     * @var integer Number of instance nodes.
     */
    public $NodeCount;

    /**
     * @var string The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    public $RequestId;

    /**
     * @param string $ClusterName Instance name.
     * @param AddressInfo $ReadWriteAddress Address information for reading and writing of the cloud disk edition instance.
     * @param array $ReadOnlyAddress Read-only address information of the cloud disk edition instance.
     * @param array $NodeList Node list information of the Cloud Disk Edition instance.
     * @param integer $ReadonlyLimit Read-only space protection threshold, GB
     * @param integer $NodeCount Number of instance nodes.
     * @param string $RequestId The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    function __construct()
    {

    }

    /**
     * For internal only. DO NOT USE IT.
     */
    public function deserialize($param)
    {
        if ($param === null) {
            return;
        }
        if (array_key_exists("ClusterName",$param) and $param["ClusterName"] !== null) {
            $this->ClusterName = $param["ClusterName"];
        }

        if (array_key_exists("ReadWriteAddress",$param) and $param["ReadWriteAddress"] !== null) {
            $this->ReadWriteAddress = new AddressInfo();
            $this->ReadWriteAddress->deserialize($param["ReadWriteAddress"]);
        }

        if (array_key_exists("ReadOnlyAddress",$param) and $param["ReadOnlyAddress"] !== null) {
            $this->ReadOnlyAddress = [];
            foreach ($param["ReadOnlyAddress"] as $key => $value){
                $obj = new AddressInfo();
                $obj->deserialize($value);
                array_push($this->ReadOnlyAddress, $obj);
            }
        }

        if (array_key_exists("NodeList",$param) and $param["NodeList"] !== null) {
            $this->NodeList = [];
            foreach ($param["NodeList"] as $key => $value){
                $obj = new ClusterNodeInfo();
                $obj->deserialize($value);
                array_push($this->NodeList, $obj);
            }
        }

        if (array_key_exists("ReadonlyLimit",$param) and $param["ReadonlyLimit"] !== null) {
            $this->ReadonlyLimit = $param["ReadonlyLimit"];
        }

        if (array_key_exists("NodeCount",$param) and $param["NodeCount"] !== null) {
            $this->NodeCount = $param["NodeCount"];
        }

        if (array_key_exists("RequestId",$param) and $param["RequestId"] !== null) {
            $this->RequestId = $param["RequestId"];
        }
    }
}
