<?php
/*
 * Copyright (c) 2017-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
namespace TencentCloud\Emr\V20190103\Models;
use TencentCloud\Common\AbstractModel;

/**
 * DescribeHDFSStorageInfo response structure.
 *
 * @method integer getSampleTime() Obtain Sampling time.
 * @method void setSampleTime(integer $SampleTime) Set Sampling time.
 * @method array getStorageSummaryDistribution() Obtain Hdfs storage details.
Note: This field may return null, indicating that no valid values can be obtained.
 * @method void setStorageSummaryDistribution(array $StorageSummaryDistribution) Set Hdfs storage details.
Note: This field may return null, indicating that no valid values can be obtained.
 * @method string getRequestId() Obtain The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
 * @method void setRequestId(string $RequestId) Set The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
 */
class DescribeHDFSStorageInfoResponse extends AbstractModel
{
    /**
     * @var integer Sampling time.
     */
    public $SampleTime;

    /**
     * @var array Hdfs storage details.
Note: This field may return null, indicating that no valid values can be obtained.
     */
    public $StorageSummaryDistribution;

    /**
     * @var string The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    public $RequestId;

    /**
     * @param integer $SampleTime Sampling time.
     * @param array $StorageSummaryDistribution Hdfs storage details.
Note: This field may return null, indicating that no valid values can be obtained.
     * @param string $RequestId The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    function __construct()
    {

    }

    /**
     * For internal only. DO NOT USE IT.
     */
    public function deserialize($param)
    {
        if ($param === null) {
            return;
        }
        if (array_key_exists("SampleTime",$param) and $param["SampleTime"] !== null) {
            $this->SampleTime = $param["SampleTime"];
        }

        if (array_key_exists("StorageSummaryDistribution",$param) and $param["StorageSummaryDistribution"] !== null) {
            $this->StorageSummaryDistribution = [];
            foreach ($param["StorageSummaryDistribution"] as $key => $value){
                $obj = new StorageSummaryDistribution();
                $obj->deserialize($value);
                array_push($this->StorageSummaryDistribution, $obj);
            }
        }

        if (array_key_exists("RequestId",$param) and $param["RequestId"] !== null) {
            $this->RequestId = $param["RequestId"];
        }
    }
}
