<?php
/*
 * Copyright (c) 2017-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
namespace TencentCloud\Emr\V20190103\Models;
use TencentCloud\Common\AbstractModel;

/**
 * DescribeAutoScaleStrategies response structure.
 *
 * @method array getLoadAutoScaleStrategies() Obtain Load-based scaling rules

Note: This field may return null, indicating that no valid values can be obtained.
 * @method void setLoadAutoScaleStrategies(array $LoadAutoScaleStrategies) Set Load-based scaling rules

Note: This field may return null, indicating that no valid values can be obtained.
 * @method array getTimeBasedAutoScaleStrategies() Obtain Scaling rules by time

Note: This field may return null, indicating that no valid values can be obtained.
 * @method void setTimeBasedAutoScaleStrategies(array $TimeBasedAutoScaleStrategies) Set Scaling rules by time

Note: This field may return null, indicating that no valid values can be obtained.
 * @method string getRequestId() Obtain The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
 * @method void setRequestId(string $RequestId) Set The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
 */
class DescribeAutoScaleStrategiesResponse extends AbstractModel
{
    /**
     * @var array Load-based scaling rules

Note: This field may return null, indicating that no valid values can be obtained.
     */
    public $LoadAutoScaleStrategies;

    /**
     * @var array Scaling rules by time

Note: This field may return null, indicating that no valid values can be obtained.
     */
    public $TimeBasedAutoScaleStrategies;

    /**
     * @var string The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    public $RequestId;

    /**
     * @param array $LoadAutoScaleStrategies Load-based scaling rules

Note: This field may return null, indicating that no valid values can be obtained.
     * @param array $TimeBasedAutoScaleStrategies Scaling rules by time

Note: This field may return null, indicating that no valid values can be obtained.
     * @param string $RequestId The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    function __construct()
    {

    }

    /**
     * For internal only. DO NOT USE IT.
     */
    public function deserialize($param)
    {
        if ($param === null) {
            return;
        }
        if (array_key_exists("LoadAutoScaleStrategies",$param) and $param["LoadAutoScaleStrategies"] !== null) {
            $this->LoadAutoScaleStrategies = [];
            foreach ($param["LoadAutoScaleStrategies"] as $key => $value){
                $obj = new LoadAutoScaleStrategy();
                $obj->deserialize($value);
                array_push($this->LoadAutoScaleStrategies, $obj);
            }
        }

        if (array_key_exists("TimeBasedAutoScaleStrategies",$param) and $param["TimeBasedAutoScaleStrategies"] !== null) {
            $this->TimeBasedAutoScaleStrategies = [];
            foreach ($param["TimeBasedAutoScaleStrategies"] as $key => $value){
                $obj = new TimeAutoScaleStrategy();
                $obj->deserialize($value);
                array_push($this->TimeBasedAutoScaleStrategies, $obj);
            }
        }

        if (array_key_exists("RequestId",$param) and $param["RequestId"] !== null) {
            $this->RequestId = $param["RequestId"];
        }
    }
}
