<?php
/*
 * Copyright (c) 2017-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
namespace TencentCloud\Intlpartnersmgt\V20220928\Models;
use TencentCloud\Common\AbstractModel;

/**
 * DescribeCustomerVoucherUsageDetails response structure.
 *
 * @method array getData() Obtain Voucher information details
 * @method void setData(array $Data) Set Voucher information details
 * @method integer getCustomerUin() Obtain Customer UIN
 * @method void setCustomerUin(integer $CustomerUin) Set Customer UIN
 * @method integer getVoucherId() Obtain Voucher ID.
 * @method void setVoucherId(integer $VoucherId) Set Voucher ID.
 * @method float getTotalAmount() Obtain Total voucher amount
 * @method void setTotalAmount(float $TotalAmount) Set Total voucher amount
 * @method float getRemainAmount() Obtain Voucher balance
 * @method void setRemainAmount(float $RemainAmount) Set Voucher balance
 * @method integer getTotalRecordsCount() Obtain Total number of records
 * @method void setTotalRecordsCount(integer $TotalRecordsCount) Set Total number of records
 * @method string getMonth() Obtain Voucher Usage Month
 * @method void setMonth(string $Month) Set Voucher Usage Month
 * @method integer getRecordsCountByMonth() Obtain Number of records in the current month
 * @method void setRecordsCountByMonth(integer $RecordsCountByMonth) Set Number of records in the current month
 * @method string getRequestId() Obtain The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
 * @method void setRequestId(string $RequestId) Set The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
 */
class DescribeCustomerVoucherUsageDetailsResponse extends AbstractModel
{
    /**
     * @var array Voucher information details
     */
    public $Data;

    /**
     * @var integer Customer UIN
     */
    public $CustomerUin;

    /**
     * @var integer Voucher ID.
     */
    public $VoucherId;

    /**
     * @var float Total voucher amount
     */
    public $TotalAmount;

    /**
     * @var float Voucher balance
     */
    public $RemainAmount;

    /**
     * @var integer Total number of records
     */
    public $TotalRecordsCount;

    /**
     * @var string Voucher Usage Month
     */
    public $Month;

    /**
     * @var integer Number of records in the current month
     */
    public $RecordsCountByMonth;

    /**
     * @var string The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    public $RequestId;

    /**
     * @param array $Data Voucher information details
     * @param integer $CustomerUin Customer UIN
     * @param integer $VoucherId Voucher ID.
     * @param float $TotalAmount Total voucher amount
     * @param float $RemainAmount Voucher balance
     * @param integer $TotalRecordsCount Total number of records
     * @param string $Month Voucher Usage Month
     * @param integer $RecordsCountByMonth Number of records in the current month
     * @param string $RequestId The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    function __construct()
    {

    }

    /**
     * For internal only. DO NOT USE IT.
     */
    public function deserialize($param)
    {
        if ($param === null) {
            return;
        }
        if (array_key_exists("Data",$param) and $param["Data"] !== null) {
            $this->Data = [];
            foreach ($param["Data"] as $key => $value){
                $obj = new UsageDetail();
                $obj->deserialize($value);
                array_push($this->Data, $obj);
            }
        }

        if (array_key_exists("CustomerUin",$param) and $param["CustomerUin"] !== null) {
            $this->CustomerUin = $param["CustomerUin"];
        }

        if (array_key_exists("VoucherId",$param) and $param["VoucherId"] !== null) {
            $this->VoucherId = $param["VoucherId"];
        }

        if (array_key_exists("TotalAmount",$param) and $param["TotalAmount"] !== null) {
            $this->TotalAmount = $param["TotalAmount"];
        }

        if (array_key_exists("RemainAmount",$param) and $param["RemainAmount"] !== null) {
            $this->RemainAmount = $param["RemainAmount"];
        }

        if (array_key_exists("TotalRecordsCount",$param) and $param["TotalRecordsCount"] !== null) {
            $this->TotalRecordsCount = $param["TotalRecordsCount"];
        }

        if (array_key_exists("Month",$param) and $param["Month"] !== null) {
            $this->Month = $param["Month"];
        }

        if (array_key_exists("RecordsCountByMonth",$param) and $param["RecordsCountByMonth"] !== null) {
            $this->RecordsCountByMonth = $param["RecordsCountByMonth"];
        }

        if (array_key_exists("RequestId",$param) and $param["RequestId"] !== null) {
            $this->RequestId = $param["RequestId"];
        }
    }
}
