<?php
/*
 * Copyright (c) 2017-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
namespace TencentCloud\Alb\V20251030\Models;
use TencentCloud\Common\AbstractModel;

/**
 * DescribeRules response structure.
 *
 * @method string getNextToken() Obtain Token for the next query. If the current page is the last page, this field returns empty.
 * @method void setNextToken(string $NextToken) Set Token for the next query. If the current page is the last page, this field returns empty.
 * @method array getRules() Obtain Forwarding rule list.
 * @method void setRules(array $Rules) Set Forwarding rule list.
 * @method integer getTotalCount() Obtain Total count of forwarding rules (after filtering by conditions such as listener ID and rule ID).
 * @method void setTotalCount(integer $TotalCount) Set Total count of forwarding rules (after filtering by conditions such as listener ID and rule ID).
 * @method string getRequestId() Obtain The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
 * @method void setRequestId(string $RequestId) Set The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
 */
class DescribeRulesResponse extends AbstractModel
{
    /**
     * @var string Token for the next query. If the current page is the last page, this field returns empty.
     */
    public $NextToken;

    /**
     * @var array Forwarding rule list.
     */
    public $Rules;

    /**
     * @var integer Total count of forwarding rules (after filtering by conditions such as listener ID and rule ID).
     */
    public $TotalCount;

    /**
     * @var string The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    public $RequestId;

    /**
     * @param string $NextToken Token for the next query. If the current page is the last page, this field returns empty.
     * @param array $Rules Forwarding rule list.
     * @param integer $TotalCount Total count of forwarding rules (after filtering by conditions such as listener ID and rule ID).
     * @param string $RequestId The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    function __construct()
    {

    }

    /**
     * For internal only. DO NOT USE IT.
     */
    public function deserialize($param)
    {
        if ($param === null) {
            return;
        }
        if (array_key_exists("NextToken",$param) and $param["NextToken"] !== null) {
            $this->NextToken = $param["NextToken"];
        }

        if (array_key_exists("Rules",$param) and $param["Rules"] !== null) {
            $this->Rules = [];
            foreach ($param["Rules"] as $key => $value){
                $obj = new RuleOutput();
                $obj->deserialize($value);
                array_push($this->Rules, $obj);
            }
        }

        if (array_key_exists("TotalCount",$param) and $param["TotalCount"] !== null) {
            $this->TotalCount = $param["TotalCount"];
        }

        if (array_key_exists("RequestId",$param) and $param["RequestId"] !== null) {
            $this->RequestId = $param["RequestId"];
        }
    }
}
