<?php
/*
 * Copyright (c) 2017-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
namespace TencentCloud\Alb\V20251030\Models;
use TencentCloud\Common\AbstractModel;

/**
 * DescribeAsyncJobs response structure.
 *
 * @method array getJobs() Obtain Task list.
 * @method void setJobs(array $Jobs) Set Task list.
 * @method integer getMaxResults() Obtain Entry number displayed each time during batch query.
 * @method void setMaxResults(integer $MaxResults) Set Entry number displayed each time during batch query.
 * @method string getNextToken() Obtain Whether it has the token for the next query. Value: If NextToken is empty, there is no next query. If NextToken has a return value, this value indicates the token for starting the next query.
 * @method void setNextToken(string $NextToken) Set Whether it has the token for the next query. Value: If NextToken is empty, there is no next query. If NextToken has a return value, this value indicates the token for starting the next query.
 * @method integer getTotalCount() Obtain Number of list entries.
 * @method void setTotalCount(integer $TotalCount) Set Number of list entries.
 * @method string getRequestId() Obtain The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
 * @method void setRequestId(string $RequestId) Set The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
 */
class DescribeAsyncJobsResponse extends AbstractModel
{
    /**
     * @var array Task list.
     */
    public $Jobs;

    /**
     * @var integer Entry number displayed each time during batch query.
     */
    public $MaxResults;

    /**
     * @var string Whether it has the token for the next query. Value: If NextToken is empty, there is no next query. If NextToken has a return value, this value indicates the token for starting the next query.
     */
    public $NextToken;

    /**
     * @var integer Number of list entries.
     */
    public $TotalCount;

    /**
     * @var string The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    public $RequestId;

    /**
     * @param array $Jobs Task list.
     * @param integer $MaxResults Entry number displayed each time during batch query.
     * @param string $NextToken Whether it has the token for the next query. Value: If NextToken is empty, there is no next query. If NextToken has a return value, this value indicates the token for starting the next query.
     * @param integer $TotalCount Number of list entries.
     * @param string $RequestId The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    function __construct()
    {

    }

    /**
     * For internal only. DO NOT USE IT.
     */
    public function deserialize($param)
    {
        if ($param === null) {
            return;
        }
        if (array_key_exists("Jobs",$param) and $param["Jobs"] !== null) {
            $this->Jobs = [];
            foreach ($param["Jobs"] as $key => $value){
                $obj = new Job();
                $obj->deserialize($value);
                array_push($this->Jobs, $obj);
            }
        }

        if (array_key_exists("MaxResults",$param) and $param["MaxResults"] !== null) {
            $this->MaxResults = $param["MaxResults"];
        }

        if (array_key_exists("NextToken",$param) and $param["NextToken"] !== null) {
            $this->NextToken = $param["NextToken"];
        }

        if (array_key_exists("TotalCount",$param) and $param["TotalCount"] !== null) {
            $this->TotalCount = $param["TotalCount"];
        }

        if (array_key_exists("RequestId",$param) and $param["RequestId"] !== null) {
            $this->RequestId = $param["RequestId"];
        }
    }
}
