<?php
/*
 * Copyright (c) 2017-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
namespace TencentCloud\Alb\V20251030\Models;
use TencentCloud\Common\AbstractModel;

/**
 * DescribeListenerHealthStatus response structure.
 *
 * @method string getListenerId() Obtain Listener ID, format: lst- followed by 8 alphanumeric characters.
 * @method void setListenerId(string $ListenerId) Set Listener ID, format: lst- followed by 8 alphanumeric characters.
 * @method string getListenerPort() Obtain Listener port.
 * @method void setListenerPort(string $ListenerPort) Set Listener port.
 * @method string getListenerProtocol() Obtain Listener protocol.
 * @method void setListenerProtocol(string $ListenerProtocol) Set Listener protocol.
 * @method string getNextToken() Obtain Token for the next query. If it is empty, this is the last page.
 * @method void setNextToken(string $NextToken) Set Token for the next query. If it is empty, this is the last page.
 * @method array getRuleHealthStatusInfos() Obtain Health status of the forwarding rule.
 * @method void setRuleHealthStatusInfos(array $RuleHealthStatusInfos) Set Health status of the forwarding rule.
 * @method string getRequestId() Obtain The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
 * @method void setRequestId(string $RequestId) Set The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
 */
class DescribeListenerHealthStatusResponse extends AbstractModel
{
    /**
     * @var string Listener ID, format: lst- followed by 8 alphanumeric characters.
     */
    public $ListenerId;

    /**
     * @var string Listener port.
     */
    public $ListenerPort;

    /**
     * @var string Listener protocol.
     */
    public $ListenerProtocol;

    /**
     * @var string Token for the next query. If it is empty, this is the last page.
     */
    public $NextToken;

    /**
     * @var array Health status of the forwarding rule.
     */
    public $RuleHealthStatusInfos;

    /**
     * @var string The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    public $RequestId;

    /**
     * @param string $ListenerId Listener ID, format: lst- followed by 8 alphanumeric characters.
     * @param string $ListenerPort Listener port.
     * @param string $ListenerProtocol Listener protocol.
     * @param string $NextToken Token for the next query. If it is empty, this is the last page.
     * @param array $RuleHealthStatusInfos Health status of the forwarding rule.
     * @param string $RequestId The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    function __construct()
    {

    }

    /**
     * For internal only. DO NOT USE IT.
     */
    public function deserialize($param)
    {
        if ($param === null) {
            return;
        }
        if (array_key_exists("ListenerId",$param) and $param["ListenerId"] !== null) {
            $this->ListenerId = $param["ListenerId"];
        }

        if (array_key_exists("ListenerPort",$param) and $param["ListenerPort"] !== null) {
            $this->ListenerPort = $param["ListenerPort"];
        }

        if (array_key_exists("ListenerProtocol",$param) and $param["ListenerProtocol"] !== null) {
            $this->ListenerProtocol = $param["ListenerProtocol"];
        }

        if (array_key_exists("NextToken",$param) and $param["NextToken"] !== null) {
            $this->NextToken = $param["NextToken"];
        }

        if (array_key_exists("RuleHealthStatusInfos",$param) and $param["RuleHealthStatusInfos"] !== null) {
            $this->RuleHealthStatusInfos = [];
            foreach ($param["RuleHealthStatusInfos"] as $key => $value){
                $obj = new RuleHealthStatusInfo();
                $obj->deserialize($value);
                array_push($this->RuleHealthStatusInfos, $obj);
            }
        }

        if (array_key_exists("RequestId",$param) and $param["RequestId"] !== null) {
            $this->RequestId = $param["RequestId"];
        }
    }
}
