<?php
/*
 * Copyright (c) 2017-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
namespace TencentCloud\Alb\V20251030\Models;
use TencentCloud\Common\AbstractModel;

/**
 * DescribeSecurityPolicies response structure.
 *
 * @method string getNextToken() Obtain Token for the next query.

-If the return value is not empty, it means there is more data. You can use this value as the NextToken parameter in the next request to continue querying.
-If the return value is empty or this field is not returned, it means the current page is the last page.

 * @method void setNextToken(string $NextToken) Set Token for the next query.

-If the return value is not empty, it means there is more data. You can use this value as the NextToken parameter in the next request to continue querying.
-If the return value is empty or this field is not returned, it means the current page is the last page.

 * @method array getSecurityPolicies() Obtain Information list of security policies. Contains detailed configuration of each security policy, such as policy ID, name, TLS version, and encryption suite.

 * @method void setSecurityPolicies(array $SecurityPolicies) Set Information list of security policies. Contains detailed configuration of each security policy, such as policy ID, name, TLS version, and encryption suite.

 * @method integer getTotalCount() Obtain Total number of security policies that meet filtering criteria.

**Description:** This value indicates the total record count that meets the query condition, not the number of records returned this time. It can be used to calculate pagination information.

 * @method void setTotalCount(integer $TotalCount) Set Total number of security policies that meet filtering criteria.

**Description:** This value indicates the total record count that meets the query condition, not the number of records returned this time. It can be used to calculate pagination information.

 * @method string getRequestId() Obtain The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
 * @method void setRequestId(string $RequestId) Set The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
 */
class DescribeSecurityPoliciesResponse extends AbstractModel
{
    /**
     * @var string Token for the next query.

-If the return value is not empty, it means there is more data. You can use this value as the NextToken parameter in the next request to continue querying.
-If the return value is empty or this field is not returned, it means the current page is the last page.

     */
    public $NextToken;

    /**
     * @var array Information list of security policies. Contains detailed configuration of each security policy, such as policy ID, name, TLS version, and encryption suite.

     */
    public $SecurityPolicies;

    /**
     * @var integer Total number of security policies that meet filtering criteria.

**Description:** This value indicates the total record count that meets the query condition, not the number of records returned this time. It can be used to calculate pagination information.

     */
    public $TotalCount;

    /**
     * @var string The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    public $RequestId;

    /**
     * @param string $NextToken Token for the next query.

-If the return value is not empty, it means there is more data. You can use this value as the NextToken parameter in the next request to continue querying.
-If the return value is empty or this field is not returned, it means the current page is the last page.

     * @param array $SecurityPolicies Information list of security policies. Contains detailed configuration of each security policy, such as policy ID, name, TLS version, and encryption suite.

     * @param integer $TotalCount Total number of security policies that meet filtering criteria.

**Description:** This value indicates the total record count that meets the query condition, not the number of records returned this time. It can be used to calculate pagination information.

     * @param string $RequestId The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    function __construct()
    {

    }

    /**
     * For internal only. DO NOT USE IT.
     */
    public function deserialize($param)
    {
        if ($param === null) {
            return;
        }
        if (array_key_exists("NextToken",$param) and $param["NextToken"] !== null) {
            $this->NextToken = $param["NextToken"];
        }

        if (array_key_exists("SecurityPolicies",$param) and $param["SecurityPolicies"] !== null) {
            $this->SecurityPolicies = [];
            foreach ($param["SecurityPolicies"] as $key => $value){
                $obj = new SecurityPolicyInfo();
                $obj->deserialize($value);
                array_push($this->SecurityPolicies, $obj);
            }
        }

        if (array_key_exists("TotalCount",$param) and $param["TotalCount"] !== null) {
            $this->TotalCount = $param["TotalCount"];
        }

        if (array_key_exists("RequestId",$param) and $param["RequestId"] !== null) {
            $this->RequestId = $param["RequestId"];
        }
    }
}
