<?php
/*
 * Copyright (c) 2017-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
namespace TencentCloud\Alb\V20251030\Models;
use TencentCloud\Common\AbstractModel;

/**
 * DescribeTargetGroups response structure.
 *
 * @method string getNextToken() Obtain Token for the next query. If the current page is the last page, this field returns empty.
 * @method void setNextToken(string $NextToken) Set Token for the next query. If the current page is the last page, this field returns empty.
 * @method array getTargetGroups() Obtain Target group information.
 * @method void setTargetGroups(array $TargetGroups) Set Target group information.
 * @method integer getTotalCount() Obtain Total number of target groups.
 * @method void setTotalCount(integer $TotalCount) Set Total number of target groups.
 * @method string getRequestId() Obtain The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
 * @method void setRequestId(string $RequestId) Set The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
 */
class DescribeTargetGroupsResponse extends AbstractModel
{
    /**
     * @var string Token for the next query. If the current page is the last page, this field returns empty.
     */
    public $NextToken;

    /**
     * @var array Target group information.
     */
    public $TargetGroups;

    /**
     * @var integer Total number of target groups.
     */
    public $TotalCount;

    /**
     * @var string The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    public $RequestId;

    /**
     * @param string $NextToken Token for the next query. If the current page is the last page, this field returns empty.
     * @param array $TargetGroups Target group information.
     * @param integer $TotalCount Total number of target groups.
     * @param string $RequestId The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    function __construct()
    {

    }

    /**
     * For internal only. DO NOT USE IT.
     */
    public function deserialize($param)
    {
        if ($param === null) {
            return;
        }
        if (array_key_exists("NextToken",$param) and $param["NextToken"] !== null) {
            $this->NextToken = $param["NextToken"];
        }

        if (array_key_exists("TargetGroups",$param) and $param["TargetGroups"] !== null) {
            $this->TargetGroups = [];
            foreach ($param["TargetGroups"] as $key => $value){
                $obj = new TargetGroupOutput();
                $obj->deserialize($value);
                array_push($this->TargetGroups, $obj);
            }
        }

        if (array_key_exists("TotalCount",$param) and $param["TotalCount"] !== null) {
            $this->TotalCount = $param["TotalCount"];
        }

        if (array_key_exists("RequestId",$param) and $param["RequestId"] !== null) {
            $this->RequestId = $param["RequestId"];
        }
    }
}
