<?php
/*
 * Copyright (c) 2017-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
namespace TencentCloud\Alb\V20251030\Models;
use TencentCloud\Common\AbstractModel;

/**
 * DescribeHealthCheckTemplates response structure.
 *
 * @method array getHealthCheckTemplates() Obtain <p>Health check template list.</p>
 * @method void setHealthCheckTemplates(array $HealthCheckTemplates) Set <p>Health check template list.</p>
 * @method string getNextToken() Obtain <p>Token for the next query. If the current page is the last page, this field returns empty.</p>
 * @method void setNextToken(string $NextToken) Set <p>Token for the next query. If the current page is the last page, this field returns empty.</p>
 * @method integer getTotalCount() Obtain <p>Total number of health check templates queried after filtering.</p>
 * @method void setTotalCount(integer $TotalCount) Set <p>Total number of health check templates queried after filtering.</p>
 * @method string getRequestId() Obtain The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
 * @method void setRequestId(string $RequestId) Set The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
 */
class DescribeHealthCheckTemplatesResponse extends AbstractModel
{
    /**
     * @var array <p>Health check template list.</p>
     */
    public $HealthCheckTemplates;

    /**
     * @var string <p>Token for the next query. If the current page is the last page, this field returns empty.</p>
     */
    public $NextToken;

    /**
     * @var integer <p>Total number of health check templates queried after filtering.</p>
     */
    public $TotalCount;

    /**
     * @var string The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    public $RequestId;

    /**
     * @param array $HealthCheckTemplates <p>Health check template list.</p>
     * @param string $NextToken <p>Token for the next query. If the current page is the last page, this field returns empty.</p>
     * @param integer $TotalCount <p>Total number of health check templates queried after filtering.</p>
     * @param string $RequestId The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    function __construct()
    {

    }

    /**
     * For internal only. DO NOT USE IT.
     */
    public function deserialize($param)
    {
        if ($param === null) {
            return;
        }
        if (array_key_exists("HealthCheckTemplates",$param) and $param["HealthCheckTemplates"] !== null) {
            $this->HealthCheckTemplates = [];
            foreach ($param["HealthCheckTemplates"] as $key => $value){
                $obj = new HealthCheckTemplate();
                $obj->deserialize($value);
                array_push($this->HealthCheckTemplates, $obj);
            }
        }

        if (array_key_exists("NextToken",$param) and $param["NextToken"] !== null) {
            $this->NextToken = $param["NextToken"];
        }

        if (array_key_exists("TotalCount",$param) and $param["TotalCount"] !== null) {
            $this->TotalCount = $param["TotalCount"];
        }

        if (array_key_exists("RequestId",$param) and $param["RequestId"] !== null) {
            $this->RequestId = $param["RequestId"];
        }
    }
}
