<?php
/*
 * Copyright (c) 2017-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
namespace TencentCloud\Csip\V20221121\Models;
use TencentCloud\Common\AbstractModel;

/**
 * CheckIsUltimateVersion response structure.
 *
 * @method boolean getIsUltimateVersion() Obtain <p>Flagship edition user or not</p>
 * @method void setIsUltimateVersion(boolean $IsUltimateVersion) Set <p>Flagship edition user or not</p>
 * @method boolean getIsNewUltimateVersion() Obtain <p>Whether the user is a new version flagship edition user</p>
 * @method void setIsNewUltimateVersion(boolean $IsNewUltimateVersion) Set <p>Whether the user is a new version flagship edition user</p>
 * @method string getRequestId() Obtain The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
 * @method void setRequestId(string $RequestId) Set The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
 */
class CheckIsUltimateVersionResponse extends AbstractModel
{
    /**
     * @var boolean <p>Flagship edition user or not</p>
     */
    public $IsUltimateVersion;

    /**
     * @var boolean <p>Whether the user is a new version flagship edition user</p>
     */
    public $IsNewUltimateVersion;

    /**
     * @var string The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    public $RequestId;

    /**
     * @param boolean $IsUltimateVersion <p>Flagship edition user or not</p>
     * @param boolean $IsNewUltimateVersion <p>Whether the user is a new version flagship edition user</p>
     * @param string $RequestId The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    function __construct()
    {

    }

    /**
     * For internal only. DO NOT USE IT.
     */
    public function deserialize($param)
    {
        if ($param === null) {
            return;
        }
        if (array_key_exists("IsUltimateVersion",$param) and $param["IsUltimateVersion"] !== null) {
            $this->IsUltimateVersion = $param["IsUltimateVersion"];
        }

        if (array_key_exists("IsNewUltimateVersion",$param) and $param["IsNewUltimateVersion"] !== null) {
            $this->IsNewUltimateVersion = $param["IsNewUltimateVersion"];
        }

        if (array_key_exists("RequestId",$param) and $param["RequestId"] !== null) {
            $this->RequestId = $param["RequestId"];
        }
    }
}
