<?php
/*
 * Copyright (c) 2017-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
namespace TencentCloud\Csip\V20221121\Models;
use TencentCloud\Common\AbstractModel;

/**
 * DescribeDspmPayInfo response structure.
 *
 * @method integer getAppID() Obtain APPID
 * @method void setAppID(integer $AppID) Set APPID
 * @method integer getOrderStatus() Obtain Order status. 0: not purchased. 1: normal. 2: isolated. 3: terminated. 6: in trial. 7: expired.
 * @method void setOrderStatus(integer $OrderStatus) Set Order status. 0: not purchased. 1: normal. 2: isolated. 3: terminated. 6: in trial. 7: expired.
 * @method integer getAssetNum() Obtain Number of purchased database instances
 * @method void setAssetNum(integer $AssetNum) Set Number of purchased database instances
 * @method float getLogStorage() Obtain Purchased audit log volume (TB)
 * @method void setLogStorage(float $LogStorage) Set Purchased audit log volume (TB)
 * @method integer getUsedAssetNum() Obtain Number of database instances in use
 * @method void setUsedAssetNum(integer $UsedAssetNum) Set Number of database instances in use
 * @method float getUsedLogStorage() Obtain Used audit log volume (TB)
 * @method void setUsedLogStorage(float $UsedLogStorage) Set Used audit log volume (TB)
 * @method integer getSqlTotal() Obtain Total purchased sql storage (unit: million)
 * @method void setSqlTotal(integer $SqlTotal) Set Total purchased sql storage (unit: million)
 * @method integer getSqlQps() Obtain Purchased sql qps
 * @method void setSqlQps(integer $SqlQps) Set Purchased sql qps
 * @method integer getPayMode() Obtain Payment mode. 0: pay-as-you-go; 1: prepaid
 * @method void setPayMode(integer $PayMode) Set Payment mode. 0: pay-as-you-go; 1: prepaid
 * @method integer getIsSelfBuy() Obtain Whether to purchase separately. 1: separate purchase; 2: shared by other accounts
 * @method void setIsSelfBuy(integer $IsSelfBuy) Set Whether to purchase separately. 1: separate purchase; 2: shared by other accounts
 * @method string getBeginTime() Obtain Order start time.
 * @method void setBeginTime(string $BeginTime) Set Order start time.
 * @method string getEndTime() Obtain Order expiration time
 * @method void setEndTime(string $EndTime) Set Order expiration time
 * @method integer getAutoRenew() Obtain 0: user not set; 1: set auto-renewal by user; 2: set not to auto-renew by user
 * @method void setAutoRenew(integer $AutoRenew) Set 0: user not set; 1: set auto-renewal by user; 2: set not to auto-renew by user
 * @method integer getTimeSpan() Obtain Order duration
 * @method void setTimeSpan(integer $TimeSpan) Set Order duration
 * @method string getTimeUnit() Obtain Duration unit.
 * @method void setTimeUnit(string $TimeUnit) Set Duration unit.
 * @method string getResourceId() Obtain Resource ID
 * @method void setResourceId(string $ResourceId) Set Resource ID
 * @method string getBetaEndTime() Obtain Open beta end time
 * @method void setBetaEndTime(string $BetaEndTime) Set Open beta end time
 * @method string getTimeNow() Obtain Current system time.
 * @method void setTimeNow(string $TimeNow) Set Current system time.
 * @method integer getIsShareToOther() Obtain Whether to share with other accounts. 1: yes; 2: no
 * @method void setIsShareToOther(integer $IsShareToOther) Set Whether to share with other accounts. 1: yes; 2: no
 * @method string getUin() Obtain uin
 * @method void setUin(string $Uin) Set uin
 * @method string getNickName() Obtain Nickname
 * @method void setNickName(string $NickName) Set Nickname
 * @method array getInquireData() Obtain Purchase information
 * @method void setInquireData(array $InquireData) Set Purchase information
 * @method string getVersion() Obtain Edition (Professional: professional; Trial: trial)
 * @method void setVersion(string $Version) Set Edition (Professional: professional; Trial: trial)
 * @method string getRequestId() Obtain The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
 * @method void setRequestId(string $RequestId) Set The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
 */
class DescribeDspmPayInfoResponse extends AbstractModel
{
    /**
     * @var integer APPID
     */
    public $AppID;

    /**
     * @var integer Order status. 0: not purchased. 1: normal. 2: isolated. 3: terminated. 6: in trial. 7: expired.
     */
    public $OrderStatus;

    /**
     * @var integer Number of purchased database instances
     */
    public $AssetNum;

    /**
     * @var float Purchased audit log volume (TB)
     */
    public $LogStorage;

    /**
     * @var integer Number of database instances in use
     */
    public $UsedAssetNum;

    /**
     * @var float Used audit log volume (TB)
     */
    public $UsedLogStorage;

    /**
     * @var integer Total purchased sql storage (unit: million)
     */
    public $SqlTotal;

    /**
     * @var integer Purchased sql qps
     */
    public $SqlQps;

    /**
     * @var integer Payment mode. 0: pay-as-you-go; 1: prepaid
     */
    public $PayMode;

    /**
     * @var integer Whether to purchase separately. 1: separate purchase; 2: shared by other accounts
     */
    public $IsSelfBuy;

    /**
     * @var string Order start time.
     */
    public $BeginTime;

    /**
     * @var string Order expiration time
     */
    public $EndTime;

    /**
     * @var integer 0: user not set; 1: set auto-renewal by user; 2: set not to auto-renew by user
     */
    public $AutoRenew;

    /**
     * @var integer Order duration
     */
    public $TimeSpan;

    /**
     * @var string Duration unit.
     */
    public $TimeUnit;

    /**
     * @var string Resource ID
     */
    public $ResourceId;

    /**
     * @var string Open beta end time
     */
    public $BetaEndTime;

    /**
     * @var string Current system time.
     */
    public $TimeNow;

    /**
     * @var integer Whether to share with other accounts. 1: yes; 2: no
     */
    public $IsShareToOther;

    /**
     * @var string uin
     */
    public $Uin;

    /**
     * @var string Nickname
     */
    public $NickName;

    /**
     * @var array Purchase information
     */
    public $InquireData;

    /**
     * @var string Edition (Professional: professional; Trial: trial)
     */
    public $Version;

    /**
     * @var string The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    public $RequestId;

    /**
     * @param integer $AppID APPID
     * @param integer $OrderStatus Order status. 0: not purchased. 1: normal. 2: isolated. 3: terminated. 6: in trial. 7: expired.
     * @param integer $AssetNum Number of purchased database instances
     * @param float $LogStorage Purchased audit log volume (TB)
     * @param integer $UsedAssetNum Number of database instances in use
     * @param float $UsedLogStorage Used audit log volume (TB)
     * @param integer $SqlTotal Total purchased sql storage (unit: million)
     * @param integer $SqlQps Purchased sql qps
     * @param integer $PayMode Payment mode. 0: pay-as-you-go; 1: prepaid
     * @param integer $IsSelfBuy Whether to purchase separately. 1: separate purchase; 2: shared by other accounts
     * @param string $BeginTime Order start time.
     * @param string $EndTime Order expiration time
     * @param integer $AutoRenew 0: user not set; 1: set auto-renewal by user; 2: set not to auto-renew by user
     * @param integer $TimeSpan Order duration
     * @param string $TimeUnit Duration unit.
     * @param string $ResourceId Resource ID
     * @param string $BetaEndTime Open beta end time
     * @param string $TimeNow Current system time.
     * @param integer $IsShareToOther Whether to share with other accounts. 1: yes; 2: no
     * @param string $Uin uin
     * @param string $NickName Nickname
     * @param array $InquireData Purchase information
     * @param string $Version Edition (Professional: professional; Trial: trial)
     * @param string $RequestId The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    function __construct()
    {

    }

    /**
     * For internal only. DO NOT USE IT.
     */
    public function deserialize($param)
    {
        if ($param === null) {
            return;
        }
        if (array_key_exists("AppID",$param) and $param["AppID"] !== null) {
            $this->AppID = $param["AppID"];
        }

        if (array_key_exists("OrderStatus",$param) and $param["OrderStatus"] !== null) {
            $this->OrderStatus = $param["OrderStatus"];
        }

        if (array_key_exists("AssetNum",$param) and $param["AssetNum"] !== null) {
            $this->AssetNum = $param["AssetNum"];
        }

        if (array_key_exists("LogStorage",$param) and $param["LogStorage"] !== null) {
            $this->LogStorage = $param["LogStorage"];
        }

        if (array_key_exists("UsedAssetNum",$param) and $param["UsedAssetNum"] !== null) {
            $this->UsedAssetNum = $param["UsedAssetNum"];
        }

        if (array_key_exists("UsedLogStorage",$param) and $param["UsedLogStorage"] !== null) {
            $this->UsedLogStorage = $param["UsedLogStorage"];
        }

        if (array_key_exists("SqlTotal",$param) and $param["SqlTotal"] !== null) {
            $this->SqlTotal = $param["SqlTotal"];
        }

        if (array_key_exists("SqlQps",$param) and $param["SqlQps"] !== null) {
            $this->SqlQps = $param["SqlQps"];
        }

        if (array_key_exists("PayMode",$param) and $param["PayMode"] !== null) {
            $this->PayMode = $param["PayMode"];
        }

        if (array_key_exists("IsSelfBuy",$param) and $param["IsSelfBuy"] !== null) {
            $this->IsSelfBuy = $param["IsSelfBuy"];
        }

        if (array_key_exists("BeginTime",$param) and $param["BeginTime"] !== null) {
            $this->BeginTime = $param["BeginTime"];
        }

        if (array_key_exists("EndTime",$param) and $param["EndTime"] !== null) {
            $this->EndTime = $param["EndTime"];
        }

        if (array_key_exists("AutoRenew",$param) and $param["AutoRenew"] !== null) {
            $this->AutoRenew = $param["AutoRenew"];
        }

        if (array_key_exists("TimeSpan",$param) and $param["TimeSpan"] !== null) {
            $this->TimeSpan = $param["TimeSpan"];
        }

        if (array_key_exists("TimeUnit",$param) and $param["TimeUnit"] !== null) {
            $this->TimeUnit = $param["TimeUnit"];
        }

        if (array_key_exists("ResourceId",$param) and $param["ResourceId"] !== null) {
            $this->ResourceId = $param["ResourceId"];
        }

        if (array_key_exists("BetaEndTime",$param) and $param["BetaEndTime"] !== null) {
            $this->BetaEndTime = $param["BetaEndTime"];
        }

        if (array_key_exists("TimeNow",$param) and $param["TimeNow"] !== null) {
            $this->TimeNow = $param["TimeNow"];
        }

        if (array_key_exists("IsShareToOther",$param) and $param["IsShareToOther"] !== null) {
            $this->IsShareToOther = $param["IsShareToOther"];
        }

        if (array_key_exists("Uin",$param) and $param["Uin"] !== null) {
            $this->Uin = $param["Uin"];
        }

        if (array_key_exists("NickName",$param) and $param["NickName"] !== null) {
            $this->NickName = $param["NickName"];
        }

        if (array_key_exists("InquireData",$param) and $param["InquireData"] !== null) {
            $this->InquireData = [];
            foreach ($param["InquireData"] as $key => $value){
                $obj = new InquireInfo();
                $obj->deserialize($value);
                array_push($this->InquireData, $obj);
            }
        }

        if (array_key_exists("Version",$param) and $param["Version"] !== null) {
            $this->Version = $param["Version"];
        }

        if (array_key_exists("RequestId",$param) and $param["RequestId"] !== null) {
            $this->RequestId = $param["RequestId"];
        }
    }
}
