<?php
/*
 * Copyright (c) 2017-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
namespace TencentCloud\Csip\V20221121\Models;
use TencentCloud\Common\AbstractModel;

/**
 * DescribeAssetRiskList response structure.
 *
 * @method integer getTotalCount() Obtain Number of risks from the asset perspective
 * @method void setTotalCount(integer $TotalCount) Set Number of risks from the asset perspective
 * @method array getAssetRiskList() Obtain Risk list from the asset perspective
 * @method void setAssetRiskList(array $AssetRiskList) Set Risk list from the asset perspective
 * @method array getStandardNameList() Obtain Collection of MLPS standard names
 * @method void setStandardNameList(array $StandardNameList) Set Collection of MLPS standard names
 * @method array getAssetTypeList() Obtain Asset type collection
 * @method void setAssetTypeList(array $AssetTypeList) Set Asset type collection
 * @method string getRequestId() Obtain The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
 * @method void setRequestId(string $RequestId) Set The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
 */
class DescribeAssetRiskListResponse extends AbstractModel
{
    /**
     * @var integer Number of risks from the asset perspective
     */
    public $TotalCount;

    /**
     * @var array Risk list from the asset perspective
     */
    public $AssetRiskList;

    /**
     * @var array Collection of MLPS standard names
     */
    public $StandardNameList;

    /**
     * @var array Asset type collection
     */
    public $AssetTypeList;

    /**
     * @var string The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    public $RequestId;

    /**
     * @param integer $TotalCount Number of risks from the asset perspective
     * @param array $AssetRiskList Risk list from the asset perspective
     * @param array $StandardNameList Collection of MLPS standard names
     * @param array $AssetTypeList Asset type collection
     * @param string $RequestId The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    function __construct()
    {

    }

    /**
     * For internal only. DO NOT USE IT.
     */
    public function deserialize($param)
    {
        if ($param === null) {
            return;
        }
        if (array_key_exists("TotalCount",$param) and $param["TotalCount"] !== null) {
            $this->TotalCount = $param["TotalCount"];
        }

        if (array_key_exists("AssetRiskList",$param) and $param["AssetRiskList"] !== null) {
            $this->AssetRiskList = [];
            foreach ($param["AssetRiskList"] as $key => $value){
                $obj = new AssetRiskItem();
                $obj->deserialize($value);
                array_push($this->AssetRiskList, $obj);
            }
        }

        if (array_key_exists("StandardNameList",$param) and $param["StandardNameList"] !== null) {
            $this->StandardNameList = [];
            foreach ($param["StandardNameList"] as $key => $value){
                $obj = new StandardItem();
                $obj->deserialize($value);
                array_push($this->StandardNameList, $obj);
            }
        }

        if (array_key_exists("AssetTypeList",$param) and $param["AssetTypeList"] !== null) {
            $this->AssetTypeList = [];
            foreach ($param["AssetTypeList"] as $key => $value){
                $obj = new AttributeOptionSet();
                $obj->deserialize($value);
                array_push($this->AssetTypeList, $obj);
            }
        }

        if (array_key_exists("RequestId",$param) and $param["RequestId"] !== null) {
            $this->RequestId = $param["RequestId"];
        }
    }
}
