<?php
/*
 * Copyright (c) 2017-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
namespace TencentCloud\Csip\V20221121\Models;
use TencentCloud\Common\AbstractModel;

/**
 * DescribeCustomRiskRules response structure.
 *
 * @method integer getTotalCount() Obtain <p>Number of risk rules</p>
 * @method void setTotalCount(integer $TotalCount) Set <p>Number of risk rules</p>
 * @method array getRiskRuleList() Obtain <p>Risk rule list</p>
 * @method void setRiskRuleList(array $RiskRuleList) Set <p>Risk rule list</p>
 * @method array getProviderList() Obtain <p>Cloud service provider options</p>
 * @method void setProviderList(array $ProviderList) Set <p>Cloud service provider options</p>
 * @method array getAssetTypeList() Obtain <p>Asset type options</p>
 * @method void setAssetTypeList(array $AssetTypeList) Set <p>Asset type options</p>
 * @method array getStandardNameList() Obtain <p>Security clause specification</p>
 * @method void setStandardNameList(array $StandardNameList) Set <p>Security clause specification</p>
 * @method array getRuleSeverityList() Obtain <p>Risk level.</p>
 * @method void setRuleSeverityList(array $RuleSeverityList) Set <p>Risk level.</p>
 * @method array getCheckTypeList() Obtain <p>Check type</p>
 * @method void setCheckTypeList(array $CheckTypeList) Set <p>Check type</p>
 * @method array getClassifyList() Obtain <p>Security category</p>
 * @method void setClassifyList(array $ClassifyList) Set <p>Security category</p>
 * @method array getStandardList() Obtain <p>Security specification</p>
 * @method void setStandardList(array $StandardList) Set <p>Security specification</p>
 * @method string getRequestId() Obtain The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
 * @method void setRequestId(string $RequestId) Set The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
 */
class DescribeCustomRiskRulesResponse extends AbstractModel
{
    /**
     * @var integer <p>Number of risk rules</p>
     */
    public $TotalCount;

    /**
     * @var array <p>Risk rule list</p>
     */
    public $RiskRuleList;

    /**
     * @var array <p>Cloud service provider options</p>
     */
    public $ProviderList;

    /**
     * @var array <p>Asset type options</p>
     */
    public $AssetTypeList;

    /**
     * @var array <p>Security clause specification</p>
     */
    public $StandardNameList;

    /**
     * @var array <p>Risk level.</p>
     */
    public $RuleSeverityList;

    /**
     * @var array <p>Check type</p>
     */
    public $CheckTypeList;

    /**
     * @var array <p>Security category</p>
     */
    public $ClassifyList;

    /**
     * @var array <p>Security specification</p>
     */
    public $StandardList;

    /**
     * @var string The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    public $RequestId;

    /**
     * @param integer $TotalCount <p>Number of risk rules</p>
     * @param array $RiskRuleList <p>Risk rule list</p>
     * @param array $ProviderList <p>Cloud service provider options</p>
     * @param array $AssetTypeList <p>Asset type options</p>
     * @param array $StandardNameList <p>Security clause specification</p>
     * @param array $RuleSeverityList <p>Risk level.</p>
     * @param array $CheckTypeList <p>Check type</p>
     * @param array $ClassifyList <p>Security category</p>
     * @param array $StandardList <p>Security specification</p>
     * @param string $RequestId The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    function __construct()
    {

    }

    /**
     * For internal only. DO NOT USE IT.
     */
    public function deserialize($param)
    {
        if ($param === null) {
            return;
        }
        if (array_key_exists("TotalCount",$param) and $param["TotalCount"] !== null) {
            $this->TotalCount = $param["TotalCount"];
        }

        if (array_key_exists("RiskRuleList",$param) and $param["RiskRuleList"] !== null) {
            $this->RiskRuleList = [];
            foreach ($param["RiskRuleList"] as $key => $value){
                $obj = new CustomRiskRuleItem();
                $obj->deserialize($value);
                array_push($this->RiskRuleList, $obj);
            }
        }

        if (array_key_exists("ProviderList",$param) and $param["ProviderList"] !== null) {
            $this->ProviderList = [];
            foreach ($param["ProviderList"] as $key => $value){
                $obj = new AttributeOptionSet();
                $obj->deserialize($value);
                array_push($this->ProviderList, $obj);
            }
        }

        if (array_key_exists("AssetTypeList",$param) and $param["AssetTypeList"] !== null) {
            $this->AssetTypeList = [];
            foreach ($param["AssetTypeList"] as $key => $value){
                $obj = new AttributeOptionSet();
                $obj->deserialize($value);
                array_push($this->AssetTypeList, $obj);
            }
        }

        if (array_key_exists("StandardNameList",$param) and $param["StandardNameList"] !== null) {
            $this->StandardNameList = [];
            foreach ($param["StandardNameList"] as $key => $value){
                $obj = new StandardItem();
                $obj->deserialize($value);
                array_push($this->StandardNameList, $obj);
            }
        }

        if (array_key_exists("RuleSeverityList",$param) and $param["RuleSeverityList"] !== null) {
            $this->RuleSeverityList = [];
            foreach ($param["RuleSeverityList"] as $key => $value){
                $obj = new RuleStatisticsItem();
                $obj->deserialize($value);
                array_push($this->RuleSeverityList, $obj);
            }
        }

        if (array_key_exists("CheckTypeList",$param) and $param["CheckTypeList"] !== null) {
            $this->CheckTypeList = [];
            foreach ($param["CheckTypeList"] as $key => $value){
                $obj = new RuleStatisticsItem();
                $obj->deserialize($value);
                array_push($this->CheckTypeList, $obj);
            }
        }

        if (array_key_exists("ClassifyList",$param) and $param["ClassifyList"] !== null) {
            $this->ClassifyList = [];
            foreach ($param["ClassifyList"] as $key => $value){
                $obj = new RuleStatisticsItem();
                $obj->deserialize($value);
                array_push($this->ClassifyList, $obj);
            }
        }

        if (array_key_exists("StandardList",$param) and $param["StandardList"] !== null) {
            $this->StandardList = [];
            foreach ($param["StandardList"] as $key => $value){
                $obj = new RuleStatisticsItem();
                $obj->deserialize($value);
                array_push($this->StandardList, $obj);
            }
        }

        if (array_key_exists("RequestId",$param) and $param["RequestId"] !== null) {
            $this->RequestId = $param["RequestId"];
        }
    }
}
