<?php
/*
 * Copyright (c) 2017-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
namespace TencentCloud\Csip\V20221121\Models;
use TencentCloud\Common\AbstractModel;

/**
 * DescribeAccessKeyRiskDetail response structure.
 *
 * @method AccessKeyRisk getRiskInfo() Obtain Risk list.
 * @method void setRiskInfo(AccessKeyRisk $RiskInfo) Set Risk list.
 * @method integer getCamCount() Obtain Total number of CAM policies.
 * @method void setCamCount(integer $CamCount) Set Total number of CAM policies.
 * @method integer getAlarmCount() Obtain Number of associated alarms for the account.
 * @method void setAlarmCount(integer $AlarmCount) Set Number of associated alarms for the account.
 * @method integer getAccessType() Obtain Access method 0 API 1 console and API.
 * @method void setAccessType(integer $AccessType) Set Access method 0 API 1 console and API.
 * @method array getAccessKeyAlarmCount() Obtain Access key Alarm count list.
 * @method void setAccessKeyAlarmCount(array $AccessKeyAlarmCount) Set Access key Alarm count list.
 * @method integer getActionFlag() Obtain Whether operation protection is enabled. valid values: 0 (not enabled), 1 (enabled).
 * @method void setActionFlag(integer $ActionFlag) Set Whether operation protection is enabled. valid values: 0 (not enabled), 1 (enabled).
 * @method integer getLoginFlag() Obtain Whether login protection is enabled. valid values: 0 (not enabled), 1 (enabled).
 * @method void setLoginFlag(integer $LoginFlag) Set Whether login protection is enabled. valid values: 0 (not enabled), 1 (enabled).
 * @method string getRequestId() Obtain The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
 * @method void setRequestId(string $RequestId) Set The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
 */
class DescribeAccessKeyRiskDetailResponse extends AbstractModel
{
    /**
     * @var AccessKeyRisk Risk list.
     */
    public $RiskInfo;

    /**
     * @var integer Total number of CAM policies.
     */
    public $CamCount;

    /**
     * @var integer Number of associated alarms for the account.
     */
    public $AlarmCount;

    /**
     * @var integer Access method 0 API 1 console and API.
     */
    public $AccessType;

    /**
     * @var array Access key Alarm count list.
     */
    public $AccessKeyAlarmCount;

    /**
     * @var integer Whether operation protection is enabled. valid values: 0 (not enabled), 1 (enabled).
     */
    public $ActionFlag;

    /**
     * @var integer Whether login protection is enabled. valid values: 0 (not enabled), 1 (enabled).
     */
    public $LoginFlag;

    /**
     * @var string The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    public $RequestId;

    /**
     * @param AccessKeyRisk $RiskInfo Risk list.
     * @param integer $CamCount Total number of CAM policies.
     * @param integer $AlarmCount Number of associated alarms for the account.
     * @param integer $AccessType Access method 0 API 1 console and API.
     * @param array $AccessKeyAlarmCount Access key Alarm count list.
     * @param integer $ActionFlag Whether operation protection is enabled. valid values: 0 (not enabled), 1 (enabled).
     * @param integer $LoginFlag Whether login protection is enabled. valid values: 0 (not enabled), 1 (enabled).
     * @param string $RequestId The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    function __construct()
    {

    }

    /**
     * For internal only. DO NOT USE IT.
     */
    public function deserialize($param)
    {
        if ($param === null) {
            return;
        }
        if (array_key_exists("RiskInfo",$param) and $param["RiskInfo"] !== null) {
            $this->RiskInfo = new AccessKeyRisk();
            $this->RiskInfo->deserialize($param["RiskInfo"]);
        }

        if (array_key_exists("CamCount",$param) and $param["CamCount"] !== null) {
            $this->CamCount = $param["CamCount"];
        }

        if (array_key_exists("AlarmCount",$param) and $param["AlarmCount"] !== null) {
            $this->AlarmCount = $param["AlarmCount"];
        }

        if (array_key_exists("AccessType",$param) and $param["AccessType"] !== null) {
            $this->AccessType = $param["AccessType"];
        }

        if (array_key_exists("AccessKeyAlarmCount",$param) and $param["AccessKeyAlarmCount"] !== null) {
            $this->AccessKeyAlarmCount = [];
            foreach ($param["AccessKeyAlarmCount"] as $key => $value){
                $obj = new AccessKeyAlarmCount();
                $obj->deserialize($value);
                array_push($this->AccessKeyAlarmCount, $obj);
            }
        }

        if (array_key_exists("ActionFlag",$param) and $param["ActionFlag"] !== null) {
            $this->ActionFlag = $param["ActionFlag"];
        }

        if (array_key_exists("LoginFlag",$param) and $param["LoginFlag"] !== null) {
            $this->LoginFlag = $param["LoginFlag"];
        }

        if (array_key_exists("RequestId",$param) and $param["RequestId"] !== null) {
            $this->RequestId = $param["RequestId"];
        }
    }
}
