<?php
/*
 * Copyright (c) 2017-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
namespace TencentCloud\Csip\V20221121\Models;
use TencentCloud\Common\AbstractModel;

/**
 * DescribeCWPScanIpInfo response structure.
 *
 * @method string getBussiness() Obtain <p>Associated business</p>
 * @method void setBussiness(string $Bussiness) Set <p>Associated business</p>
 * @method string getCharacteristic() Obtain <p>Business characteristic</p>
 * @method void setCharacteristic(string $Characteristic) Set <p>Business characteristic</p>
 * @method string getDescribe() Obtain <p>Description.</p>
 * @method void setDescribe(string $Describe) Set <p>Description.</p>
 * @method string getReferer() Obtain <p>Official announcement</p>
 * @method void setReferer(string $Referer) Set <p>Official announcement</p>
 * @method string getDemo() Obtain <p>Scan example</p>
 * @method void setDemo(string $Demo) Set <p>Scan example</p>
 * @method string getTarget() Obtain <p>Scan target</p>
 * @method void setTarget(string $Target) Set <p>Scan target</p>
 * @method string getPurpose() Obtain <p>Scan target</p>
 * @method void setPurpose(string $Purpose) Set <p>Scan target</p>
 * @method string getAnnouncement() Obtain <p>Product copywriting</p>
 * @method void setAnnouncement(string $Announcement) Set <p>Product copywriting</p>
 * @method string getLocation() Obtain <p>Geographic location</p>
 * @method void setLocation(string $Location) Set <p>Geographic location</p>
 * @method string getISP() Obtain <p>Associated operator</p>
 * @method void setISP(string $ISP) Set <p>Associated operator</p>
 * @method boolean getIsBelongTencent() Obtain <p>Whether it belongs to Tencent</p>
 * @method void setIsBelongTencent(boolean $IsBelongTencent) Set <p>Whether it belongs to Tencent</p>
 * @method string getRequestId() Obtain The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
 * @method void setRequestId(string $RequestId) Set The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
 */
class DescribeCWPScanIpInfoResponse extends AbstractModel
{
    /**
     * @var string <p>Associated business</p>
     */
    public $Bussiness;

    /**
     * @var string <p>Business characteristic</p>
     */
    public $Characteristic;

    /**
     * @var string <p>Description.</p>
     */
    public $Describe;

    /**
     * @var string <p>Official announcement</p>
     */
    public $Referer;

    /**
     * @var string <p>Scan example</p>
     */
    public $Demo;

    /**
     * @var string <p>Scan target</p>
     */
    public $Target;

    /**
     * @var string <p>Scan target</p>
     */
    public $Purpose;

    /**
     * @var string <p>Product copywriting</p>
     */
    public $Announcement;

    /**
     * @var string <p>Geographic location</p>
     */
    public $Location;

    /**
     * @var string <p>Associated operator</p>
     */
    public $ISP;

    /**
     * @var boolean <p>Whether it belongs to Tencent</p>
     */
    public $IsBelongTencent;

    /**
     * @var string The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    public $RequestId;

    /**
     * @param string $Bussiness <p>Associated business</p>
     * @param string $Characteristic <p>Business characteristic</p>
     * @param string $Describe <p>Description.</p>
     * @param string $Referer <p>Official announcement</p>
     * @param string $Demo <p>Scan example</p>
     * @param string $Target <p>Scan target</p>
     * @param string $Purpose <p>Scan target</p>
     * @param string $Announcement <p>Product copywriting</p>
     * @param string $Location <p>Geographic location</p>
     * @param string $ISP <p>Associated operator</p>
     * @param boolean $IsBelongTencent <p>Whether it belongs to Tencent</p>
     * @param string $RequestId The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    function __construct()
    {

    }

    /**
     * For internal only. DO NOT USE IT.
     */
    public function deserialize($param)
    {
        if ($param === null) {
            return;
        }
        if (array_key_exists("Bussiness",$param) and $param["Bussiness"] !== null) {
            $this->Bussiness = $param["Bussiness"];
        }

        if (array_key_exists("Characteristic",$param) and $param["Characteristic"] !== null) {
            $this->Characteristic = $param["Characteristic"];
        }

        if (array_key_exists("Describe",$param) and $param["Describe"] !== null) {
            $this->Describe = $param["Describe"];
        }

        if (array_key_exists("Referer",$param) and $param["Referer"] !== null) {
            $this->Referer = $param["Referer"];
        }

        if (array_key_exists("Demo",$param) and $param["Demo"] !== null) {
            $this->Demo = $param["Demo"];
        }

        if (array_key_exists("Target",$param) and $param["Target"] !== null) {
            $this->Target = $param["Target"];
        }

        if (array_key_exists("Purpose",$param) and $param["Purpose"] !== null) {
            $this->Purpose = $param["Purpose"];
        }

        if (array_key_exists("Announcement",$param) and $param["Announcement"] !== null) {
            $this->Announcement = $param["Announcement"];
        }

        if (array_key_exists("Location",$param) and $param["Location"] !== null) {
            $this->Location = $param["Location"];
        }

        if (array_key_exists("ISP",$param) and $param["ISP"] !== null) {
            $this->ISP = $param["ISP"];
        }

        if (array_key_exists("IsBelongTencent",$param) and $param["IsBelongTencent"] !== null) {
            $this->IsBelongTencent = $param["IsBelongTencent"];
        }

        if (array_key_exists("RequestId",$param) and $param["RequestId"] !== null) {
            $this->RequestId = $param["RequestId"];
        }
    }
}
