<?php
/*
 * Copyright (c) 2017-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
namespace TencentCloud\Csip\V20221121\Models;
use TencentCloud\Common\AbstractModel;

/**
 * DescribeRiskCenterCFGViewCFGRiskList response structure.
 *
 * @method integer getTotalCount() Obtain Total number of entries
 * @method void setTotalCount(integer $TotalCount) Set Total number of entries
 * @method array getData() Obtain Configuration Risk List from Asset's Perspective
 * @method void setData(array $Data) Set Configuration Risk List from Asset's Perspective
 * @method array getStatusLists() Obtain Status list
 * @method void setStatusLists(array $StatusLists) Set Status list
 * @method array getLevelLists() Obtain Danger Level List
 * @method void setLevelLists(array $LevelLists) Set Danger Level List
 * @method array getCFGNameLists() Obtain Configuration Name List
 * @method void setCFGNameLists(array $CFGNameLists) Set Configuration Name List
 * @method array getCheckTypeLists() Obtain Check Type List
 * @method void setCheckTypeLists(array $CheckTypeLists) Set Check Type List
 * @method array getInstanceTypeLists() Obtain Asset Type List
 * @method void setInstanceTypeLists(array $InstanceTypeLists) Set Asset Type List
 * @method array getFromLists() Obtain Source List
 * @method void setFromLists(array $FromLists) Set Source List
 * @method string getRequestId() Obtain The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
 * @method void setRequestId(string $RequestId) Set The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
 */
class DescribeRiskCenterCFGViewCFGRiskListResponse extends AbstractModel
{
    /**
     * @var integer Total number of entries
     */
    public $TotalCount;

    /**
     * @var array Configuration Risk List from Asset's Perspective
     */
    public $Data;

    /**
     * @var array Status list
     */
    public $StatusLists;

    /**
     * @var array Danger Level List
     */
    public $LevelLists;

    /**
     * @var array Configuration Name List
     */
    public $CFGNameLists;

    /**
     * @var array Check Type List
     */
    public $CheckTypeLists;

    /**
     * @var array Asset Type List
     */
    public $InstanceTypeLists;

    /**
     * @var array Source List
     */
    public $FromLists;

    /**
     * @var string The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    public $RequestId;

    /**
     * @param integer $TotalCount Total number of entries
     * @param array $Data Configuration Risk List from Asset's Perspective
     * @param array $StatusLists Status list
     * @param array $LevelLists Danger Level List
     * @param array $CFGNameLists Configuration Name List
     * @param array $CheckTypeLists Check Type List
     * @param array $InstanceTypeLists Asset Type List
     * @param array $FromLists Source List
     * @param string $RequestId The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    function __construct()
    {

    }

    /**
     * For internal only. DO NOT USE IT.
     */
    public function deserialize($param)
    {
        if ($param === null) {
            return;
        }
        if (array_key_exists("TotalCount",$param) and $param["TotalCount"] !== null) {
            $this->TotalCount = $param["TotalCount"];
        }

        if (array_key_exists("Data",$param) and $param["Data"] !== null) {
            $this->Data = [];
            foreach ($param["Data"] as $key => $value){
                $obj = new CFGViewCFGRisk();
                $obj->deserialize($value);
                array_push($this->Data, $obj);
            }
        }

        if (array_key_exists("StatusLists",$param) and $param["StatusLists"] !== null) {
            $this->StatusLists = [];
            foreach ($param["StatusLists"] as $key => $value){
                $obj = new FilterDataObject();
                $obj->deserialize($value);
                array_push($this->StatusLists, $obj);
            }
        }

        if (array_key_exists("LevelLists",$param) and $param["LevelLists"] !== null) {
            $this->LevelLists = [];
            foreach ($param["LevelLists"] as $key => $value){
                $obj = new FilterDataObject();
                $obj->deserialize($value);
                array_push($this->LevelLists, $obj);
            }
        }

        if (array_key_exists("CFGNameLists",$param) and $param["CFGNameLists"] !== null) {
            $this->CFGNameLists = [];
            foreach ($param["CFGNameLists"] as $key => $value){
                $obj = new FilterDataObject();
                $obj->deserialize($value);
                array_push($this->CFGNameLists, $obj);
            }
        }

        if (array_key_exists("CheckTypeLists",$param) and $param["CheckTypeLists"] !== null) {
            $this->CheckTypeLists = [];
            foreach ($param["CheckTypeLists"] as $key => $value){
                $obj = new FilterDataObject();
                $obj->deserialize($value);
                array_push($this->CheckTypeLists, $obj);
            }
        }

        if (array_key_exists("InstanceTypeLists",$param) and $param["InstanceTypeLists"] !== null) {
            $this->InstanceTypeLists = [];
            foreach ($param["InstanceTypeLists"] as $key => $value){
                $obj = new FilterDataObject();
                $obj->deserialize($value);
                array_push($this->InstanceTypeLists, $obj);
            }
        }

        if (array_key_exists("FromLists",$param) and $param["FromLists"] !== null) {
            $this->FromLists = [];
            foreach ($param["FromLists"] as $key => $value){
                $obj = new FilterDataObject();
                $obj->deserialize($value);
                array_push($this->FromLists, $obj);
            }
        }

        if (array_key_exists("RequestId",$param) and $param["RequestId"] !== null) {
            $this->RequestId = $param["RequestId"];
        }
    }
}
