<?php
/*
 * Copyright (c) 2017-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
namespace TencentCloud\Csip\V20221121\Models;
use TencentCloud\Common\AbstractModel;

/**
 * DescribeEdrAlertSummary response structure.
 *
 * @method integer getCriticalPendingCount() Obtain <p>Number of pending CRITICAL and HIGH-risk items (Level IN CRITICAL,HIGH, DB internal value 1,5)</p>
 * @method void setCriticalPendingCount(integer $CriticalPendingCount) Set <p>Number of pending CRITICAL and HIGH-risk items (Level IN CRITICAL,HIGH, DB internal value 1,5)</p>
 * @method integer getTotalPendingCount() Obtain <p>Total number of pending items</p>
 * @method void setTotalPendingCount(integer $TotalPendingCount) Set <p>Total number of pending items</p>
 * @method string getRequestId() Obtain The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
 * @method void setRequestId(string $RequestId) Set The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
 */
class DescribeEdrAlertSummaryResponse extends AbstractModel
{
    /**
     * @var integer <p>Number of pending CRITICAL and HIGH-risk items (Level IN CRITICAL,HIGH, DB internal value 1,5)</p>
     */
    public $CriticalPendingCount;

    /**
     * @var integer <p>Total number of pending items</p>
     */
    public $TotalPendingCount;

    /**
     * @var string The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    public $RequestId;

    /**
     * @param integer $CriticalPendingCount <p>Number of pending CRITICAL and HIGH-risk items (Level IN CRITICAL,HIGH, DB internal value 1,5)</p>
     * @param integer $TotalPendingCount <p>Total number of pending items</p>
     * @param string $RequestId The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    function __construct()
    {

    }

    /**
     * For internal only. DO NOT USE IT.
     */
    public function deserialize($param)
    {
        if ($param === null) {
            return;
        }
        if (array_key_exists("CriticalPendingCount",$param) and $param["CriticalPendingCount"] !== null) {
            $this->CriticalPendingCount = $param["CriticalPendingCount"];
        }

        if (array_key_exists("TotalPendingCount",$param) and $param["TotalPendingCount"] !== null) {
            $this->TotalPendingCount = $param["TotalPendingCount"];
        }

        if (array_key_exists("RequestId",$param) and $param["RequestId"] !== null) {
            $this->RequestId = $param["RequestId"];
        }
    }
}
