<?php
/*
 * Copyright (c) 2017-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
namespace TencentCloud\Csip\V20221121\Models;
use TencentCloud\Common\AbstractModel;

/**
 * DescribeAlertList response structure.
 *
 * @method array getAlertList() Obtain All Alarm List
 * @method void setAlertList(array $AlertList) Set All Alarm List
 * @method array getAlertTypeCount() Obtain Number of major alarm categories
 * @method void setAlertTypeCount(array $AlertTypeCount) Set Number of major alarm categories
 * @method integer getTotalCount() Obtain Total number of alarms
 * @method void setTotalCount(integer $TotalCount) Set Total number of alarms
 * @method integer getReturnCode() Obtain 0:succeed 1:timeout
 * @method void setReturnCode(integer $ReturnCode) Set 0:succeed 1:timeout
 * @method string getReturnMsg() Obtain Returned status information.
 * @method void setReturnMsg(string $ReturnMsg) Set Returned status information.
 * @method string getRequestId() Obtain The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
 * @method void setRequestId(string $RequestId) Set The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
 */
class DescribeAlertListResponse extends AbstractModel
{
    /**
     * @var array All Alarm List
     */
    public $AlertList;

    /**
     * @var array Number of major alarm categories
     */
    public $AlertTypeCount;

    /**
     * @var integer Total number of alarms
     */
    public $TotalCount;

    /**
     * @var integer 0:succeed 1:timeout
     */
    public $ReturnCode;

    /**
     * @var string Returned status information.
     */
    public $ReturnMsg;

    /**
     * @var string The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    public $RequestId;

    /**
     * @param array $AlertList All Alarm List
     * @param array $AlertTypeCount Number of major alarm categories
     * @param integer $TotalCount Total number of alarms
     * @param integer $ReturnCode 0:succeed 1:timeout
     * @param string $ReturnMsg Returned status information.
     * @param string $RequestId The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    function __construct()
    {

    }

    /**
     * For internal only. DO NOT USE IT.
     */
    public function deserialize($param)
    {
        if ($param === null) {
            return;
        }
        if (array_key_exists("AlertList",$param) and $param["AlertList"] !== null) {
            $this->AlertList = [];
            foreach ($param["AlertList"] as $key => $value){
                $obj = new AlertInfo();
                $obj->deserialize($value);
                array_push($this->AlertList, $obj);
            }
        }

        if (array_key_exists("AlertTypeCount",$param) and $param["AlertTypeCount"] !== null) {
            $this->AlertTypeCount = [];
            foreach ($param["AlertTypeCount"] as $key => $value){
                $obj = new TagCount();
                $obj->deserialize($value);
                array_push($this->AlertTypeCount, $obj);
            }
        }

        if (array_key_exists("TotalCount",$param) and $param["TotalCount"] !== null) {
            $this->TotalCount = $param["TotalCount"];
        }

        if (array_key_exists("ReturnCode",$param) and $param["ReturnCode"] !== null) {
            $this->ReturnCode = $param["ReturnCode"];
        }

        if (array_key_exists("ReturnMsg",$param) and $param["ReturnMsg"] !== null) {
            $this->ReturnMsg = $param["ReturnMsg"];
        }

        if (array_key_exists("RequestId",$param) and $param["RequestId"] !== null) {
            $this->RequestId = $param["RequestId"];
        }
    }
}
