<?php
/*
 * Copyright (c) 2017-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
namespace TencentCloud\Csip\V20221121\Models;
use TencentCloud\Common\AbstractModel;

/**
 * DescribeAccessKeyAlarmDetail response structure.
 *
 * @method AccessKeyAlarm getAlarmInfo() Obtain Alarm information.
 * @method void setAlarmInfo(AccessKeyAlarm $AlarmInfo) Set Alarm information.
 * @method integer getCamCount() Obtain Number of CAM policies in the associated account.
 * @method void setCamCount(integer $CamCount) Set Number of CAM policies in the associated account.
 * @method integer getRiskCount() Obtain Number of AK risks.
 * @method void setRiskCount(integer $RiskCount) Set Number of AK risks.
 * @method string getAlarmDesc() Obtain Alarm policy description.
 * @method void setAlarmDesc(string $AlarmDesc) Set Alarm policy description.
 * @method string getRequestId() Obtain The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
 * @method void setRequestId(string $RequestId) Set The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
 */
class DescribeAccessKeyAlarmDetailResponse extends AbstractModel
{
    /**
     * @var AccessKeyAlarm Alarm information.
     */
    public $AlarmInfo;

    /**
     * @var integer Number of CAM policies in the associated account.
     */
    public $CamCount;

    /**
     * @var integer Number of AK risks.
     */
    public $RiskCount;

    /**
     * @var string Alarm policy description.
     */
    public $AlarmDesc;

    /**
     * @var string The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    public $RequestId;

    /**
     * @param AccessKeyAlarm $AlarmInfo Alarm information.
     * @param integer $CamCount Number of CAM policies in the associated account.
     * @param integer $RiskCount Number of AK risks.
     * @param string $AlarmDesc Alarm policy description.
     * @param string $RequestId The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    function __construct()
    {

    }

    /**
     * For internal only. DO NOT USE IT.
     */
    public function deserialize($param)
    {
        if ($param === null) {
            return;
        }
        if (array_key_exists("AlarmInfo",$param) and $param["AlarmInfo"] !== null) {
            $this->AlarmInfo = new AccessKeyAlarm();
            $this->AlarmInfo->deserialize($param["AlarmInfo"]);
        }

        if (array_key_exists("CamCount",$param) and $param["CamCount"] !== null) {
            $this->CamCount = $param["CamCount"];
        }

        if (array_key_exists("RiskCount",$param) and $param["RiskCount"] !== null) {
            $this->RiskCount = $param["RiskCount"];
        }

        if (array_key_exists("AlarmDesc",$param) and $param["AlarmDesc"] !== null) {
            $this->AlarmDesc = $param["AlarmDesc"];
        }

        if (array_key_exists("RequestId",$param) and $param["RequestId"] !== null) {
            $this->RequestId = $param["RequestId"];
        }
    }
}
