<?php
/*
 * Copyright (c) 2017-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
namespace TencentCloud\Csip\V20221121\Models;
use TencentCloud\Common\AbstractModel;

/**
 * DescribeDomainAssets response structure.
 *
 * @method integer getTotal() Obtain Total number.
 * @method void setTotal(integer $Total) Set Total number.
 * @method array getData() Obtain Domain name list
 * @method void setData(array $Data) Set Domain name list
 * @method array getDefenseStatusList() Obtain Protection Status List
 * @method void setDefenseStatusList(array $DefenseStatusList) Set Protection Status List
 * @method array getAssetLocationList() Obtain Asset Attribution List
 * @method void setAssetLocationList(array $AssetLocationList) Set Asset Attribution List
 * @method array getSourceTypeList() Obtain Asset Type List
 * @method void setSourceTypeList(array $SourceTypeList) Set Asset Type List
 * @method array getRegionList() Obtain Region list
 * @method void setRegionList(array $RegionList) Set Region list
 * @method string getRequestId() Obtain The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
 * @method void setRequestId(string $RequestId) Set The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
 */
class DescribeDomainAssetsResponse extends AbstractModel
{
    /**
     * @var integer Total number.
     */
    public $Total;

    /**
     * @var array Domain name list
     */
    public $Data;

    /**
     * @var array Protection Status List
     */
    public $DefenseStatusList;

    /**
     * @var array Asset Attribution List
     */
    public $AssetLocationList;

    /**
     * @var array Asset Type List
     */
    public $SourceTypeList;

    /**
     * @var array Region list
     */
    public $RegionList;

    /**
     * @var string The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    public $RequestId;

    /**
     * @param integer $Total Total number.
     * @param array $Data Domain name list
     * @param array $DefenseStatusList Protection Status List
     * @param array $AssetLocationList Asset Attribution List
     * @param array $SourceTypeList Asset Type List
     * @param array $RegionList Region list
     * @param string $RequestId The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    function __construct()
    {

    }

    /**
     * For internal only. DO NOT USE IT.
     */
    public function deserialize($param)
    {
        if ($param === null) {
            return;
        }
        if (array_key_exists("Total",$param) and $param["Total"] !== null) {
            $this->Total = $param["Total"];
        }

        if (array_key_exists("Data",$param) and $param["Data"] !== null) {
            $this->Data = [];
            foreach ($param["Data"] as $key => $value){
                $obj = new DomainAssetVO();
                $obj->deserialize($value);
                array_push($this->Data, $obj);
            }
        }

        if (array_key_exists("DefenseStatusList",$param) and $param["DefenseStatusList"] !== null) {
            $this->DefenseStatusList = [];
            foreach ($param["DefenseStatusList"] as $key => $value){
                $obj = new FilterDataObject();
                $obj->deserialize($value);
                array_push($this->DefenseStatusList, $obj);
            }
        }

        if (array_key_exists("AssetLocationList",$param) and $param["AssetLocationList"] !== null) {
            $this->AssetLocationList = [];
            foreach ($param["AssetLocationList"] as $key => $value){
                $obj = new FilterDataObject();
                $obj->deserialize($value);
                array_push($this->AssetLocationList, $obj);
            }
        }

        if (array_key_exists("SourceTypeList",$param) and $param["SourceTypeList"] !== null) {
            $this->SourceTypeList = [];
            foreach ($param["SourceTypeList"] as $key => $value){
                $obj = new FilterDataObject();
                $obj->deserialize($value);
                array_push($this->SourceTypeList, $obj);
            }
        }

        if (array_key_exists("RegionList",$param) and $param["RegionList"] !== null) {
            $this->RegionList = [];
            foreach ($param["RegionList"] as $key => $value){
                $obj = new FilterDataObject();
                $obj->deserialize($value);
                array_push($this->RegionList, $obj);
            }
        }

        if (array_key_exists("RequestId",$param) and $param["RequestId"] !== null) {
            $this->RequestId = $param["RequestId"];
        }
    }
}
