<?php
/*
 * Copyright (c) 2017-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
namespace TencentCloud\Csip\V20221121\Models;
use TencentCloud\Common\AbstractModel;

/**
 * DescribeKeySandboxCredential response structure.
 *
 * @method string getCredentialId() Obtain Credential ID
 * @method void setCredentialId(string $CredentialId) Set Credential ID
 * @method string getCredentialName() Obtain Credential name
 * @method void setCredentialName(string $CredentialName) Set Credential name
 * @method string getCredentialType() Obtain Credential Type
Enumeration value:
access: standard key
sts: STS temporary key
 * @method void setCredentialType(string $CredentialType) Set Credential Type
Enumeration value:
access: standard key
sts: STS temporary key
 * @method CredentialEffectScope getCredentialEffectScope() Obtain Effective machine scope
 * @method void setCredentialEffectScope(CredentialEffectScope $CredentialEffectScope) Set Effective machine scope
 * @method array getAccess() Obtain Normal key credential data (masked). Returned when CredentialType is access.
Supplementary explanation: Key is the original text, and Value is the masked value (reserve the first 3 and last 4 digits, with *** as substitution in the middle).
Note: This field may return null, indicating that no valid values can be obtained.
 * @method void setAccess(array $Access) Set Normal key credential data (masked). Returned when CredentialType is access.
Supplementary explanation: Key is the original text, and Value is the masked value (reserve the first 3 and last 4 digits, with *** as substitution in the middle).
Note: This field may return null, indicating that no valid values can be obtained.
 * @method STSCredentialOutput getSTS() Obtain STS credential data (masked). Returned when CredentialType is sts.
Supplementary description: System is the original text, SecretID and SecretKey are masked values (reserve the first 3 and last 4 characters, with *** as substitution in the middle).
Note: This field may return null, indicating that no valid values can be obtained.
 * @method void setSTS(STSCredentialOutput $STS) Set STS credential data (masked). Returned when CredentialType is sts.
Supplementary description: System is the original text, SecretID and SecretKey are masked values (reserve the first 3 and last 4 characters, with *** as substitution in the middle).
Note: This field may return null, indicating that no valid values can be obtained.
 * @method string getCreateTime() Obtain Creation time.
Parameter format: YYYY-MM-DDTHH:mm:ssZ (ISO8601 format).
 * @method void setCreateTime(string $CreateTime) Set Creation time.
Parameter format: YYYY-MM-DDTHH:mm:ssZ (ISO8601 format).
 * @method string getUpdateTime() Obtain Update time
Parameter format: YYYY-MM-DDTHH:mm:ssZ (ISO8601 format).
 * @method void setUpdateTime(string $UpdateTime) Set Update time
Parameter format: YYYY-MM-DDTHH:mm:ssZ (ISO8601 format).
 * @method string getRequestId() Obtain The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
 * @method void setRequestId(string $RequestId) Set The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
 */
class DescribeKeySandboxCredentialResponse extends AbstractModel
{
    /**
     * @var string Credential ID
     */
    public $CredentialId;

    /**
     * @var string Credential name
     */
    public $CredentialName;

    /**
     * @var string Credential Type
Enumeration value:
access: standard key
sts: STS temporary key
     */
    public $CredentialType;

    /**
     * @var CredentialEffectScope Effective machine scope
     */
    public $CredentialEffectScope;

    /**
     * @var array Normal key credential data (masked). Returned when CredentialType is access.
Supplementary explanation: Key is the original text, and Value is the masked value (reserve the first 3 and last 4 digits, with *** as substitution in the middle).
Note: This field may return null, indicating that no valid values can be obtained.
     */
    public $Access;

    /**
     * @var STSCredentialOutput STS credential data (masked). Returned when CredentialType is sts.
Supplementary description: System is the original text, SecretID and SecretKey are masked values (reserve the first 3 and last 4 characters, with *** as substitution in the middle).
Note: This field may return null, indicating that no valid values can be obtained.
     */
    public $STS;

    /**
     * @var string Creation time.
Parameter format: YYYY-MM-DDTHH:mm:ssZ (ISO8601 format).
     */
    public $CreateTime;

    /**
     * @var string Update time
Parameter format: YYYY-MM-DDTHH:mm:ssZ (ISO8601 format).
     */
    public $UpdateTime;

    /**
     * @var string The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    public $RequestId;

    /**
     * @param string $CredentialId Credential ID
     * @param string $CredentialName Credential name
     * @param string $CredentialType Credential Type
Enumeration value:
access: standard key
sts: STS temporary key
     * @param CredentialEffectScope $CredentialEffectScope Effective machine scope
     * @param array $Access Normal key credential data (masked). Returned when CredentialType is access.
Supplementary explanation: Key is the original text, and Value is the masked value (reserve the first 3 and last 4 digits, with *** as substitution in the middle).
Note: This field may return null, indicating that no valid values can be obtained.
     * @param STSCredentialOutput $STS STS credential data (masked). Returned when CredentialType is sts.
Supplementary description: System is the original text, SecretID and SecretKey are masked values (reserve the first 3 and last 4 characters, with *** as substitution in the middle).
Note: This field may return null, indicating that no valid values can be obtained.
     * @param string $CreateTime Creation time.
Parameter format: YYYY-MM-DDTHH:mm:ssZ (ISO8601 format).
     * @param string $UpdateTime Update time
Parameter format: YYYY-MM-DDTHH:mm:ssZ (ISO8601 format).
     * @param string $RequestId The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    function __construct()
    {

    }

    /**
     * For internal only. DO NOT USE IT.
     */
    public function deserialize($param)
    {
        if ($param === null) {
            return;
        }
        if (array_key_exists("CredentialId",$param) and $param["CredentialId"] !== null) {
            $this->CredentialId = $param["CredentialId"];
        }

        if (array_key_exists("CredentialName",$param) and $param["CredentialName"] !== null) {
            $this->CredentialName = $param["CredentialName"];
        }

        if (array_key_exists("CredentialType",$param) and $param["CredentialType"] !== null) {
            $this->CredentialType = $param["CredentialType"];
        }

        if (array_key_exists("CredentialEffectScope",$param) and $param["CredentialEffectScope"] !== null) {
            $this->CredentialEffectScope = new CredentialEffectScope();
            $this->CredentialEffectScope->deserialize($param["CredentialEffectScope"]);
        }

        if (array_key_exists("Access",$param) and $param["Access"] !== null) {
            $this->Access = [];
            foreach ($param["Access"] as $key => $value){
                $obj = new AccessCredentialOutput();
                $obj->deserialize($value);
                array_push($this->Access, $obj);
            }
        }

        if (array_key_exists("STS",$param) and $param["STS"] !== null) {
            $this->STS = new STSCredentialOutput();
            $this->STS->deserialize($param["STS"]);
        }

        if (array_key_exists("CreateTime",$param) and $param["CreateTime"] !== null) {
            $this->CreateTime = $param["CreateTime"];
        }

        if (array_key_exists("UpdateTime",$param) and $param["UpdateTime"] !== null) {
            $this->UpdateTime = $param["UpdateTime"];
        }

        if (array_key_exists("RequestId",$param) and $param["RequestId"] !== null) {
            $this->RequestId = $param["RequestId"];
        }
    }
}
