<?php
/*
 * Copyright (c) 2017-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
namespace TencentCloud\Csip\V20221121\Models;
use TencentCloud\Common\AbstractModel;

/**
 * DescribeDspmBackupLogList response structure.
 *
 * @method integer getTotalCount() Obtain <p>How many are there in total</p>
 * @method void setTotalCount(integer $TotalCount) Set <p>How many are there in total</p>
 * @method array getList() Obtain <p>Backup log list.</p>
 * @method void setList(array $List) Set <p>Backup log list.</p>
 * @method boolean getHasRestoringTask() Obtain <p>Whether recovery tasks currently exist</p>
 * @method void setHasRestoringTask(boolean $HasRestoringTask) Set <p>Whether recovery tasks currently exist</p>
 * @method integer getMaxRestoreSizeInGB() Obtain <p>Maximum recovery space</p>
 * @method void setMaxRestoreSizeInGB(integer $MaxRestoreSizeInGB) Set <p>Maximum recovery space</p>
 * @method string getRequestId() Obtain The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
 * @method void setRequestId(string $RequestId) Set The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
 */
class DescribeDspmBackupLogListResponse extends AbstractModel
{
    /**
     * @var integer <p>How many are there in total</p>
     */
    public $TotalCount;

    /**
     * @var array <p>Backup log list.</p>
     */
    public $List;

    /**
     * @var boolean <p>Whether recovery tasks currently exist</p>
     */
    public $HasRestoringTask;

    /**
     * @var integer <p>Maximum recovery space</p>
     */
    public $MaxRestoreSizeInGB;

    /**
     * @var string The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    public $RequestId;

    /**
     * @param integer $TotalCount <p>How many are there in total</p>
     * @param array $List <p>Backup log list.</p>
     * @param boolean $HasRestoringTask <p>Whether recovery tasks currently exist</p>
     * @param integer $MaxRestoreSizeInGB <p>Maximum recovery space</p>
     * @param string $RequestId The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    function __construct()
    {

    }

    /**
     * For internal only. DO NOT USE IT.
     */
    public function deserialize($param)
    {
        if ($param === null) {
            return;
        }
        if (array_key_exists("TotalCount",$param) and $param["TotalCount"] !== null) {
            $this->TotalCount = $param["TotalCount"];
        }

        if (array_key_exists("List",$param) and $param["List"] !== null) {
            $this->List = [];
            foreach ($param["List"] as $key => $value){
                $obj = new BackupLog();
                $obj->deserialize($value);
                array_push($this->List, $obj);
            }
        }

        if (array_key_exists("HasRestoringTask",$param) and $param["HasRestoringTask"] !== null) {
            $this->HasRestoringTask = $param["HasRestoringTask"];
        }

        if (array_key_exists("MaxRestoreSizeInGB",$param) and $param["MaxRestoreSizeInGB"] !== null) {
            $this->MaxRestoreSizeInGB = $param["MaxRestoreSizeInGB"];
        }

        if (array_key_exists("RequestId",$param) and $param["RequestId"] !== null) {
            $this->RequestId = $param["RequestId"];
        }
    }
}
