<?php
/*
 * Copyright (c) 2017-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
namespace TencentCloud\Csip\V20221121\Models;
use TencentCloud\Common\AbstractModel;

/**
 * DescribeClusterDetail response structure.
 *
 * @method ClusterListItem getClusterBaseInfo() Obtain <p>Cluster basic information</p>
 * @method void setClusterBaseInfo(ClusterListItem $ClusterBaseInfo) Set <p>Cluster basic information</p>
 * @method string getRuntimeComponent() Obtain <p>Runtime component.</p>
 * @method void setRuntimeComponent(string $RuntimeComponent) Set <p>Runtime component.</p>
 * @method string getMasterIP() Obtain <p>master ip</p>
 * @method void setMasterIP(string $MasterIP) Set <p>master ip</p>
 * @method integer getNodeCount() Obtain <p>Number of nodes</p>
 * @method void setNodeCount(integer $NodeCount) Set <p>Number of nodes</p>
 * @method integer getNamespaceCount() Obtain <p>Number of namespaces</p>
 * @method void setNamespaceCount(integer $NamespaceCount) Set <p>Number of namespaces</p>
 * @method integer getPodCount() Obtain <p>Number of pods</p>
 * @method void setPodCount(integer $PodCount) Set <p>Number of pods</p>
 * @method integer getContainerCount() Obtain <p>Number of containers</p>
 * @method void setContainerCount(integer $ContainerCount) Set <p>Number of containers</p>
 * @method integer getServiceCount() Obtain <p>Number of services</p>
 * @method void setServiceCount(integer $ServiceCount) Set <p>Number of services</p>
 * @method integer getIngressCount() Obtain <p>Number of ingresses</p>
 * @method void setIngressCount(integer $IngressCount) Set <p>Number of ingresses</p>
 * @method integer getImageCount() Obtain <p>Number of images.</p>
 * @method void setImageCount(integer $ImageCount) Set <p>Number of images.</p>
 * @method integer getSystemComponentCount() Obtain <p>Number of system components</p>
 * @method void setSystemComponentCount(integer $SystemComponentCount) Set <p>Number of system components</p>
 * @method string getRequestId() Obtain The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
 * @method void setRequestId(string $RequestId) Set The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
 */
class DescribeClusterDetailResponse extends AbstractModel
{
    /**
     * @var ClusterListItem <p>Cluster basic information</p>
     */
    public $ClusterBaseInfo;

    /**
     * @var string <p>Runtime component.</p>
     */
    public $RuntimeComponent;

    /**
     * @var string <p>master ip</p>
     */
    public $MasterIP;

    /**
     * @var integer <p>Number of nodes</p>
     */
    public $NodeCount;

    /**
     * @var integer <p>Number of namespaces</p>
     */
    public $NamespaceCount;

    /**
     * @var integer <p>Number of pods</p>
     */
    public $PodCount;

    /**
     * @var integer <p>Number of containers</p>
     */
    public $ContainerCount;

    /**
     * @var integer <p>Number of services</p>
     */
    public $ServiceCount;

    /**
     * @var integer <p>Number of ingresses</p>
     */
    public $IngressCount;

    /**
     * @var integer <p>Number of images.</p>
     */
    public $ImageCount;

    /**
     * @var integer <p>Number of system components</p>
     */
    public $SystemComponentCount;

    /**
     * @var string The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    public $RequestId;

    /**
     * @param ClusterListItem $ClusterBaseInfo <p>Cluster basic information</p>
     * @param string $RuntimeComponent <p>Runtime component.</p>
     * @param string $MasterIP <p>master ip</p>
     * @param integer $NodeCount <p>Number of nodes</p>
     * @param integer $NamespaceCount <p>Number of namespaces</p>
     * @param integer $PodCount <p>Number of pods</p>
     * @param integer $ContainerCount <p>Number of containers</p>
     * @param integer $ServiceCount <p>Number of services</p>
     * @param integer $IngressCount <p>Number of ingresses</p>
     * @param integer $ImageCount <p>Number of images.</p>
     * @param integer $SystemComponentCount <p>Number of system components</p>
     * @param string $RequestId The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    function __construct()
    {

    }

    /**
     * For internal only. DO NOT USE IT.
     */
    public function deserialize($param)
    {
        if ($param === null) {
            return;
        }
        if (array_key_exists("ClusterBaseInfo",$param) and $param["ClusterBaseInfo"] !== null) {
            $this->ClusterBaseInfo = new ClusterListItem();
            $this->ClusterBaseInfo->deserialize($param["ClusterBaseInfo"]);
        }

        if (array_key_exists("RuntimeComponent",$param) and $param["RuntimeComponent"] !== null) {
            $this->RuntimeComponent = $param["RuntimeComponent"];
        }

        if (array_key_exists("MasterIP",$param) and $param["MasterIP"] !== null) {
            $this->MasterIP = $param["MasterIP"];
        }

        if (array_key_exists("NodeCount",$param) and $param["NodeCount"] !== null) {
            $this->NodeCount = $param["NodeCount"];
        }

        if (array_key_exists("NamespaceCount",$param) and $param["NamespaceCount"] !== null) {
            $this->NamespaceCount = $param["NamespaceCount"];
        }

        if (array_key_exists("PodCount",$param) and $param["PodCount"] !== null) {
            $this->PodCount = $param["PodCount"];
        }

        if (array_key_exists("ContainerCount",$param) and $param["ContainerCount"] !== null) {
            $this->ContainerCount = $param["ContainerCount"];
        }

        if (array_key_exists("ServiceCount",$param) and $param["ServiceCount"] !== null) {
            $this->ServiceCount = $param["ServiceCount"];
        }

        if (array_key_exists("IngressCount",$param) and $param["IngressCount"] !== null) {
            $this->IngressCount = $param["IngressCount"];
        }

        if (array_key_exists("ImageCount",$param) and $param["ImageCount"] !== null) {
            $this->ImageCount = $param["ImageCount"];
        }

        if (array_key_exists("SystemComponentCount",$param) and $param["SystemComponentCount"] !== null) {
            $this->SystemComponentCount = $param["SystemComponentCount"];
        }

        if (array_key_exists("RequestId",$param) and $param["RequestId"] !== null) {
            $this->RequestId = $param["RequestId"];
        }
    }
}
