<?php
/*
 * Copyright (c) 2017-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
namespace TencentCloud\Csip\V20221121\Models;
use TencentCloud\Common\AbstractModel;

/**
 * DescribeCspmShardConfig response structure.
 *
 * @method integer getShardFromAppID() Obtain <p>Shared quota source appid</p>
 * @method void setShardFromAppID(integer $ShardFromAppID) Set <p>Shared quota source appid</p>
 * @method integer getAutoShardStatus() Obtain <p>Automatic sharing toggle status</p>
 * @method void setAutoShardStatus(integer $AutoShardStatus) Set <p>Automatic sharing toggle status</p>
 * @method array getShardAppIDs() Obtain <p>List of target appids for which quota has been shared</p>
 * @method void setShardAppIDs(array $ShardAppIDs) Set <p>List of target appids for which quota has been shared</p>
 * @method string getRequestId() Obtain The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
 * @method void setRequestId(string $RequestId) Set The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
 */
class DescribeCspmShardConfigResponse extends AbstractModel
{
    /**
     * @var integer <p>Shared quota source appid</p>
     */
    public $ShardFromAppID;

    /**
     * @var integer <p>Automatic sharing toggle status</p>
     */
    public $AutoShardStatus;

    /**
     * @var array <p>List of target appids for which quota has been shared</p>
     */
    public $ShardAppIDs;

    /**
     * @var string The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    public $RequestId;

    /**
     * @param integer $ShardFromAppID <p>Shared quota source appid</p>
     * @param integer $AutoShardStatus <p>Automatic sharing toggle status</p>
     * @param array $ShardAppIDs <p>List of target appids for which quota has been shared</p>
     * @param string $RequestId The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    function __construct()
    {

    }

    /**
     * For internal only. DO NOT USE IT.
     */
    public function deserialize($param)
    {
        if ($param === null) {
            return;
        }
        if (array_key_exists("ShardFromAppID",$param) and $param["ShardFromAppID"] !== null) {
            $this->ShardFromAppID = $param["ShardFromAppID"];
        }

        if (array_key_exists("AutoShardStatus",$param) and $param["AutoShardStatus"] !== null) {
            $this->AutoShardStatus = $param["AutoShardStatus"];
        }

        if (array_key_exists("ShardAppIDs",$param) and $param["ShardAppIDs"] !== null) {
            $this->ShardAppIDs = $param["ShardAppIDs"];
        }

        if (array_key_exists("RequestId",$param) and $param["RequestId"] !== null) {
            $this->RequestId = $param["RequestId"];
        }
    }
}
