<?php
/*
 * Copyright (c) 2017-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
namespace TencentCloud\Csip\V20221121\Models;
use TencentCloud\Common\AbstractModel;

/**
 * DescribeDspmAssetLoginCredential response structure.
 *
 * @method string getAccount() Obtain Account
 * @method void setAccount(string $Account) Set Account
 * @method string getPassword() Obtain Password information.
 * @method void setPassword(string $Password) Set Password information.
 * @method string getValidateStart() Obtain Validity start time
 * @method void setValidateStart(string $ValidateStart) Set Validity start time
 * @method string getValidateEnd() Obtain Validity end time
 * @method void setValidateEnd(string $ValidateEnd) Set Validity end time
 * @method string getRequestId() Obtain The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
 * @method void setRequestId(string $RequestId) Set The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
 */
class DescribeDspmAssetLoginCredentialResponse extends AbstractModel
{
    /**
     * @var string Account
     */
    public $Account;

    /**
     * @var string Password information.
     */
    public $Password;

    /**
     * @var string Validity start time
     */
    public $ValidateStart;

    /**
     * @var string Validity end time
     */
    public $ValidateEnd;

    /**
     * @var string The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    public $RequestId;

    /**
     * @param string $Account Account
     * @param string $Password Password information.
     * @param string $ValidateStart Validity start time
     * @param string $ValidateEnd Validity end time
     * @param string $RequestId The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    function __construct()
    {

    }

    /**
     * For internal only. DO NOT USE IT.
     */
    public function deserialize($param)
    {
        if ($param === null) {
            return;
        }
        if (array_key_exists("Account",$param) and $param["Account"] !== null) {
            $this->Account = $param["Account"];
        }

        if (array_key_exists("Password",$param) and $param["Password"] !== null) {
            $this->Password = $param["Password"];
        }

        if (array_key_exists("ValidateStart",$param) and $param["ValidateStart"] !== null) {
            $this->ValidateStart = $param["ValidateStart"];
        }

        if (array_key_exists("ValidateEnd",$param) and $param["ValidateEnd"] !== null) {
            $this->ValidateEnd = $param["ValidateEnd"];
        }

        if (array_key_exists("RequestId",$param) and $param["RequestId"] !== null) {
            $this->RequestId = $param["RequestId"];
        }
    }
}
