<?php
/*
 * Copyright (c) 2017-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
namespace TencentCloud\Csip\V20221121\Models;
use TencentCloud\Common\AbstractModel;

/**
 * DescribeRiskDetailList response structure.
 *
 * @method integer getTotalCount() Obtain Risk detail count from asset perspective
 * @method void setTotalCount(integer $TotalCount) Set Risk detail count from asset perspective
 * @method array getAssetRiskDetailList() Obtain Risk detail list from asset perspective
 * @method void setAssetRiskDetailList(array $AssetRiskDetailList) Set Risk detail list from asset perspective
 * @method string getRequestId() Obtain The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
 * @method void setRequestId(string $RequestId) Set The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
 */
class DescribeRiskDetailListResponse extends AbstractModel
{
    /**
     * @var integer Risk detail count from asset perspective
     */
    public $TotalCount;

    /**
     * @var array Risk detail list from asset perspective
     */
    public $AssetRiskDetailList;

    /**
     * @var string The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    public $RequestId;

    /**
     * @param integer $TotalCount Risk detail count from asset perspective
     * @param array $AssetRiskDetailList Risk detail list from asset perspective
     * @param string $RequestId The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    function __construct()
    {

    }

    /**
     * For internal only. DO NOT USE IT.
     */
    public function deserialize($param)
    {
        if ($param === null) {
            return;
        }
        if (array_key_exists("TotalCount",$param) and $param["TotalCount"] !== null) {
            $this->TotalCount = $param["TotalCount"];
        }

        if (array_key_exists("AssetRiskDetailList",$param) and $param["AssetRiskDetailList"] !== null) {
            $this->AssetRiskDetailList = [];
            foreach ($param["AssetRiskDetailList"] as $key => $value){
                $obj = new RiskDetailItem();
                $obj->deserialize($value);
                array_push($this->AssetRiskDetailList, $obj);
            }
        }

        if (array_key_exists("RequestId",$param) and $param["RequestId"] !== null) {
            $this->RequestId = $param["RequestId"];
        }
    }
}
