<?php
/*
 * Copyright (c) 2017-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
namespace TencentCloud\Csip\V20221121\Models;
use TencentCloud\Common\AbstractModel;

/**
 * DescribeVulFixedHostDetail response structure.
 *
 * @method string getVulName() Obtain <p>Vulnerability name</p>
 * @method void setVulName(string $VulName) Set <p>Vulnerability name</p>
 * @method string getCveId() Obtain <p>CVE id</p>
 * @method void setCveId(string $CveId) Set <p>CVE id</p>
 * @method string getVulCategory() Obtain <p>Vulnerability type<br>Enumeration value:<br>LINUX: Linux software vulnerability<br>WINDOWS: Windows system patch vulnerability<br>WEB_CMS: Web-CMS vulnerability<br>APPLICATION: Application vulnerability</p>
 * @method void setVulCategory(string $VulCategory) Set <p>Vulnerability type<br>Enumeration value:<br>LINUX: Linux software vulnerability<br>WINDOWS: Windows system patch vulnerability<br>WEB_CMS: Web-CMS vulnerability<br>APPLICATION: Application vulnerability</p>
 * @method string getFixTime() Obtain <p>Repair completion time<br>Parameter format: YYYY-MM-DDTHH:mm:ssZ (ISO8601 format)</p>
 * @method void setFixTime(string $FixTime) Set <p>Repair completion time<br>Parameter format: YYYY-MM-DDTHH:mm:ssZ (ISO8601 format)</p>
 * @method string getInstanceId() Obtain <p>Host instance ID.</p>
 * @method void setInstanceId(string $InstanceId) Set <p>Host instance ID.</p>
 * @method string getMachineName() Obtain <p>Host name.</p>
 * @method void setMachineName(string $MachineName) Set <p>Host name.</p>
 * @method string getPublicIp() Obtain <p>Public IP of the server</p>
 * @method void setPublicIp(string $PublicIp) Set <p>Public IP of the server</p>
 * @method string getPrivateIp() Obtain <p>Host private IP address</p>
 * @method void setPrivateIp(string $PrivateIp) Set <p>Host private IP address</p>
 * @method array getComponentDetails() Obtain <p>Associated component & path detail list</p>
 * @method void setComponentDetails(array $ComponentDetails) Set <p>Associated component & path detail list</p>
 * @method integer getTotalCount() Obtain <p>Total number of associated components & paths</p>
 * @method void setTotalCount(integer $TotalCount) Set <p>Total number of associated components & paths</p>
 * @method string getRequestId() Obtain The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
 * @method void setRequestId(string $RequestId) Set The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
 */
class DescribeVulFixedHostDetailResponse extends AbstractModel
{
    /**
     * @var string <p>Vulnerability name</p>
     */
    public $VulName;

    /**
     * @var string <p>CVE id</p>
     */
    public $CveId;

    /**
     * @var string <p>Vulnerability type<br>Enumeration value:<br>LINUX: Linux software vulnerability<br>WINDOWS: Windows system patch vulnerability<br>WEB_CMS: Web-CMS vulnerability<br>APPLICATION: Application vulnerability</p>
     */
    public $VulCategory;

    /**
     * @var string <p>Repair completion time<br>Parameter format: YYYY-MM-DDTHH:mm:ssZ (ISO8601 format)</p>
     */
    public $FixTime;

    /**
     * @var string <p>Host instance ID.</p>
     */
    public $InstanceId;

    /**
     * @var string <p>Host name.</p>
     */
    public $MachineName;

    /**
     * @var string <p>Public IP of the server</p>
     */
    public $PublicIp;

    /**
     * @var string <p>Host private IP address</p>
     */
    public $PrivateIp;

    /**
     * @var array <p>Associated component & path detail list</p>
     */
    public $ComponentDetails;

    /**
     * @var integer <p>Total number of associated components & paths</p>
     */
    public $TotalCount;

    /**
     * @var string The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    public $RequestId;

    /**
     * @param string $VulName <p>Vulnerability name</p>
     * @param string $CveId <p>CVE id</p>
     * @param string $VulCategory <p>Vulnerability type<br>Enumeration value:<br>LINUX: Linux software vulnerability<br>WINDOWS: Windows system patch vulnerability<br>WEB_CMS: Web-CMS vulnerability<br>APPLICATION: Application vulnerability</p>
     * @param string $FixTime <p>Repair completion time<br>Parameter format: YYYY-MM-DDTHH:mm:ssZ (ISO8601 format)</p>
     * @param string $InstanceId <p>Host instance ID.</p>
     * @param string $MachineName <p>Host name.</p>
     * @param string $PublicIp <p>Public IP of the server</p>
     * @param string $PrivateIp <p>Host private IP address</p>
     * @param array $ComponentDetails <p>Associated component & path detail list</p>
     * @param integer $TotalCount <p>Total number of associated components & paths</p>
     * @param string $RequestId The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    function __construct()
    {

    }

    /**
     * For internal only. DO NOT USE IT.
     */
    public function deserialize($param)
    {
        if ($param === null) {
            return;
        }
        if (array_key_exists("VulName",$param) and $param["VulName"] !== null) {
            $this->VulName = $param["VulName"];
        }

        if (array_key_exists("CveId",$param) and $param["CveId"] !== null) {
            $this->CveId = $param["CveId"];
        }

        if (array_key_exists("VulCategory",$param) and $param["VulCategory"] !== null) {
            $this->VulCategory = $param["VulCategory"];
        }

        if (array_key_exists("FixTime",$param) and $param["FixTime"] !== null) {
            $this->FixTime = $param["FixTime"];
        }

        if (array_key_exists("InstanceId",$param) and $param["InstanceId"] !== null) {
            $this->InstanceId = $param["InstanceId"];
        }

        if (array_key_exists("MachineName",$param) and $param["MachineName"] !== null) {
            $this->MachineName = $param["MachineName"];
        }

        if (array_key_exists("PublicIp",$param) and $param["PublicIp"] !== null) {
            $this->PublicIp = $param["PublicIp"];
        }

        if (array_key_exists("PrivateIp",$param) and $param["PrivateIp"] !== null) {
            $this->PrivateIp = $param["PrivateIp"];
        }

        if (array_key_exists("ComponentDetails",$param) and $param["ComponentDetails"] !== null) {
            $this->ComponentDetails = [];
            foreach ($param["ComponentDetails"] as $key => $value){
                $obj = new ComponentDetailItem();
                $obj->deserialize($value);
                array_push($this->ComponentDetails, $obj);
            }
        }

        if (array_key_exists("TotalCount",$param) and $param["TotalCount"] !== null) {
            $this->TotalCount = $param["TotalCount"];
        }

        if (array_key_exists("RequestId",$param) and $param["RequestId"] !== null) {
            $this->RequestId = $param["RequestId"];
        }
    }
}
