<?php
/*
 * Copyright (c) 2017-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
namespace TencentCloud\Csip\V20221121\Models;
use TencentCloud\Common\AbstractModel;

/**
 * DescribeUserCSPMInfoList response structure.
 *
 * @method array getList() Obtain CSPM list of an account
 * @method void setList(array $List) Set CSPM list of an account
 * @method integer getSelectedCSPMNum() Obtain Total CSPM quota of selected accounts
 * @method void setSelectedCSPMNum(integer $SelectedCSPMNum) Set Total CSPM quota of selected accounts
 * @method integer getCount() Obtain Total number of accounts
 * @method void setCount(integer $Count) Set Total number of accounts
 * @method string getRequestId() Obtain The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
 * @method void setRequestId(string $RequestId) Set The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
 */
class DescribeUserCSPMInfoListResponse extends AbstractModel
{
    /**
     * @var array CSPM list of an account
     */
    public $List;

    /**
     * @var integer Total CSPM quota of selected accounts
     */
    public $SelectedCSPMNum;

    /**
     * @var integer Total number of accounts
     */
    public $Count;

    /**
     * @var string The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    public $RequestId;

    /**
     * @param array $List CSPM list of an account
     * @param integer $SelectedCSPMNum Total CSPM quota of selected accounts
     * @param integer $Count Total number of accounts
     * @param string $RequestId The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    function __construct()
    {

    }

    /**
     * For internal only. DO NOT USE IT.
     */
    public function deserialize($param)
    {
        if ($param === null) {
            return;
        }
        if (array_key_exists("List",$param) and $param["List"] !== null) {
            $this->List = [];
            foreach ($param["List"] as $key => $value){
                $obj = new UserCSPMInfo();
                $obj->deserialize($value);
                array_push($this->List, $obj);
            }
        }

        if (array_key_exists("SelectedCSPMNum",$param) and $param["SelectedCSPMNum"] !== null) {
            $this->SelectedCSPMNum = $param["SelectedCSPMNum"];
        }

        if (array_key_exists("Count",$param) and $param["Count"] !== null) {
            $this->Count = $param["Count"];
        }

        if (array_key_exists("RequestId",$param) and $param["RequestId"] !== null) {
            $this->RequestId = $param["RequestId"];
        }
    }
}
