<?php
/*
 * Copyright (c) 2017-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
namespace TencentCloud\Csip\V20221121\Models;
use TencentCloud\Common\AbstractModel;

/**
 * DescribeSkillScanPayInfo response structure.
 *
 * @method integer getAppID() Obtain <p>AppID of the associated tenant for the order</p>
 * @method void setAppID(integer $AppID) Set <p>AppID of the associated tenant for the order</p>
 * @method integer getOrderStatus() Obtain <p>Order status<br>Enumeration value:<br>0: Not purchased<br>1: Normal<br>2: Isolated<br>6: In trial<br>7: Expired<br>8: Trial expiration</p>
 * @method void setOrderStatus(integer $OrderStatus) Set <p>Order status<br>Enumeration value:<br>0: Not purchased<br>1: Normal<br>2: Isolated<br>6: In trial<br>7: Expired<br>8: Trial expiration</p>
 * @method integer getTotalQuota() Obtain <p>Total quota</p>
 * @method void setTotalQuota(integer $TotalQuota) Set <p>Total quota</p>
 * @method integer getUsedCount() Obtain <p>Consumed quota.</p>
 * @method void setUsedCount(integer $UsedCount) Set <p>Consumed quota.</p>
 * @method integer getPayMode() Obtain <p>Payment mode<br>Enumeration value:<br>0: Postpaid<br>1: Prepaid</p>
 * @method void setPayMode(integer $PayMode) Set <p>Payment mode<br>Enumeration value:<br>0: Postpaid<br>1: Prepaid</p>
 * @method integer getAutoRenew() Obtain <p>Auto-renewal flag<br>Enumeration value:<br>0: not set<br>1: auto-renewal<br>2: no auto-renewal</p>
 * @method void setAutoRenew(integer $AutoRenew) Set <p>Auto-renewal flag<br>Enumeration value:<br>0: not set<br>1: auto-renewal<br>2: no auto-renewal</p>
 * @method string getResourceId() Obtain <p>Resource ID</p>
 * @method void setResourceId(string $ResourceId) Set <p>Resource ID</p>
 * @method integer getTimeSpan() Obtain <p>Purchase period</p>
 * @method void setTimeSpan(integer $TimeSpan) Set <p>Purchase period</p>
 * @method string getTimeUnit() Obtain <p>Duration unit</p>
 * @method void setTimeUnit(string $TimeUnit) Set <p>Duration unit</p>
 * @method string getBeginTime() Obtain <p>Order start time</p>
 * @method void setBeginTime(string $BeginTime) Set <p>Order start time</p>
 * @method string getEndTime() Obtain <p>Order expiration time</p>
 * @method void setEndTime(string $EndTime) Set <p>Order expiration time</p>
 * @method string getBetaEndTime() Obtain <p>Open beta end time is fixed as 2026-06-30 23:59:59</p>
 * @method void setBetaEndTime(string $BetaEndTime) Set <p>Open beta end time is fixed as 2026-06-30 23:59:59</p>
 * @method string getTimeNow() Obtain <p>Server current time</p>
 * @method void setTimeNow(string $TimeNow) Set <p>Server current time</p>
 * @method string getUin() Obtain <p>Tenant Uin</p>
 * @method void setUin(string $Uin) Set <p>Tenant Uin</p>
 * @method string getNickName() Obtain <p>Tenant nickname</p>
 * @method void setNickName(string $NickName) Set <p>Tenant nickname</p>
 * @method string getRequestId() Obtain The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
 * @method void setRequestId(string $RequestId) Set The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
 */
class DescribeSkillScanPayInfoResponse extends AbstractModel
{
    /**
     * @var integer <p>AppID of the associated tenant for the order</p>
     */
    public $AppID;

    /**
     * @var integer <p>Order status<br>Enumeration value:<br>0: Not purchased<br>1: Normal<br>2: Isolated<br>6: In trial<br>7: Expired<br>8: Trial expiration</p>
     */
    public $OrderStatus;

    /**
     * @var integer <p>Total quota</p>
     */
    public $TotalQuota;

    /**
     * @var integer <p>Consumed quota.</p>
     */
    public $UsedCount;

    /**
     * @var integer <p>Payment mode<br>Enumeration value:<br>0: Postpaid<br>1: Prepaid</p>
     */
    public $PayMode;

    /**
     * @var integer <p>Auto-renewal flag<br>Enumeration value:<br>0: not set<br>1: auto-renewal<br>2: no auto-renewal</p>
     */
    public $AutoRenew;

    /**
     * @var string <p>Resource ID</p>
     */
    public $ResourceId;

    /**
     * @var integer <p>Purchase period</p>
     */
    public $TimeSpan;

    /**
     * @var string <p>Duration unit</p>
     */
    public $TimeUnit;

    /**
     * @var string <p>Order start time</p>
     */
    public $BeginTime;

    /**
     * @var string <p>Order expiration time</p>
     */
    public $EndTime;

    /**
     * @var string <p>Open beta end time is fixed as 2026-06-30 23:59:59</p>
     */
    public $BetaEndTime;

    /**
     * @var string <p>Server current time</p>
     */
    public $TimeNow;

    /**
     * @var string <p>Tenant Uin</p>
     */
    public $Uin;

    /**
     * @var string <p>Tenant nickname</p>
     */
    public $NickName;

    /**
     * @var string The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    public $RequestId;

    /**
     * @param integer $AppID <p>AppID of the associated tenant for the order</p>
     * @param integer $OrderStatus <p>Order status<br>Enumeration value:<br>0: Not purchased<br>1: Normal<br>2: Isolated<br>6: In trial<br>7: Expired<br>8: Trial expiration</p>
     * @param integer $TotalQuota <p>Total quota</p>
     * @param integer $UsedCount <p>Consumed quota.</p>
     * @param integer $PayMode <p>Payment mode<br>Enumeration value:<br>0: Postpaid<br>1: Prepaid</p>
     * @param integer $AutoRenew <p>Auto-renewal flag<br>Enumeration value:<br>0: not set<br>1: auto-renewal<br>2: no auto-renewal</p>
     * @param string $ResourceId <p>Resource ID</p>
     * @param integer $TimeSpan <p>Purchase period</p>
     * @param string $TimeUnit <p>Duration unit</p>
     * @param string $BeginTime <p>Order start time</p>
     * @param string $EndTime <p>Order expiration time</p>
     * @param string $BetaEndTime <p>Open beta end time is fixed as 2026-06-30 23:59:59</p>
     * @param string $TimeNow <p>Server current time</p>
     * @param string $Uin <p>Tenant Uin</p>
     * @param string $NickName <p>Tenant nickname</p>
     * @param string $RequestId The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    function __construct()
    {

    }

    /**
     * For internal only. DO NOT USE IT.
     */
    public function deserialize($param)
    {
        if ($param === null) {
            return;
        }
        if (array_key_exists("AppID",$param) and $param["AppID"] !== null) {
            $this->AppID = $param["AppID"];
        }

        if (array_key_exists("OrderStatus",$param) and $param["OrderStatus"] !== null) {
            $this->OrderStatus = $param["OrderStatus"];
        }

        if (array_key_exists("TotalQuota",$param) and $param["TotalQuota"] !== null) {
            $this->TotalQuota = $param["TotalQuota"];
        }

        if (array_key_exists("UsedCount",$param) and $param["UsedCount"] !== null) {
            $this->UsedCount = $param["UsedCount"];
        }

        if (array_key_exists("PayMode",$param) and $param["PayMode"] !== null) {
            $this->PayMode = $param["PayMode"];
        }

        if (array_key_exists("AutoRenew",$param) and $param["AutoRenew"] !== null) {
            $this->AutoRenew = $param["AutoRenew"];
        }

        if (array_key_exists("ResourceId",$param) and $param["ResourceId"] !== null) {
            $this->ResourceId = $param["ResourceId"];
        }

        if (array_key_exists("TimeSpan",$param) and $param["TimeSpan"] !== null) {
            $this->TimeSpan = $param["TimeSpan"];
        }

        if (array_key_exists("TimeUnit",$param) and $param["TimeUnit"] !== null) {
            $this->TimeUnit = $param["TimeUnit"];
        }

        if (array_key_exists("BeginTime",$param) and $param["BeginTime"] !== null) {
            $this->BeginTime = $param["BeginTime"];
        }

        if (array_key_exists("EndTime",$param) and $param["EndTime"] !== null) {
            $this->EndTime = $param["EndTime"];
        }

        if (array_key_exists("BetaEndTime",$param) and $param["BetaEndTime"] !== null) {
            $this->BetaEndTime = $param["BetaEndTime"];
        }

        if (array_key_exists("TimeNow",$param) and $param["TimeNow"] !== null) {
            $this->TimeNow = $param["TimeNow"];
        }

        if (array_key_exists("Uin",$param) and $param["Uin"] !== null) {
            $this->Uin = $param["Uin"];
        }

        if (array_key_exists("NickName",$param) and $param["NickName"] !== null) {
            $this->NickName = $param["NickName"];
        }

        if (array_key_exists("RequestId",$param) and $param["RequestId"] !== null) {
            $this->RequestId = $param["RequestId"];
        }
    }
}
