<?php
/*
 * Copyright (c) 2017-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
namespace TencentCloud\Csip\V20221121\Models;
use TencentCloud\Common\AbstractModel;

/**
 * DescribeRegistryOverview response structure.
 *
 * @method integer getRegistryCount() Obtain <p>Total number of mirror repositories</p>
 * @method void setRegistryCount(integer $RegistryCount) Set <p>Total number of mirror repositories</p>
 * @method integer getRegistryConnectFailedCount() Obtain <p>Mirror repository connection failure count</p>
 * @method void setRegistryConnectFailedCount(integer $RegistryConnectFailedCount) Set <p>Mirror repository connection failure count</p>
 * @method array getRegistryTypeList() Obtain <p>List of image repository type counts</p>
 * @method void setRegistryTypeList(array $RegistryTypeList) Set <p>List of image repository type counts</p>
 * @method string getRequestId() Obtain The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
 * @method void setRequestId(string $RequestId) Set The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
 */
class DescribeRegistryOverviewResponse extends AbstractModel
{
    /**
     * @var integer <p>Total number of mirror repositories</p>
     */
    public $RegistryCount;

    /**
     * @var integer <p>Mirror repository connection failure count</p>
     */
    public $RegistryConnectFailedCount;

    /**
     * @var array <p>List of image repository type counts</p>
     */
    public $RegistryTypeList;

    /**
     * @var string The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    public $RequestId;

    /**
     * @param integer $RegistryCount <p>Total number of mirror repositories</p>
     * @param integer $RegistryConnectFailedCount <p>Mirror repository connection failure count</p>
     * @param array $RegistryTypeList <p>List of image repository type counts</p>
     * @param string $RequestId The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    function __construct()
    {

    }

    /**
     * For internal only. DO NOT USE IT.
     */
    public function deserialize($param)
    {
        if ($param === null) {
            return;
        }
        if (array_key_exists("RegistryCount",$param) and $param["RegistryCount"] !== null) {
            $this->RegistryCount = $param["RegistryCount"];
        }

        if (array_key_exists("RegistryConnectFailedCount",$param) and $param["RegistryConnectFailedCount"] !== null) {
            $this->RegistryConnectFailedCount = $param["RegistryConnectFailedCount"];
        }

        if (array_key_exists("RegistryTypeList",$param) and $param["RegistryTypeList"] !== null) {
            $this->RegistryTypeList = [];
            foreach ($param["RegistryTypeList"] as $key => $value){
                $obj = new ImageRegistryTypeCountItem();
                $obj->deserialize($value);
                array_push($this->RegistryTypeList, $obj);
            }
        }

        if (array_key_exists("RequestId",$param) and $param["RequestId"] !== null) {
            $this->RequestId = $param["RequestId"];
        }
    }
}
