<?php
/*
 * Copyright (c) 2017-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
namespace TencentCloud\Csip\V20221121\Models;
use TencentCloud\Common\AbstractModel;

/**
 * DescribeNFSScanConf response structure.
 *
 * @method integer getEnable() Obtain <p>Whether NFS scan is enabled. 0: No, 1: Yes, 9: Not set. Same as 0, it is not enabled.</p>
 * @method void setEnable(integer $Enable) Set <p>Whether NFS scan is enabled. 0: No, 1: Yes, 9: Not set. Same as 0, it is not enabled.</p>
 * @method integer getScope() Obtain <p>Enable scope: 0 - selected host; 1 - all hosts</p>
 * @method void setScope(integer $Scope) Set <p>Enable scope: 0 - selected host; 1 - all hosts</p>
 * @method array getIncludeQuuid() Obtain <p>List of selected quuid configurations</p>
 * @method void setIncludeQuuid(array $IncludeQuuid) Set <p>List of selected quuid configurations</p>
 * @method array getExcludeQuuid() Obtain <p>List of configurations for deselecting quuid</p>
 * @method void setExcludeQuuid(array $ExcludeQuuid) Set <p>List of configurations for deselecting quuid</p>
 * @method string getRequestId() Obtain The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
 * @method void setRequestId(string $RequestId) Set The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
 */
class DescribeNFSScanConfResponse extends AbstractModel
{
    /**
     * @var integer <p>Whether NFS scan is enabled. 0: No, 1: Yes, 9: Not set. Same as 0, it is not enabled.</p>
     */
    public $Enable;

    /**
     * @var integer <p>Enable scope: 0 - selected host; 1 - all hosts</p>
     */
    public $Scope;

    /**
     * @var array <p>List of selected quuid configurations</p>
     */
    public $IncludeQuuid;

    /**
     * @var array <p>List of configurations for deselecting quuid</p>
     */
    public $ExcludeQuuid;

    /**
     * @var string The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    public $RequestId;

    /**
     * @param integer $Enable <p>Whether NFS scan is enabled. 0: No, 1: Yes, 9: Not set. Same as 0, it is not enabled.</p>
     * @param integer $Scope <p>Enable scope: 0 - selected host; 1 - all hosts</p>
     * @param array $IncludeQuuid <p>List of selected quuid configurations</p>
     * @param array $ExcludeQuuid <p>List of configurations for deselecting quuid</p>
     * @param string $RequestId The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    function __construct()
    {

    }

    /**
     * For internal only. DO NOT USE IT.
     */
    public function deserialize($param)
    {
        if ($param === null) {
            return;
        }
        if (array_key_exists("Enable",$param) and $param["Enable"] !== null) {
            $this->Enable = $param["Enable"];
        }

        if (array_key_exists("Scope",$param) and $param["Scope"] !== null) {
            $this->Scope = $param["Scope"];
        }

        if (array_key_exists("IncludeQuuid",$param) and $param["IncludeQuuid"] !== null) {
            $this->IncludeQuuid = $param["IncludeQuuid"];
        }

        if (array_key_exists("ExcludeQuuid",$param) and $param["ExcludeQuuid"] !== null) {
            $this->ExcludeQuuid = $param["ExcludeQuuid"];
        }

        if (array_key_exists("RequestId",$param) and $param["RequestId"] !== null) {
            $this->RequestId = $param["RequestId"];
        }
    }
}
