<?php
/*
 * Copyright (c) 2017-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
namespace TencentCloud\Csip\V20221121\Models;
use TencentCloud\Common\AbstractModel;

/**
 * DescribeCFWAssetStatistics response structure.
 *
 * @method integer getNetworkTotal() Obtain Total number of network assets
 * @method void setNetworkTotal(integer $NetworkTotal) Set Total number of network assets
 * @method integer getClbTotal() Obtain Asset CLB Quantity
 * @method void setClbTotal(integer $ClbTotal) Set Asset CLB Quantity
 * @method integer getNatTotal() Obtain Number of NATs
 * @method void setNatTotal(integer $NatTotal) Set Number of NATs
 * @method integer getPublicAssetTotal() Obtain Number of Public IP Addresses
 * @method void setPublicAssetTotal(integer $PublicAssetTotal) Set Number of Public IP Addresses
 * @method integer getCVMAssetTotal() Obtain Number of hosts
 * @method void setCVMAssetTotal(integer $CVMAssetTotal) Set Number of hosts
 * @method integer getCFGTotal() Obtain Configuration risk.
 * @method void setCFGTotal(integer $CFGTotal) Set Configuration risk.
 * @method integer getPortTotal() Obtain Port risk.
 * @method void setPortTotal(integer $PortTotal) Set Port risk.
 * @method integer getWebsiteTotal() Obtain Content risk.
 * @method void setWebsiteTotal(integer $WebsiteTotal) Set Content risk.
 * @method integer getServerTotal() Obtain Risk service exposure.
 * @method void setServerTotal(integer $ServerTotal) Set Risk service exposure.
 * @method integer getWeakPasswordTotal() Obtain Weak password risk.
 * @method void setWeakPasswordTotal(integer $WeakPasswordTotal) Set Weak password risk.
 * @method integer getVULTotal() Obtain Vulnerability risk.
 * @method void setVULTotal(integer $VULTotal) Set Vulnerability risk.
 * @method string getRequestId() Obtain The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
 * @method void setRequestId(string $RequestId) Set The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
 */
class DescribeCFWAssetStatisticsResponse extends AbstractModel
{
    /**
     * @var integer Total number of network assets
     */
    public $NetworkTotal;

    /**
     * @var integer Asset CLB Quantity
     */
    public $ClbTotal;

    /**
     * @var integer Number of NATs
     */
    public $NatTotal;

    /**
     * @var integer Number of Public IP Addresses
     */
    public $PublicAssetTotal;

    /**
     * @var integer Number of hosts
     */
    public $CVMAssetTotal;

    /**
     * @var integer Configuration risk.
     */
    public $CFGTotal;

    /**
     * @var integer Port risk.
     */
    public $PortTotal;

    /**
     * @var integer Content risk.
     */
    public $WebsiteTotal;

    /**
     * @var integer Risk service exposure.
     */
    public $ServerTotal;

    /**
     * @var integer Weak password risk.
     */
    public $WeakPasswordTotal;

    /**
     * @var integer Vulnerability risk.
     */
    public $VULTotal;

    /**
     * @var string The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    public $RequestId;

    /**
     * @param integer $NetworkTotal Total number of network assets
     * @param integer $ClbTotal Asset CLB Quantity
     * @param integer $NatTotal Number of NATs
     * @param integer $PublicAssetTotal Number of Public IP Addresses
     * @param integer $CVMAssetTotal Number of hosts
     * @param integer $CFGTotal Configuration risk.
     * @param integer $PortTotal Port risk.
     * @param integer $WebsiteTotal Content risk.
     * @param integer $ServerTotal Risk service exposure.
     * @param integer $WeakPasswordTotal Weak password risk.
     * @param integer $VULTotal Vulnerability risk.
     * @param string $RequestId The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    function __construct()
    {

    }

    /**
     * For internal only. DO NOT USE IT.
     */
    public function deserialize($param)
    {
        if ($param === null) {
            return;
        }
        if (array_key_exists("NetworkTotal",$param) and $param["NetworkTotal"] !== null) {
            $this->NetworkTotal = $param["NetworkTotal"];
        }

        if (array_key_exists("ClbTotal",$param) and $param["ClbTotal"] !== null) {
            $this->ClbTotal = $param["ClbTotal"];
        }

        if (array_key_exists("NatTotal",$param) and $param["NatTotal"] !== null) {
            $this->NatTotal = $param["NatTotal"];
        }

        if (array_key_exists("PublicAssetTotal",$param) and $param["PublicAssetTotal"] !== null) {
            $this->PublicAssetTotal = $param["PublicAssetTotal"];
        }

        if (array_key_exists("CVMAssetTotal",$param) and $param["CVMAssetTotal"] !== null) {
            $this->CVMAssetTotal = $param["CVMAssetTotal"];
        }

        if (array_key_exists("CFGTotal",$param) and $param["CFGTotal"] !== null) {
            $this->CFGTotal = $param["CFGTotal"];
        }

        if (array_key_exists("PortTotal",$param) and $param["PortTotal"] !== null) {
            $this->PortTotal = $param["PortTotal"];
        }

        if (array_key_exists("WebsiteTotal",$param) and $param["WebsiteTotal"] !== null) {
            $this->WebsiteTotal = $param["WebsiteTotal"];
        }

        if (array_key_exists("ServerTotal",$param) and $param["ServerTotal"] !== null) {
            $this->ServerTotal = $param["ServerTotal"];
        }

        if (array_key_exists("WeakPasswordTotal",$param) and $param["WeakPasswordTotal"] !== null) {
            $this->WeakPasswordTotal = $param["WeakPasswordTotal"];
        }

        if (array_key_exists("VULTotal",$param) and $param["VULTotal"] !== null) {
            $this->VULTotal = $param["VULTotal"];
        }

        if (array_key_exists("RequestId",$param) and $param["RequestId"] !== null) {
            $this->RequestId = $param["RequestId"];
        }
    }
}
