<?php
/*
 * Copyright (c) 2017-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
namespace TencentCloud\Csip\V20221121\Models;
use TencentCloud\Common\AbstractModel;

/**
 * DescribePublicIpAssets response structure.
 *
 * @method array getData() Obtain List
 * @method void setData(array $Data) Set List
 * @method integer getTotal() Obtain Total number of results
 * @method void setTotal(integer $Total) Set Total number of results
 * @method array getAssetLocationList() Obtain Asset Attribution
 * @method void setAssetLocationList(array $AssetLocationList) Set Asset Attribution
 * @method array getIpTypeList() Obtain IP List Enumeration
 * @method void setIpTypeList(array $IpTypeList) Set IP List Enumeration
 * @method array getRegionList() Obtain Region List Enumeration
 * @method void setRegionList(array $RegionList) Set Region List Enumeration
 * @method array getDefenseStatusList() Obtain Protection Enumeration
 * @method void setDefenseStatusList(array $DefenseStatusList) Set Protection Enumeration
 * @method array getAssetTypeList() Obtain Asset Type Enumeration
 * @method void setAssetTypeList(array $AssetTypeList) Set Asset Type Enumeration
 * @method array getAppIdList() Obtain AppId Enumeration
 * @method void setAppIdList(array $AppIdList) Set AppId Enumeration
 * @method string getRequestId() Obtain The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
 * @method void setRequestId(string $RequestId) Set The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
 */
class DescribePublicIpAssetsResponse extends AbstractModel
{
    /**
     * @var array List
     */
    public $Data;

    /**
     * @var integer Total number of results
     */
    public $Total;

    /**
     * @var array Asset Attribution
     */
    public $AssetLocationList;

    /**
     * @var array IP List Enumeration
     */
    public $IpTypeList;

    /**
     * @var array Region List Enumeration
     */
    public $RegionList;

    /**
     * @var array Protection Enumeration
     */
    public $DefenseStatusList;

    /**
     * @var array Asset Type Enumeration
     */
    public $AssetTypeList;

    /**
     * @var array AppId Enumeration
     */
    public $AppIdList;

    /**
     * @var string The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    public $RequestId;

    /**
     * @param array $Data List
     * @param integer $Total Total number of results
     * @param array $AssetLocationList Asset Attribution
     * @param array $IpTypeList IP List Enumeration
     * @param array $RegionList Region List Enumeration
     * @param array $DefenseStatusList Protection Enumeration
     * @param array $AssetTypeList Asset Type Enumeration
     * @param array $AppIdList AppId Enumeration
     * @param string $RequestId The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    function __construct()
    {

    }

    /**
     * For internal only. DO NOT USE IT.
     */
    public function deserialize($param)
    {
        if ($param === null) {
            return;
        }
        if (array_key_exists("Data",$param) and $param["Data"] !== null) {
            $this->Data = [];
            foreach ($param["Data"] as $key => $value){
                $obj = new IpAssetListVO();
                $obj->deserialize($value);
                array_push($this->Data, $obj);
            }
        }

        if (array_key_exists("Total",$param) and $param["Total"] !== null) {
            $this->Total = $param["Total"];
        }

        if (array_key_exists("AssetLocationList",$param) and $param["AssetLocationList"] !== null) {
            $this->AssetLocationList = [];
            foreach ($param["AssetLocationList"] as $key => $value){
                $obj = new FilterDataObject();
                $obj->deserialize($value);
                array_push($this->AssetLocationList, $obj);
            }
        }

        if (array_key_exists("IpTypeList",$param) and $param["IpTypeList"] !== null) {
            $this->IpTypeList = [];
            foreach ($param["IpTypeList"] as $key => $value){
                $obj = new FilterDataObject();
                $obj->deserialize($value);
                array_push($this->IpTypeList, $obj);
            }
        }

        if (array_key_exists("RegionList",$param) and $param["RegionList"] !== null) {
            $this->RegionList = [];
            foreach ($param["RegionList"] as $key => $value){
                $obj = new FilterDataObject();
                $obj->deserialize($value);
                array_push($this->RegionList, $obj);
            }
        }

        if (array_key_exists("DefenseStatusList",$param) and $param["DefenseStatusList"] !== null) {
            $this->DefenseStatusList = [];
            foreach ($param["DefenseStatusList"] as $key => $value){
                $obj = new FilterDataObject();
                $obj->deserialize($value);
                array_push($this->DefenseStatusList, $obj);
            }
        }

        if (array_key_exists("AssetTypeList",$param) and $param["AssetTypeList"] !== null) {
            $this->AssetTypeList = [];
            foreach ($param["AssetTypeList"] as $key => $value){
                $obj = new FilterDataObject();
                $obj->deserialize($value);
                array_push($this->AssetTypeList, $obj);
            }
        }

        if (array_key_exists("AppIdList",$param) and $param["AppIdList"] !== null) {
            $this->AppIdList = [];
            foreach ($param["AppIdList"] as $key => $value){
                $obj = new FilterDataObject();
                $obj->deserialize($value);
                array_push($this->AppIdList, $obj);
            }
        }

        if (array_key_exists("RequestId",$param) and $param["RequestId"] !== null) {
            $this->RequestId = $param["RequestId"];
        }
    }
}
