<?php
/*
 * Copyright (c) 2017-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
namespace TencentCloud\Csip\V20221121\Models;
use TencentCloud\Common\AbstractModel;

/**
 * DescribeVulFixableMachineList response structure.
 *
 * @method array getData() Obtain <p>Repair host list</p>
 * @method void setData(array $Data) Set <p>Repair host list</p>
 * @method integer getTotalCount() Obtain <p>Total quantity.</p>
 * @method void setTotalCount(integer $TotalCount) Set <p>Total quantity.</p>
 * @method integer getFixableCount() Obtain <p>Number of hosts that can be repaired with one click</p>
 * @method void setFixableCount(integer $FixableCount) Set <p>Number of hosts that can be repaired with one click</p>
 * @method integer getNotFixableCount() Obtain <p>Number of hosts that cannot be one-click repaired</p>
 * @method void setNotFixableCount(integer $NotFixableCount) Set <p>Number of hosts that cannot be one-click repaired</p>
 * @method array getVulSummary() Obtain <p>Summary information of vulnerability dimension, showing overview of list of vulnerabilities to be fixed</p>
 * @method void setVulSummary(array $VulSummary) Set <p>Summary information of vulnerability dimension, showing overview of list of vulnerabilities to be fixed</p>
 * @method string getRequestId() Obtain The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
 * @method void setRequestId(string $RequestId) Set The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
 */
class DescribeVulFixableMachineListResponse extends AbstractModel
{
    /**
     * @var array <p>Repair host list</p>
     */
    public $Data;

    /**
     * @var integer <p>Total quantity.</p>
     */
    public $TotalCount;

    /**
     * @var integer <p>Number of hosts that can be repaired with one click</p>
     */
    public $FixableCount;

    /**
     * @var integer <p>Number of hosts that cannot be one-click repaired</p>
     */
    public $NotFixableCount;

    /**
     * @var array <p>Summary information of vulnerability dimension, showing overview of list of vulnerabilities to be fixed</p>
     */
    public $VulSummary;

    /**
     * @var string The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    public $RequestId;

    /**
     * @param array $Data <p>Repair host list</p>
     * @param integer $TotalCount <p>Total quantity.</p>
     * @param integer $FixableCount <p>Number of hosts that can be repaired with one click</p>
     * @param integer $NotFixableCount <p>Number of hosts that cannot be one-click repaired</p>
     * @param array $VulSummary <p>Summary information of vulnerability dimension, showing overview of list of vulnerabilities to be fixed</p>
     * @param string $RequestId The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    function __construct()
    {

    }

    /**
     * For internal only. DO NOT USE IT.
     */
    public function deserialize($param)
    {
        if ($param === null) {
            return;
        }
        if (array_key_exists("Data",$param) and $param["Data"] !== null) {
            $this->Data = [];
            foreach ($param["Data"] as $key => $value){
                $obj = new VulFixableMachineItem();
                $obj->deserialize($value);
                array_push($this->Data, $obj);
            }
        }

        if (array_key_exists("TotalCount",$param) and $param["TotalCount"] !== null) {
            $this->TotalCount = $param["TotalCount"];
        }

        if (array_key_exists("FixableCount",$param) and $param["FixableCount"] !== null) {
            $this->FixableCount = $param["FixableCount"];
        }

        if (array_key_exists("NotFixableCount",$param) and $param["NotFixableCount"] !== null) {
            $this->NotFixableCount = $param["NotFixableCount"];
        }

        if (array_key_exists("VulSummary",$param) and $param["VulSummary"] !== null) {
            $this->VulSummary = [];
            foreach ($param["VulSummary"] as $key => $value){
                $obj = new VulFixSummaryItem();
                $obj->deserialize($value);
                array_push($this->VulSummary, $obj);
            }
        }

        if (array_key_exists("RequestId",$param) and $param["RequestId"] !== null) {
            $this->RequestId = $param["RequestId"];
        }
    }
}
