<?php
/*
 * Copyright (c) 2017-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
namespace TencentCloud\Csip\V20221121\Models;
use TencentCloud\Common\AbstractModel;

/**
 * DescribeBaselineUserOtherConf response structure.
 *
 * @method BaselineUserOtherConf getUserConf() Obtain <p>User-level baseline configuration for the current account.</p>
 * @method void setUserConf(BaselineUserOtherConf $UserConf) Set <p>User-level baseline configuration for the current account.</p>
 * @method boolean getIsSync() Obtain <p>Whether from synchronization</p>
 * @method void setIsSync(boolean $IsSync) Set <p>Whether from synchronization</p>
 * @method AccountBriefInfo getAdminInfo() Obtain <p>Synchronized account information</p>
 * @method void setAdminInfo(AccountBriefInfo $AdminInfo) Set <p>Synchronized account information</p>
 * @method string getRequestId() Obtain The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
 * @method void setRequestId(string $RequestId) Set The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
 */
class DescribeBaselineUserOtherConfResponse extends AbstractModel
{
    /**
     * @var BaselineUserOtherConf <p>User-level baseline configuration for the current account.</p>
     */
    public $UserConf;

    /**
     * @var boolean <p>Whether from synchronization</p>
     */
    public $IsSync;

    /**
     * @var AccountBriefInfo <p>Synchronized account information</p>
     */
    public $AdminInfo;

    /**
     * @var string The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    public $RequestId;

    /**
     * @param BaselineUserOtherConf $UserConf <p>User-level baseline configuration for the current account.</p>
     * @param boolean $IsSync <p>Whether from synchronization</p>
     * @param AccountBriefInfo $AdminInfo <p>Synchronized account information</p>
     * @param string $RequestId The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    function __construct()
    {

    }

    /**
     * For internal only. DO NOT USE IT.
     */
    public function deserialize($param)
    {
        if ($param === null) {
            return;
        }
        if (array_key_exists("UserConf",$param) and $param["UserConf"] !== null) {
            $this->UserConf = new BaselineUserOtherConf();
            $this->UserConf->deserialize($param["UserConf"]);
        }

        if (array_key_exists("IsSync",$param) and $param["IsSync"] !== null) {
            $this->IsSync = $param["IsSync"];
        }

        if (array_key_exists("AdminInfo",$param) and $param["AdminInfo"] !== null) {
            $this->AdminInfo = new AccountBriefInfo();
            $this->AdminInfo->deserialize($param["AdminInfo"]);
        }

        if (array_key_exists("RequestId",$param) and $param["RequestId"] !== null) {
            $this->RequestId = $param["RequestId"];
        }
    }
}
