<?php
/*
 * Copyright (c) 2017-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
namespace TencentCloud\Csip\V20221121\Models;
use TencentCloud\Common\AbstractModel;

/**
 * DescribeImageRegistryConnectivityTaskResult response structure.
 *
 * @method array getConnDetectResult() Obtain <p>Link check result</p>
 * @method void setConnDetectResult(array $ConnDetectResult) Set <p>Link check result</p>
 * @method integer getFinished() Obtain <p>Whether the task ends</p><p>Enumeration values:</p><ul><li>1: task is finished</li><li>0: task is not finished</li></ul>
 * @method void setFinished(integer $Finished) Set <p>Whether the task ends</p><p>Enumeration values:</p><ul><li>1: task is finished</li><li>0: task is not finished</li></ul>
 * @method string getRequestId() Obtain The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
 * @method void setRequestId(string $RequestId) Set The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
 */
class DescribeImageRegistryConnectivityTaskResultResponse extends AbstractModel
{
    /**
     * @var array <p>Link check result</p>
     */
    public $ConnDetectResult;

    /**
     * @var integer <p>Whether the task ends</p><p>Enumeration values:</p><ul><li>1: task is finished</li><li>0: task is not finished</li></ul>
     */
    public $Finished;

    /**
     * @var string The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    public $RequestId;

    /**
     * @param array $ConnDetectResult <p>Link check result</p>
     * @param integer $Finished <p>Whether the task ends</p><p>Enumeration values:</p><ul><li>1: task is finished</li><li>0: task is not finished</li></ul>
     * @param string $RequestId The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    function __construct()
    {

    }

    /**
     * For internal only. DO NOT USE IT.
     */
    public function deserialize($param)
    {
        if ($param === null) {
            return;
        }
        if (array_key_exists("ConnDetectResult",$param) and $param["ConnDetectResult"] !== null) {
            $this->ConnDetectResult = [];
            foreach ($param["ConnDetectResult"] as $key => $value){
                $obj = new ImageRegistryConnectivityTaskResult();
                $obj->deserialize($value);
                array_push($this->ConnDetectResult, $obj);
            }
        }

        if (array_key_exists("Finished",$param) and $param["Finished"] !== null) {
            $this->Finished = $param["Finished"];
        }

        if (array_key_exists("RequestId",$param) and $param["RequestId"] !== null) {
            $this->RequestId = $param["RequestId"];
        }
    }
}
