<?php
/*
 * Copyright (c) 2017-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
namespace TencentCloud\Csip\V20221121\Models;
use TencentCloud\Common\AbstractModel;

/**
 * DescribeLicenseStatus response structure.
 *
 * @method array getList() Obtain <p>Authorization status list (flagship edition → pro edition → RASP)</p>
 * @method void setList(array $List) Set <p>Authorization status list (flagship edition → pro edition → RASP)</p>
 * @method integer getAutoRepurchaseSwitch() Obtain <p>Auto-purchase switch. 0: off; 1: on</p>
 * @method void setAutoRepurchaseSwitch(integer $AutoRepurchaseSwitch) Set <p>Auto-purchase switch. 0: off; 1: on</p>
 * @method integer getUnbindCountLeft() Obtain <p>Merged unconsumed unbinding count = (Flagship Edition total + Pro Edition total) × 2 - Unbound count in the current month</p>
 * @method void setUnbindCountLeft(integer $UnbindCountLeft) Set <p>Merged unconsumed unbinding count = (Flagship Edition total + Pro Edition total) × 2 - Unbound count in the current month</p>
 * @method string getRequestId() Obtain The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
 * @method void setRequestId(string $RequestId) Set The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
 */
class DescribeLicenseStatusResponse extends AbstractModel
{
    /**
     * @var array <p>Authorization status list (flagship edition → pro edition → RASP)</p>
     */
    public $List;

    /**
     * @var integer <p>Auto-purchase switch. 0: off; 1: on</p>
     */
    public $AutoRepurchaseSwitch;

    /**
     * @var integer <p>Merged unconsumed unbinding count = (Flagship Edition total + Pro Edition total) × 2 - Unbound count in the current month</p>
     */
    public $UnbindCountLeft;

    /**
     * @var string The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    public $RequestId;

    /**
     * @param array $List <p>Authorization status list (flagship edition → pro edition → RASP)</p>
     * @param integer $AutoRepurchaseSwitch <p>Auto-purchase switch. 0: off; 1: on</p>
     * @param integer $UnbindCountLeft <p>Merged unconsumed unbinding count = (Flagship Edition total + Pro Edition total) × 2 - Unbound count in the current month</p>
     * @param string $RequestId The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    function __construct()
    {

    }

    /**
     * For internal only. DO NOT USE IT.
     */
    public function deserialize($param)
    {
        if ($param === null) {
            return;
        }
        if (array_key_exists("List",$param) and $param["List"] !== null) {
            $this->List = [];
            foreach ($param["List"] as $key => $value){
                $obj = new LicenseStatusItem();
                $obj->deserialize($value);
                array_push($this->List, $obj);
            }
        }

        if (array_key_exists("AutoRepurchaseSwitch",$param) and $param["AutoRepurchaseSwitch"] !== null) {
            $this->AutoRepurchaseSwitch = $param["AutoRepurchaseSwitch"];
        }

        if (array_key_exists("UnbindCountLeft",$param) and $param["UnbindCountLeft"] !== null) {
            $this->UnbindCountLeft = $param["UnbindCountLeft"];
        }

        if (array_key_exists("RequestId",$param) and $param["RequestId"] !== null) {
            $this->RequestId = $param["RequestId"];
        }
    }
}
