<?php
/*
 * Copyright (c) 2017-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
namespace TencentCloud\Csip\V20221121\Models;
use TencentCloud\Common\AbstractModel;

/**
 * DescribeCSCPayInfo response structure.
 *
 * @method integer getAppID() Obtain <p>Tenant AppID.</p>
 * @method void setAppID(integer $AppID) Set <p>Tenant AppID.</p>
 * @method integer getOrderStatus() Obtain <p>Order status. Value: 0 (not purchased), 1 (normal), 2 (isolated), 3 (terminated), 4 (modified), 5 (renewed), 6 (trial use), 7 (expired), 8 (trial expiration).</p>
 * @method void setOrderStatus(integer $OrderStatus) Set <p>Order status. Value: 0 (not purchased), 1 (normal), 2 (isolated), 3 (terminated), 4 (modified), 5 (renewed), 6 (trial use), 7 (expired), 8 (trial expiration).</p>
 * @method integer getPayMode() Obtain <p>Payment mode. Values: 0 (postpaid), 1 (prepaid).</p>
 * @method void setPayMode(integer $PayMode) Set <p>Payment mode. Values: 0 (postpaid), 1 (prepaid).</p>
 * @method string getBeginTime() Obtain <p>Order start time, format: 2006-01-02 15:04:05.</p>
 * @method void setBeginTime(string $BeginTime) Set <p>Order start time, format: 2006-01-02 15:04:05.</p>
 * @method string getEndTime() Obtain <p>Order end time, format: 2006-01-02 15:04:05.</p>
 * @method void setEndTime(string $EndTime) Set <p>Order end time, format: 2006-01-02 15:04:05.</p>
 * @method integer getAutoRenew() Obtain <p>Auto-renewal flag. Values: 0 (not set), 1 (auto-renewal), 2 (no auto-renewal).</p>
 * @method void setAutoRenew(integer $AutoRenew) Set <p>Auto-renewal flag. Values: 0 (not set), 1 (auto-renewal), 2 (no auto-renewal).</p>
 * @method integer getTimeSpan() Obtain <p>Purchase period.</p>
 * @method void setTimeSpan(integer $TimeSpan) Set <p>Purchase period.</p>
 * @method string getTimeUnit() Obtain <p>Time unit, for example, m (month).</p>
 * @method void setTimeUnit(string $TimeUnit) Set <p>Time unit, for example, m (month).</p>
 * @method string getResourceId() Obtain <p>Resource ID.</p>
 * @method void setResourceId(string $ResourceId) Set <p>Resource ID.</p>
 * @method string getTimeNow() Obtain <p>Current server time, format: 2006-01-02 15:04:05.</p>
 * @method void setTimeNow(string $TimeNow) Set <p>Current server time, format: 2006-01-02 15:04:05.</p>
 * @method string getUin() Obtain <p>Account UIN.</p>
 * @method void setUin(string $Uin) Set <p>Account UIN.</p>
 * @method string getNickName() Obtain <p>Account nickname.</p>
 * @method void setNickName(string $NickName) Set <p>Account nickname.</p>
 * @method integer getNewUser() Obtain <p>Whether it is a new user. Parameter Value: 1 (new user), 0 (existing user).</p>
 * @method void setNewUser(integer $NewUser) Set <p>Whether it is a new user. Parameter Value: 1 (new user), 0 (existing user).</p>
 * @method array getQuotaList() Obtain <p>User billing info, with the Key L4</p>
 * @method void setQuotaList(array $QuotaList) Set <p>User billing info, with the Key L4</p>
 * @method string getRequestId() Obtain The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
 * @method void setRequestId(string $RequestId) Set The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
 */
class DescribeCSCPayInfoResponse extends AbstractModel
{
    /**
     * @var integer <p>Tenant AppID.</p>
     */
    public $AppID;

    /**
     * @var integer <p>Order status. Value: 0 (not purchased), 1 (normal), 2 (isolated), 3 (terminated), 4 (modified), 5 (renewed), 6 (trial use), 7 (expired), 8 (trial expiration).</p>
     */
    public $OrderStatus;

    /**
     * @var integer <p>Payment mode. Values: 0 (postpaid), 1 (prepaid).</p>
     */
    public $PayMode;

    /**
     * @var string <p>Order start time, format: 2006-01-02 15:04:05.</p>
     */
    public $BeginTime;

    /**
     * @var string <p>Order end time, format: 2006-01-02 15:04:05.</p>
     */
    public $EndTime;

    /**
     * @var integer <p>Auto-renewal flag. Values: 0 (not set), 1 (auto-renewal), 2 (no auto-renewal).</p>
     */
    public $AutoRenew;

    /**
     * @var integer <p>Purchase period.</p>
     */
    public $TimeSpan;

    /**
     * @var string <p>Time unit, for example, m (month).</p>
     */
    public $TimeUnit;

    /**
     * @var string <p>Resource ID.</p>
     */
    public $ResourceId;

    /**
     * @var string <p>Current server time, format: 2006-01-02 15:04:05.</p>
     */
    public $TimeNow;

    /**
     * @var string <p>Account UIN.</p>
     */
    public $Uin;

    /**
     * @var string <p>Account nickname.</p>
     */
    public $NickName;

    /**
     * @var integer <p>Whether it is a new user. Parameter Value: 1 (new user), 0 (existing user).</p>
     */
    public $NewUser;

    /**
     * @var array <p>User billing info, with the Key L4</p>
     */
    public $QuotaList;

    /**
     * @var string The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    public $RequestId;

    /**
     * @param integer $AppID <p>Tenant AppID.</p>
     * @param integer $OrderStatus <p>Order status. Value: 0 (not purchased), 1 (normal), 2 (isolated), 3 (terminated), 4 (modified), 5 (renewed), 6 (trial use), 7 (expired), 8 (trial expiration).</p>
     * @param integer $PayMode <p>Payment mode. Values: 0 (postpaid), 1 (prepaid).</p>
     * @param string $BeginTime <p>Order start time, format: 2006-01-02 15:04:05.</p>
     * @param string $EndTime <p>Order end time, format: 2006-01-02 15:04:05.</p>
     * @param integer $AutoRenew <p>Auto-renewal flag. Values: 0 (not set), 1 (auto-renewal), 2 (no auto-renewal).</p>
     * @param integer $TimeSpan <p>Purchase period.</p>
     * @param string $TimeUnit <p>Time unit, for example, m (month).</p>
     * @param string $ResourceId <p>Resource ID.</p>
     * @param string $TimeNow <p>Current server time, format: 2006-01-02 15:04:05.</p>
     * @param string $Uin <p>Account UIN.</p>
     * @param string $NickName <p>Account nickname.</p>
     * @param integer $NewUser <p>Whether it is a new user. Parameter Value: 1 (new user), 0 (existing user).</p>
     * @param array $QuotaList <p>User billing info, with the Key L4</p>
     * @param string $RequestId The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    function __construct()
    {

    }

    /**
     * For internal only. DO NOT USE IT.
     */
    public function deserialize($param)
    {
        if ($param === null) {
            return;
        }
        if (array_key_exists("AppID",$param) and $param["AppID"] !== null) {
            $this->AppID = $param["AppID"];
        }

        if (array_key_exists("OrderStatus",$param) and $param["OrderStatus"] !== null) {
            $this->OrderStatus = $param["OrderStatus"];
        }

        if (array_key_exists("PayMode",$param) and $param["PayMode"] !== null) {
            $this->PayMode = $param["PayMode"];
        }

        if (array_key_exists("BeginTime",$param) and $param["BeginTime"] !== null) {
            $this->BeginTime = $param["BeginTime"];
        }

        if (array_key_exists("EndTime",$param) and $param["EndTime"] !== null) {
            $this->EndTime = $param["EndTime"];
        }

        if (array_key_exists("AutoRenew",$param) and $param["AutoRenew"] !== null) {
            $this->AutoRenew = $param["AutoRenew"];
        }

        if (array_key_exists("TimeSpan",$param) and $param["TimeSpan"] !== null) {
            $this->TimeSpan = $param["TimeSpan"];
        }

        if (array_key_exists("TimeUnit",$param) and $param["TimeUnit"] !== null) {
            $this->TimeUnit = $param["TimeUnit"];
        }

        if (array_key_exists("ResourceId",$param) and $param["ResourceId"] !== null) {
            $this->ResourceId = $param["ResourceId"];
        }

        if (array_key_exists("TimeNow",$param) and $param["TimeNow"] !== null) {
            $this->TimeNow = $param["TimeNow"];
        }

        if (array_key_exists("Uin",$param) and $param["Uin"] !== null) {
            $this->Uin = $param["Uin"];
        }

        if (array_key_exists("NickName",$param) and $param["NickName"] !== null) {
            $this->NickName = $param["NickName"];
        }

        if (array_key_exists("NewUser",$param) and $param["NewUser"] !== null) {
            $this->NewUser = $param["NewUser"];
        }

        if (array_key_exists("QuotaList",$param) and $param["QuotaList"] !== null) {
            $this->QuotaList = [];
            foreach ($param["QuotaList"] as $key => $value){
                $obj = new OrderQuotaInfo();
                $obj->deserialize($value);
                array_push($this->QuotaList, $obj);
            }
        }

        if (array_key_exists("RequestId",$param) and $param["RequestId"] !== null) {
            $this->RequestId = $param["RequestId"];
        }
    }
}
