<?php
/*
 * Copyright (c) 2017-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
namespace TencentCloud\Ssm\V20190923\Models;
use TencentCloud\Common\AbstractModel;

/**
 * DescribeSupportedProducts response structure.
 *
 * @method array getProducts() Obtain List of all supported Tencent Cloud products.
The correspondence between each cloud product and secrets type is as follows:When `SecretType` is 1, the list of supported cloud products includes: Mysql, Tdsql-mysql, Tdsql_C_Mysql;When `SecretType` is 2, the supported product list is: Cvm;When `SecretType` is 3, the supported product list is: Cam (To use this function, you need to contact the cloud assistant to activate the allowlist separately);When `SecretType` is 4, the supported product list is: Redis.
 * @method void setProducts(array $Products) Set List of all supported Tencent Cloud products.
The correspondence between each cloud product and secrets type is as follows:When `SecretType` is 1, the list of supported cloud products includes: Mysql, Tdsql-mysql, Tdsql_C_Mysql;When `SecretType` is 2, the supported product list is: Cvm;When `SecretType` is 3, the supported product list is: Cam (To use this function, you need to contact the cloud assistant to activate the allowlist separately);When `SecretType` is 4, the supported product list is: Redis.
 * @method integer getTotalCount() Obtain Number of supported services
 * @method void setTotalCount(integer $TotalCount) Set Number of supported services
 * @method string getRequestId() Obtain The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
 * @method void setRequestId(string $RequestId) Set The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
 */
class DescribeSupportedProductsResponse extends AbstractModel
{
    /**
     * @var array List of all supported Tencent Cloud products.
The correspondence between each cloud product and secrets type is as follows:When `SecretType` is 1, the list of supported cloud products includes: Mysql, Tdsql-mysql, Tdsql_C_Mysql;When `SecretType` is 2, the supported product list is: Cvm;When `SecretType` is 3, the supported product list is: Cam (To use this function, you need to contact the cloud assistant to activate the allowlist separately);When `SecretType` is 4, the supported product list is: Redis.
     */
    public $Products;

    /**
     * @var integer Number of supported services
     */
    public $TotalCount;

    /**
     * @var string The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    public $RequestId;

    /**
     * @param array $Products List of all supported Tencent Cloud products.
The correspondence between each cloud product and secrets type is as follows:When `SecretType` is 1, the list of supported cloud products includes: Mysql, Tdsql-mysql, Tdsql_C_Mysql;When `SecretType` is 2, the supported product list is: Cvm;When `SecretType` is 3, the supported product list is: Cam (To use this function, you need to contact the cloud assistant to activate the allowlist separately);When `SecretType` is 4, the supported product list is: Redis.
     * @param integer $TotalCount Number of supported services
     * @param string $RequestId The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    function __construct()
    {

    }

    /**
     * For internal only. DO NOT USE IT.
     */
    public function deserialize($param)
    {
        if ($param === null) {
            return;
        }
        if (array_key_exists("Products",$param) and $param["Products"] !== null) {
            $this->Products = $param["Products"];
        }

        if (array_key_exists("TotalCount",$param) and $param["TotalCount"] !== null) {
            $this->TotalCount = $param["TotalCount"];
        }

        if (array_key_exists("RequestId",$param) and $param["RequestId"] !== null) {
            $this->RequestId = $param["RequestId"];
        }
    }
}
