<?php
/*
 * Copyright (c) 2017-2018 THL A29 Limited, a Tencent company. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
namespace TencentCloud\Car\V20220110\Models;
use TencentCloud\Common\AbstractModel;

/**
 * DescribeConcurrentSummary response structure.
 *
 * @method integer getPrepaidConcurrentTotal() Obtain Total number of prepaid (monthly subscription) concurrencies.
 * @method void setPrepaidConcurrentTotal(integer $PrepaidConcurrentTotal) Set Total number of prepaid (monthly subscription) concurrencies.
 * @method string getHourlyRemainDuration() Obtain Remaining duration of an hourly package.
 * @method void setHourlyRemainDuration(string $HourlyRemainDuration) Set Remaining duration of an hourly package.
 * @method string getRequestId() Obtain The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
 * @method void setRequestId(string $RequestId) Set The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
 */
class DescribeConcurrentSummaryResponse extends AbstractModel
{
    /**
     * @var integer Total number of prepaid (monthly subscription) concurrencies.
     */
    public $PrepaidConcurrentTotal;

    /**
     * @var string Remaining duration of an hourly package.
     */
    public $HourlyRemainDuration;

    /**
     * @var string The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    public $RequestId;

    /**
     * @param integer $PrepaidConcurrentTotal Total number of prepaid (monthly subscription) concurrencies.
     * @param string $HourlyRemainDuration Remaining duration of an hourly package.
     * @param string $RequestId The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    function __construct()
    {

    }

    /**
     * For internal only. DO NOT USE IT.
     */
    public function deserialize($param)
    {
        if ($param === null) {
            return;
        }
        if (array_key_exists("PrepaidConcurrentTotal",$param) and $param["PrepaidConcurrentTotal"] !== null) {
            $this->PrepaidConcurrentTotal = $param["PrepaidConcurrentTotal"];
        }

        if (array_key_exists("HourlyRemainDuration",$param) and $param["HourlyRemainDuration"] !== null) {
            $this->HourlyRemainDuration = $param["HourlyRemainDuration"];
        }

        if (array_key_exists("RequestId",$param) and $param["RequestId"] !== null) {
            $this->RequestId = $param["RequestId"];
        }
    }
}
