<?php
/*
 * Copyright (c) 2017-2018 THL A29 Limited, a Tencent company. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
namespace TencentCloud\Wedata\V20210820\Models;
use TencentCloud\Common\AbstractModel;

/**
 * Instance log information details
 *
 * @method string getLogInfo() Obtain Instance running log
Note: This field may return null, indicating that no valid value can be obtained.
 * @method void setLogInfo(string $LogInfo) Set Instance running log
Note: This field may return null, indicating that no valid value can be obtained.
 * @method array getYarnLogInfo() Obtain The Yarn log address submitted by the instance run
Note: This field may return null, indicating that no valid value can be obtained.
 * @method void setYarnLogInfo(array $YarnLogInfo) Set The Yarn log address submitted by the instance run
Note: This field may return null, indicating that no valid value can be obtained.
 * @method string getDataLogInfo() Obtain The datax log generated by the instance run
Note: This field may return null, indicating that no valid value can be obtained.
 * @method void setDataLogInfo(string $DataLogInfo) Set The datax log generated by the instance run
Note: This field may return null, indicating that no valid value can be obtained.
 * @method string getThirdTaskRunLogInfo() Obtain Third-party Task Execution Log
Note: This field may return null, indicating that no valid value can be obtained.
 * @method void setThirdTaskRunLogInfo(string $ThirdTaskRunLogInfo) Set Third-party Task Execution Log
Note: This field may return null, indicating that no valid value can be obtained.
 * @method string getThirdTaskLogUrlDesc() Obtain Third-party Task Log Link Description
Note: This field may return null, indicating that no valid value can be obtained.
 * @method void setThirdTaskLogUrlDesc(string $ThirdTaskLogUrlDesc) Set Third-party Task Log Link Description
Note: This field may return null, indicating that no valid value can be obtained.
 * @method integer getLineCount() Obtain Number of Log Lines
Note: This field may return null, indicating that no valid value can be obtained.
 * @method void setLineCount(integer $LineCount) Set Number of Log Lines
Note: This field may return null, indicating that no valid value can be obtained.
 */
class InstanceLogInfoOpsDto extends AbstractModel
{
    /**
     * @var string Instance running log
Note: This field may return null, indicating that no valid value can be obtained.
     */
    public $LogInfo;

    /**
     * @var array The Yarn log address submitted by the instance run
Note: This field may return null, indicating that no valid value can be obtained.
     */
    public $YarnLogInfo;

    /**
     * @var string The datax log generated by the instance run
Note: This field may return null, indicating that no valid value can be obtained.
     */
    public $DataLogInfo;

    /**
     * @var string Third-party Task Execution Log
Note: This field may return null, indicating that no valid value can be obtained.
     */
    public $ThirdTaskRunLogInfo;

    /**
     * @var string Third-party Task Log Link Description
Note: This field may return null, indicating that no valid value can be obtained.
     */
    public $ThirdTaskLogUrlDesc;

    /**
     * @var integer Number of Log Lines
Note: This field may return null, indicating that no valid value can be obtained.
     */
    public $LineCount;

    /**
     * @param string $LogInfo Instance running log
Note: This field may return null, indicating that no valid value can be obtained.
     * @param array $YarnLogInfo The Yarn log address submitted by the instance run
Note: This field may return null, indicating that no valid value can be obtained.
     * @param string $DataLogInfo The datax log generated by the instance run
Note: This field may return null, indicating that no valid value can be obtained.
     * @param string $ThirdTaskRunLogInfo Third-party Task Execution Log
Note: This field may return null, indicating that no valid value can be obtained.
     * @param string $ThirdTaskLogUrlDesc Third-party Task Log Link Description
Note: This field may return null, indicating that no valid value can be obtained.
     * @param integer $LineCount Number of Log Lines
Note: This field may return null, indicating that no valid value can be obtained.
     */
    function __construct()
    {

    }

    /**
     * For internal only. DO NOT USE IT.
     */
    public function deserialize($param)
    {
        if ($param === null) {
            return;
        }
        if (array_key_exists("LogInfo",$param) and $param["LogInfo"] !== null) {
            $this->LogInfo = $param["LogInfo"];
        }

        if (array_key_exists("YarnLogInfo",$param) and $param["YarnLogInfo"] !== null) {
            $this->YarnLogInfo = $param["YarnLogInfo"];
        }

        if (array_key_exists("DataLogInfo",$param) and $param["DataLogInfo"] !== null) {
            $this->DataLogInfo = $param["DataLogInfo"];
        }

        if (array_key_exists("ThirdTaskRunLogInfo",$param) and $param["ThirdTaskRunLogInfo"] !== null) {
            $this->ThirdTaskRunLogInfo = $param["ThirdTaskRunLogInfo"];
        }

        if (array_key_exists("ThirdTaskLogUrlDesc",$param) and $param["ThirdTaskLogUrlDesc"] !== null) {
            $this->ThirdTaskLogUrlDesc = $param["ThirdTaskLogUrlDesc"];
        }

        if (array_key_exists("LineCount",$param) and $param["LineCount"] !== null) {
            $this->LineCount = $param["LineCount"];
        }
    }
}
