<?php
/*
 * Copyright (c) 2017-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
namespace TencentCloud\Ssl\V20191205\Models;
use TencentCloud\Common\AbstractModel;

/**
 * CheckCertificateDomainVerification response structure.
 *
 * @method array getVerificationResults() Obtain Domain validation result list. If the cert is bound to multiple domain names, the return array contains multiple items.
Note: This field may return null, indicating that no valid values can be obtained.
 * @method void setVerificationResults(array $VerificationResults) Set Domain validation result list. If the cert is bound to multiple domain names, the return array contains multiple items.
Note: This field may return null, indicating that no valid values can be obtained.
 * @method string getRequestId() Obtain The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
 * @method void setRequestId(string $RequestId) Set The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
 */
class CheckCertificateDomainVerificationResponse extends AbstractModel
{
    /**
     * @var array Domain validation result list. If the cert is bound to multiple domain names, the return array contains multiple items.
Note: This field may return null, indicating that no valid values can be obtained.
     */
    public $VerificationResults;

    /**
     * @var string The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    public $RequestId;

    /**
     * @param array $VerificationResults Domain validation result list. If the cert is bound to multiple domain names, the return array contains multiple items.
Note: This field may return null, indicating that no valid values can be obtained.
     * @param string $RequestId The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    function __construct()
    {

    }

    /**
     * For internal only. DO NOT USE IT.
     */
    public function deserialize($param)
    {
        if ($param === null) {
            return;
        }
        if (array_key_exists("VerificationResults",$param) and $param["VerificationResults"] !== null) {
            $this->VerificationResults = [];
            foreach ($param["VerificationResults"] as $key => $value){
                $obj = new DomainValidationResult();
                $obj->deserialize($value);
                array_push($this->VerificationResults, $obj);
            }
        }

        if (array_key_exists("RequestId",$param) and $param["RequestId"] !== null) {
            $this->RequestId = $param["RequestId"];
        }
    }
}
