<?php
/*
 * Copyright (c) 2017-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
namespace TencentCloud\Hunyuan\V20230901\Models;
use TencentCloud\Common\AbstractModel;

/**
 * SubmitHunyuan3DPartJob request structure.
 *
 * @method InputFile3D getFile() Obtain <p>Recommends inputting 3D models generated by AIGC Recommended file size not greater than 200MB Face count not greater than 1,500,000 Only supports FBX format</p>
 * @method void setFile(InputFile3D $File) Set <p>Recommends inputting 3D models generated by AIGC Recommended file size not greater than 200MB Face count not greater than 1,500,000 Only supports FBX format</p>
 * @method string getPartSegmentationInfo() Obtain <p>Model component segmentation data; The format is a JSON string, e.g., {"MeshName_part_1":{"face_ids": 1,2,3..],"color":"#FF805C"}}. Here, face_ids is an integer array representing the set of face IDs for the segment, and color specifies the color.</p>
 * @method void setPartSegmentationInfo(string $PartSegmentationInfo) Set <p>Model component segmentation data; The format is a JSON string, e.g., {"MeshName_part_1":{"face_ids": 1,2,3..],"color":"#FF805C"}}. Here, face_ids is an integer array representing the set of face IDs for the segment, and color specifies the color.</p>
 * @method boolean getEnableStagedGeneration() Obtain <p>Determines whether component generation is performed in a step-by-step manner. When enabled, providing the original model allows for the generation of a model containing segmentation information, along with the corresponding segmentation data. Users can then edit this information before submitting the segmented model and data to proceed with the component generation process. </br>This parameter is disabled by default.</p>
 * @method void setEnableStagedGeneration(boolean $EnableStagedGeneration) Set <p>Determines whether component generation is performed in a step-by-step manner. When enabled, providing the original model allows for the generation of a model containing segmentation information, along with the corresponding segmentation data. Users can then edit this information before submitting the segmented model and data to proceed with the component generation process. </br>This parameter is disabled by default.</p>
 * @method boolean getEnablePostProcess() Obtain <p>Whether post-processing is enabled. Once enabled, only one model link will be output, off by default. (After this API is enabled, an additional increase of 20 points is required.)</p>
 * @method void setEnablePostProcess(boolean $EnablePostProcess) Set <p>Whether post-processing is enabled. Once enabled, only one model link will be output, off by default. (After this API is enabled, an additional increase of 20 points is required.)</p>
 */
class SubmitHunyuan3DPartJobRequest extends AbstractModel
{
    /**
     * @var InputFile3D <p>Recommends inputting 3D models generated by AIGC Recommended file size not greater than 200MB Face count not greater than 1,500,000 Only supports FBX format</p>
     */
    public $File;

    /**
     * @var string <p>Model component segmentation data; The format is a JSON string, e.g., {"MeshName_part_1":{"face_ids": 1,2,3..],"color":"#FF805C"}}. Here, face_ids is an integer array representing the set of face IDs for the segment, and color specifies the color.</p>
     */
    public $PartSegmentationInfo;

    /**
     * @var boolean <p>Determines whether component generation is performed in a step-by-step manner. When enabled, providing the original model allows for the generation of a model containing segmentation information, along with the corresponding segmentation data. Users can then edit this information before submitting the segmented model and data to proceed with the component generation process. </br>This parameter is disabled by default.</p>
     */
    public $EnableStagedGeneration;

    /**
     * @var boolean <p>Whether post-processing is enabled. Once enabled, only one model link will be output, off by default. (After this API is enabled, an additional increase of 20 points is required.)</p>
     */
    public $EnablePostProcess;

    /**
     * @param InputFile3D $File <p>Recommends inputting 3D models generated by AIGC Recommended file size not greater than 200MB Face count not greater than 1,500,000 Only supports FBX format</p>
     * @param string $PartSegmentationInfo <p>Model component segmentation data; The format is a JSON string, e.g., {"MeshName_part_1":{"face_ids": 1,2,3..],"color":"#FF805C"}}. Here, face_ids is an integer array representing the set of face IDs for the segment, and color specifies the color.</p>
     * @param boolean $EnableStagedGeneration <p>Determines whether component generation is performed in a step-by-step manner. When enabled, providing the original model allows for the generation of a model containing segmentation information, along with the corresponding segmentation data. Users can then edit this information before submitting the segmented model and data to proceed with the component generation process. </br>This parameter is disabled by default.</p>
     * @param boolean $EnablePostProcess <p>Whether post-processing is enabled. Once enabled, only one model link will be output, off by default. (After this API is enabled, an additional increase of 20 points is required.)</p>
     */
    function __construct()
    {

    }

    /**
     * For internal only. DO NOT USE IT.
     */
    public function deserialize($param)
    {
        if ($param === null) {
            return;
        }
        if (array_key_exists("File",$param) and $param["File"] !== null) {
            $this->File = new InputFile3D();
            $this->File->deserialize($param["File"]);
        }

        if (array_key_exists("PartSegmentationInfo",$param) and $param["PartSegmentationInfo"] !== null) {
            $this->PartSegmentationInfo = $param["PartSegmentationInfo"];
        }

        if (array_key_exists("EnableStagedGeneration",$param) and $param["EnableStagedGeneration"] !== null) {
            $this->EnableStagedGeneration = $param["EnableStagedGeneration"];
        }

        if (array_key_exists("EnablePostProcess",$param) and $param["EnablePostProcess"] !== null) {
            $this->EnablePostProcess = $param["EnablePostProcess"];
        }
    }
}
