<?php
/*
 * Copyright (c) 2017-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
namespace TencentCloud\Mna\V20210119\Models;
use TencentCloud\Common\AbstractModel;

/**
 * GetFlowAlarmInfo response structure.
 *
 * @method integer getAlarmValue() Obtain Alarm threshold of the data transfer plan
 * @method void setAlarmValue(integer $AlarmValue) Set Alarm threshold of the data transfer plan
 * @method string getNotifyUrl() Obtain Alarm notification callback url
 * @method void setNotifyUrl(string $NotifyUrl) Set Alarm notification callback url
 * @method string getCallbackKey() Obtain Alarm notification callback key
 * @method void setCallbackKey(string $CallbackKey) Set Alarm notification callback key
 * @method string getRequestId() Obtain The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
 * @method void setRequestId(string $RequestId) Set The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
 */
class GetFlowAlarmInfoResponse extends AbstractModel
{
    /**
     * @var integer Alarm threshold of the data transfer plan
     */
    public $AlarmValue;

    /**
     * @var string Alarm notification callback url
     */
    public $NotifyUrl;

    /**
     * @var string Alarm notification callback key
     */
    public $CallbackKey;

    /**
     * @var string The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    public $RequestId;

    /**
     * @param integer $AlarmValue Alarm threshold of the data transfer plan
     * @param string $NotifyUrl Alarm notification callback url
     * @param string $CallbackKey Alarm notification callback key
     * @param string $RequestId The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    function __construct()
    {

    }

    /**
     * For internal only. DO NOT USE IT.
     */
    public function deserialize($param)
    {
        if ($param === null) {
            return;
        }
        if (array_key_exists("AlarmValue",$param) and $param["AlarmValue"] !== null) {
            $this->AlarmValue = $param["AlarmValue"];
        }

        if (array_key_exists("NotifyUrl",$param) and $param["NotifyUrl"] !== null) {
            $this->NotifyUrl = $param["NotifyUrl"];
        }

        if (array_key_exists("CallbackKey",$param) and $param["CallbackKey"] !== null) {
            $this->CallbackKey = $param["CallbackKey"];
        }

        if (array_key_exists("RequestId",$param) and $param["RequestId"] !== null) {
            $this->RequestId = $param["RequestId"];
        }
    }
}
