<?php
/*
 * Copyright (c) 2017-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
namespace TencentCloud\Mna\V20210119\Models;
use TencentCloud\Common\AbstractModel;

/**
 * GetGroupDetail response structure.
 *
 * @method GroupInfo getGroupInfo() Obtain Group basic info
 * @method void setGroupInfo(GroupInfo $GroupInfo) Set Group basic info
 * @method array getDeviceInfos() Obtain Device list grouped in
 * @method void setDeviceInfos(array $DeviceInfos) Set Device list grouped in
 * @method integer getLength() Obtain Total number of devices
 * @method void setLength(integer $Length) Set Total number of devices
 * @method integer getTotalPage() Obtain Total pages
 * @method void setTotalPage(integer $TotalPage) Set Total pages
 * @method string getRequestId() Obtain The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
 * @method void setRequestId(string $RequestId) Set The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
 */
class GetGroupDetailResponse extends AbstractModel
{
    /**
     * @var GroupInfo Group basic info
     */
    public $GroupInfo;

    /**
     * @var array Device list grouped in
     */
    public $DeviceInfos;

    /**
     * @var integer Total number of devices
     */
    public $Length;

    /**
     * @var integer Total pages
     */
    public $TotalPage;

    /**
     * @var string The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    public $RequestId;

    /**
     * @param GroupInfo $GroupInfo Group basic info
     * @param array $DeviceInfos Device list grouped in
     * @param integer $Length Total number of devices
     * @param integer $TotalPage Total pages
     * @param string $RequestId The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    function __construct()
    {

    }

    /**
     * For internal only. DO NOT USE IT.
     */
    public function deserialize($param)
    {
        if ($param === null) {
            return;
        }
        if (array_key_exists("GroupInfo",$param) and $param["GroupInfo"] !== null) {
            $this->GroupInfo = new GroupInfo();
            $this->GroupInfo->deserialize($param["GroupInfo"]);
        }

        if (array_key_exists("DeviceInfos",$param) and $param["DeviceInfos"] !== null) {
            $this->DeviceInfos = [];
            foreach ($param["DeviceInfos"] as $key => $value){
                $obj = new DeviceBaseInfo();
                $obj->deserialize($value);
                array_push($this->DeviceInfos, $obj);
            }
        }

        if (array_key_exists("Length",$param) and $param["Length"] !== null) {
            $this->Length = $param["Length"];
        }

        if (array_key_exists("TotalPage",$param) and $param["TotalPage"] !== null) {
            $this->TotalPage = $param["TotalPage"];
        }

        if (array_key_exists("RequestId",$param) and $param["RequestId"] !== null) {
            $this->RequestId = $param["RequestId"];
        }
    }
}
