<?php
/*
 * Copyright (c) 2017-2018 THL A29 Limited, a Tencent company. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
namespace TencentCloud\Teo\V20220901\Models;
use TencentCloud\Common\AbstractModel;

/**
 * DescribeConfigGroupVersionDetail response structure.
 *
 * @method ConfigGroupVersionInfo getConfigGroupVersionInfo() Obtain Version information.
 * @method void setConfigGroupVersionInfo(ConfigGroupVersionInfo $ConfigGroupVersionInfo) Set Version information.
 * @method string getContent() Obtain Version file content. It is returned in JSON format.
 * @method void setContent(string $Content) Set Version file content. It is returned in JSON format.
 * @method string getRequestId() Obtain The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
 * @method void setRequestId(string $RequestId) Set The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
 */
class DescribeConfigGroupVersionDetailResponse extends AbstractModel
{
    /**
     * @var ConfigGroupVersionInfo Version information.
     */
    public $ConfigGroupVersionInfo;

    /**
     * @var string Version file content. It is returned in JSON format.
     */
    public $Content;

    /**
     * @var string The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    public $RequestId;

    /**
     * @param ConfigGroupVersionInfo $ConfigGroupVersionInfo Version information.
     * @param string $Content Version file content. It is returned in JSON format.
     * @param string $RequestId The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    function __construct()
    {

    }

    /**
     * For internal only. DO NOT USE IT.
     */
    public function deserialize($param)
    {
        if ($param === null) {
            return;
        }
        if (array_key_exists("ConfigGroupVersionInfo",$param) and $param["ConfigGroupVersionInfo"] !== null) {
            $this->ConfigGroupVersionInfo = new ConfigGroupVersionInfo();
            $this->ConfigGroupVersionInfo->deserialize($param["ConfigGroupVersionInfo"]);
        }

        if (array_key_exists("Content",$param) and $param["Content"] !== null) {
            $this->Content = $param["Content"];
        }

        if (array_key_exists("RequestId",$param) and $param["RequestId"] !== null) {
            $this->RequestId = $param["RequestId"];
        }
    }
}
