<?php
/*
 * Copyright (c) 2017-2018 THL A29 Limited, a Tencent company. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
namespace TencentCloud\Teo\V20220901\Models;
use TencentCloud\Common\AbstractModel;

/**
 * DescribeRealtimeLogDeliveryTasks response structure.
 *
 * @method integer getTotalCount() Obtain The number of real-time log delivery tasks which match the query conditions.
 * @method void setTotalCount(integer $TotalCount) Set The number of real-time log delivery tasks which match the query conditions.
 * @method array getRealtimeLogDeliveryTasks() Obtain The list of all real-time log delivery tasks which match the query conditions.
 * @method void setRealtimeLogDeliveryTasks(array $RealtimeLogDeliveryTasks) Set The list of all real-time log delivery tasks which match the query conditions.
 * @method string getRequestId() Obtain The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
 * @method void setRequestId(string $RequestId) Set The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
 */
class DescribeRealtimeLogDeliveryTasksResponse extends AbstractModel
{
    /**
     * @var integer The number of real-time log delivery tasks which match the query conditions.
     */
    public $TotalCount;

    /**
     * @var array The list of all real-time log delivery tasks which match the query conditions.
     */
    public $RealtimeLogDeliveryTasks;

    /**
     * @var string The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    public $RequestId;

    /**
     * @param integer $TotalCount The number of real-time log delivery tasks which match the query conditions.
     * @param array $RealtimeLogDeliveryTasks The list of all real-time log delivery tasks which match the query conditions.
     * @param string $RequestId The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    function __construct()
    {

    }

    /**
     * For internal only. DO NOT USE IT.
     */
    public function deserialize($param)
    {
        if ($param === null) {
            return;
        }
        if (array_key_exists("TotalCount",$param) and $param["TotalCount"] !== null) {
            $this->TotalCount = $param["TotalCount"];
        }

        if (array_key_exists("RealtimeLogDeliveryTasks",$param) and $param["RealtimeLogDeliveryTasks"] !== null) {
            $this->RealtimeLogDeliveryTasks = [];
            foreach ($param["RealtimeLogDeliveryTasks"] as $key => $value){
                $obj = new RealtimeLogDeliveryTask();
                $obj->deserialize($value);
                array_push($this->RealtimeLogDeliveryTasks, $obj);
            }
        }

        if (array_key_exists("RequestId",$param) and $param["RequestId"] !== null) {
            $this->RequestId = $param["RequestId"];
        }
    }
}
