<?php
/*
 * Copyright (c) 2017-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
namespace TencentCloud\Cls\V20201016\Models;
use TencentCloud\Common\AbstractModel;

/**
 * DescribeRecordingRuleTask response structure.
 *
 * @method array getRecordingRuleTaskInfos() Obtain <p>Task list information of RecordingRule</p>
 * @method void setRecordingRuleTaskInfos(array $RecordingRuleTaskInfos) Set <p>Task list information of RecordingRule</p>
 * @method integer getTotalCount() Obtain <p>Total number of tasks.</p>
 * @method void setTotalCount(integer $TotalCount) Set <p>Total number of tasks.</p>
 * @method string getRequestId() Obtain The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
 * @method void setRequestId(string $RequestId) Set The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
 */
class DescribeRecordingRuleTaskResponse extends AbstractModel
{
    /**
     * @var array <p>Task list information of RecordingRule</p>
     */
    public $RecordingRuleTaskInfos;

    /**
     * @var integer <p>Total number of tasks.</p>
     */
    public $TotalCount;

    /**
     * @var string The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    public $RequestId;

    /**
     * @param array $RecordingRuleTaskInfos <p>Task list information of RecordingRule</p>
     * @param integer $TotalCount <p>Total number of tasks.</p>
     * @param string $RequestId The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    function __construct()
    {

    }

    /**
     * For internal only. DO NOT USE IT.
     */
    public function deserialize($param)
    {
        if ($param === null) {
            return;
        }
        if (array_key_exists("RecordingRuleTaskInfos",$param) and $param["RecordingRuleTaskInfos"] !== null) {
            $this->RecordingRuleTaskInfos = [];
            foreach ($param["RecordingRuleTaskInfos"] as $key => $value){
                $obj = new RecordingRuleTaskInfo();
                $obj->deserialize($value);
                array_push($this->RecordingRuleTaskInfos, $obj);
            }
        }

        if (array_key_exists("TotalCount",$param) and $param["TotalCount"] !== null) {
            $this->TotalCount = $param["TotalCount"];
        }

        if (array_key_exists("RequestId",$param) and $param["RequestId"] !== null) {
            $this->RequestId = $param["RequestId"];
        }
    }
}
