<?php
/*
 * Copyright (c) 2017-2018 THL A29 Limited, a Tencent company. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
namespace TencentCloud\Cls\V20201016\Models;
use TencentCloud\Common\AbstractModel;

/**
 * Machine group information
 *
 * @method string getGroupId() Obtain Machine group ID
 * @method void setGroupId(string $GroupId) Set Machine group ID
 * @method string getGroupName() Obtain Machine group name
 * @method void setGroupName(string $GroupName) Set Machine group name
 * @method MachineGroupTypeInfo getMachineGroupType() Obtain Machine group type
 * @method void setMachineGroupType(MachineGroupTypeInfo $MachineGroupType) Set Machine group type
 * @method string getCreateTime() Obtain Creation time
 * @method void setCreateTime(string $CreateTime) Set Creation time
 * @method array getTags() Obtain List of tags bound to machine group
Note: this field may return `null`, indicating that no valid values can be obtained.
 * @method void setTags(array $Tags) Set List of tags bound to machine group
Note: this field may return `null`, indicating that no valid values can be obtained.
 * @method string getAutoUpdate() Obtain Whether to enable automatic update for the machine group
Note: this field may return `null`, indicating that no valid values can be obtained.
 * @method void setAutoUpdate(string $AutoUpdate) Set Whether to enable automatic update for the machine group
Note: this field may return `null`, indicating that no valid values can be obtained.
 * @method string getUpdateStartTime() Obtain Update start time. We recommend you update LogListener during off-peak hours.
Note: this field may return `null`, indicating that no valid values can be obtained.
 * @method void setUpdateStartTime(string $UpdateStartTime) Set Update start time. We recommend you update LogListener during off-peak hours.
Note: this field may return `null`, indicating that no valid values can be obtained.
 * @method string getUpdateEndTime() Obtain Update end time. We recommend you update LogListener during off-peak hours.
Note: this field may return `null`, indicating that no valid values can be obtained.
 * @method void setUpdateEndTime(string $UpdateEndTime) Set Update end time. We recommend you update LogListener during off-peak hours.
Note: this field may return `null`, indicating that no valid values can be obtained.
 * @method boolean getServiceLogging() Obtain Whether to enable the service log to record the logs generated by the LogListener service itself. After it is enabled, the internal logset `cls_service_logging` and the `loglistener_status`, `loglistener_alarm`, and `loglistener_business` log topics will be created, which will not incur fees.
Note: this field may return `null`, indicating that no valid values can be obtained.
 * @method void setServiceLogging(boolean $ServiceLogging) Set Whether to enable the service log to record the logs generated by the LogListener service itself. After it is enabled, the internal logset `cls_service_logging` and the `loglistener_status`, `loglistener_alarm`, and `loglistener_business` log topics will be created, which will not incur fees.
Note: this field may return `null`, indicating that no valid values can be obtained.
 * @method integer getDelayCleanupTime() Obtain Regular cleanup time for offline machines in the machine group
Note: This field may return null, indicating that no valid values can be obtained.
 * @method void setDelayCleanupTime(integer $DelayCleanupTime) Set Regular cleanup time for offline machines in the machine group
Note: This field may return null, indicating that no valid values can be obtained.
 * @method array getMetaTags() Obtain Metadata information list of a machine group
 * @method void setMetaTags(array $MetaTags) Set Metadata information list of a machine group
 * @method integer getOSType() Obtain Operating system type, 0: Linux, 1: Windows
 * @method void setOSType(integer $OSType) Set Operating system type, 0: Linux, 1: Windows
 */
class MachineGroupInfo extends AbstractModel
{
    /**
     * @var string Machine group ID
     */
    public $GroupId;

    /**
     * @var string Machine group name
     */
    public $GroupName;

    /**
     * @var MachineGroupTypeInfo Machine group type
     */
    public $MachineGroupType;

    /**
     * @var string Creation time
     */
    public $CreateTime;

    /**
     * @var array List of tags bound to machine group
Note: this field may return `null`, indicating that no valid values can be obtained.
     */
    public $Tags;

    /**
     * @var string Whether to enable automatic update for the machine group
Note: this field may return `null`, indicating that no valid values can be obtained.
     */
    public $AutoUpdate;

    /**
     * @var string Update start time. We recommend you update LogListener during off-peak hours.
Note: this field may return `null`, indicating that no valid values can be obtained.
     */
    public $UpdateStartTime;

    /**
     * @var string Update end time. We recommend you update LogListener during off-peak hours.
Note: this field may return `null`, indicating that no valid values can be obtained.
     */
    public $UpdateEndTime;

    /**
     * @var boolean Whether to enable the service log to record the logs generated by the LogListener service itself. After it is enabled, the internal logset `cls_service_logging` and the `loglistener_status`, `loglistener_alarm`, and `loglistener_business` log topics will be created, which will not incur fees.
Note: this field may return `null`, indicating that no valid values can be obtained.
     */
    public $ServiceLogging;

    /**
     * @var integer Regular cleanup time for offline machines in the machine group
Note: This field may return null, indicating that no valid values can be obtained.
     */
    public $DelayCleanupTime;

    /**
     * @var array Metadata information list of a machine group
     */
    public $MetaTags;

    /**
     * @var integer Operating system type, 0: Linux, 1: Windows
     */
    public $OSType;

    /**
     * @param string $GroupId Machine group ID
     * @param string $GroupName Machine group name
     * @param MachineGroupTypeInfo $MachineGroupType Machine group type
     * @param string $CreateTime Creation time
     * @param array $Tags List of tags bound to machine group
Note: this field may return `null`, indicating that no valid values can be obtained.
     * @param string $AutoUpdate Whether to enable automatic update for the machine group
Note: this field may return `null`, indicating that no valid values can be obtained.
     * @param string $UpdateStartTime Update start time. We recommend you update LogListener during off-peak hours.
Note: this field may return `null`, indicating that no valid values can be obtained.
     * @param string $UpdateEndTime Update end time. We recommend you update LogListener during off-peak hours.
Note: this field may return `null`, indicating that no valid values can be obtained.
     * @param boolean $ServiceLogging Whether to enable the service log to record the logs generated by the LogListener service itself. After it is enabled, the internal logset `cls_service_logging` and the `loglistener_status`, `loglistener_alarm`, and `loglistener_business` log topics will be created, which will not incur fees.
Note: this field may return `null`, indicating that no valid values can be obtained.
     * @param integer $DelayCleanupTime Regular cleanup time for offline machines in the machine group
Note: This field may return null, indicating that no valid values can be obtained.
     * @param array $MetaTags Metadata information list of a machine group
     * @param integer $OSType Operating system type, 0: Linux, 1: Windows
     */
    function __construct()
    {

    }

    /**
     * For internal only. DO NOT USE IT.
     */
    public function deserialize($param)
    {
        if ($param === null) {
            return;
        }
        if (array_key_exists("GroupId",$param) and $param["GroupId"] !== null) {
            $this->GroupId = $param["GroupId"];
        }

        if (array_key_exists("GroupName",$param) and $param["GroupName"] !== null) {
            $this->GroupName = $param["GroupName"];
        }

        if (array_key_exists("MachineGroupType",$param) and $param["MachineGroupType"] !== null) {
            $this->MachineGroupType = new MachineGroupTypeInfo();
            $this->MachineGroupType->deserialize($param["MachineGroupType"]);
        }

        if (array_key_exists("CreateTime",$param) and $param["CreateTime"] !== null) {
            $this->CreateTime = $param["CreateTime"];
        }

        if (array_key_exists("Tags",$param) and $param["Tags"] !== null) {
            $this->Tags = [];
            foreach ($param["Tags"] as $key => $value){
                $obj = new Tag();
                $obj->deserialize($value);
                array_push($this->Tags, $obj);
            }
        }

        if (array_key_exists("AutoUpdate",$param) and $param["AutoUpdate"] !== null) {
            $this->AutoUpdate = $param["AutoUpdate"];
        }

        if (array_key_exists("UpdateStartTime",$param) and $param["UpdateStartTime"] !== null) {
            $this->UpdateStartTime = $param["UpdateStartTime"];
        }

        if (array_key_exists("UpdateEndTime",$param) and $param["UpdateEndTime"] !== null) {
            $this->UpdateEndTime = $param["UpdateEndTime"];
        }

        if (array_key_exists("ServiceLogging",$param) and $param["ServiceLogging"] !== null) {
            $this->ServiceLogging = $param["ServiceLogging"];
        }

        if (array_key_exists("DelayCleanupTime",$param) and $param["DelayCleanupTime"] !== null) {
            $this->DelayCleanupTime = $param["DelayCleanupTime"];
        }

        if (array_key_exists("MetaTags",$param) and $param["MetaTags"] !== null) {
            $this->MetaTags = [];
            foreach ($param["MetaTags"] as $key => $value){
                $obj = new MetaTagInfo();
                $obj->deserialize($value);
                array_push($this->MetaTags, $obj);
            }
        }

        if (array_key_exists("OSType",$param) and $param["OSType"] !== null) {
            $this->OSType = $param["OSType"];
        }
    }
}
