<?php
/*
 * Copyright (c) 2017-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
namespace TencentCloud\Postgres\V20170312\Models;
use TencentCloud\Common\AbstractModel;

/**
 * DescribeDBInstanceSSLConfig response structure.
 *
 * @method boolean getSSLEnabled() Obtain true represents enabled. false represents not enabled.
 * @method void setSSLEnabled(boolean $SSLEnabled) Set true represents enabled. false represents not enabled.
 * @method string getCAUrl() Obtain Certificate download url for the cloud root certificate.
 * @method void setCAUrl(string $CAUrl) Set Certificate download url for the cloud root certificate.
 * @method string getConnectAddress() Obtain Specifies the intranet or public network connection address in the server certificate.
 * @method void setConnectAddress(string $ConnectAddress) Set Specifies the intranet or public network connection address in the server certificate.
 * @method string getRequestId() Obtain The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
 * @method void setRequestId(string $RequestId) Set The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
 */
class DescribeDBInstanceSSLConfigResponse extends AbstractModel
{
    /**
     * @var boolean true represents enabled. false represents not enabled.
     */
    public $SSLEnabled;

    /**
     * @var string Certificate download url for the cloud root certificate.
     */
    public $CAUrl;

    /**
     * @var string Specifies the intranet or public network connection address in the server certificate.
     */
    public $ConnectAddress;

    /**
     * @var string The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    public $RequestId;

    /**
     * @param boolean $SSLEnabled true represents enabled. false represents not enabled.
     * @param string $CAUrl Certificate download url for the cloud root certificate.
     * @param string $ConnectAddress Specifies the intranet or public network connection address in the server certificate.
     * @param string $RequestId The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    function __construct()
    {

    }

    /**
     * For internal only. DO NOT USE IT.
     */
    public function deserialize($param)
    {
        if ($param === null) {
            return;
        }
        if (array_key_exists("SSLEnabled",$param) and $param["SSLEnabled"] !== null) {
            $this->SSLEnabled = $param["SSLEnabled"];
        }

        if (array_key_exists("CAUrl",$param) and $param["CAUrl"] !== null) {
            $this->CAUrl = $param["CAUrl"];
        }

        if (array_key_exists("ConnectAddress",$param) and $param["ConnectAddress"] !== null) {
            $this->ConnectAddress = $param["ConnectAddress"];
        }

        if (array_key_exists("RequestId",$param) and $param["RequestId"] !== null) {
            $this->RequestId = $param["RequestId"];
        }
    }
}
