<?php
/*
 * Copyright (c) 2017-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
namespace TencentCloud\Tdmysql\V20211122\Models;
use TencentCloud\Common\AbstractModel;

/**
 * DescribeDBSAvailableRecoveryTime response structure.
 *
 * @method string getEndTime() Obtain <P>End time</p>
Note: This field may return null, indicating that no valid values can be obtained.
 * @method void setEndTime(string $EndTime) Set <P>End time</p>
Note: This field may return null, indicating that no valid values can be obtained.
 * @method array getIntervals() Obtain <P>Recoverable time interval.</p>
Note: This field may return null, indicating that no valid values can be obtained.
 * @method void setIntervals(array $Intervals) Set <P>Recoverable time interval.</p>
Note: This field may return null, indicating that no valid values can be obtained.
 * @method string getStartTime() Obtain <P>Start time</p>
Note: This field may return null, indicating that no valid values can be obtained.
 * @method void setStartTime(string $StartTime) Set <P>Start time</p>
Note: This field may return null, indicating that no valid values can be obtained.
 * @method string getRequestId() Obtain The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
 * @method void setRequestId(string $RequestId) Set The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
 */
class DescribeDBSAvailableRecoveryTimeResponse extends AbstractModel
{
    /**
     * @var string <P>End time</p>
Note: This field may return null, indicating that no valid values can be obtained.
     */
    public $EndTime;

    /**
     * @var array <P>Recoverable time interval.</p>
Note: This field may return null, indicating that no valid values can be obtained.
     */
    public $Intervals;

    /**
     * @var string <P>Start time</p>
Note: This field may return null, indicating that no valid values can be obtained.
     */
    public $StartTime;

    /**
     * @var string The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    public $RequestId;

    /**
     * @param string $EndTime <P>End time</p>
Note: This field may return null, indicating that no valid values can be obtained.
     * @param array $Intervals <P>Recoverable time interval.</p>
Note: This field may return null, indicating that no valid values can be obtained.
     * @param string $StartTime <P>Start time</p>
Note: This field may return null, indicating that no valid values can be obtained.
     * @param string $RequestId The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    function __construct()
    {

    }

    /**
     * For internal only. DO NOT USE IT.
     */
    public function deserialize($param)
    {
        if ($param === null) {
            return;
        }
        if (array_key_exists("EndTime",$param) and $param["EndTime"] !== null) {
            $this->EndTime = $param["EndTime"];
        }

        if (array_key_exists("Intervals",$param) and $param["Intervals"] !== null) {
            $this->Intervals = [];
            foreach ($param["Intervals"] as $key => $value){
                $obj = new ArchiveLogInterval();
                $obj->deserialize($value);
                array_push($this->Intervals, $obj);
            }
        }

        if (array_key_exists("StartTime",$param) and $param["StartTime"] !== null) {
            $this->StartTime = $param["StartTime"];
        }

        if (array_key_exists("RequestId",$param) and $param["RequestId"] !== null) {
            $this->RequestId = $param["RequestId"];
        }
    }
}
