<?php
/*
 * Copyright (c) 2017-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
namespace TencentCloud\Tdmysql\V20211122\Models;
use TencentCloud\Common\AbstractModel;

/**
 * DescribeDatabaseObjects response structure.
 *
 * @method string getInstanceId() Obtain <p>Passthrough input parameter.</p>
 * @method void setInstanceId(string $InstanceId) Set <p>Passthrough input parameter.</p>
 * @method string getDbName() Obtain <p>Database name.</p>
 * @method void setDbName(string $DbName) Set <p>Database name.</p>
 * @method array getTables() Obtain <p>Table list.</p>
Note: This field may return null, indicating that no valid values can be obtained.
 * @method void setTables(array $Tables) Set <p>Table list.</p>
Note: This field may return null, indicating that no valid values can be obtained.
 * @method array getViews() Obtain <p>View list.</p>
Note: This field may return null, indicating that no valid values can be obtained.
 * @method void setViews(array $Views) Set <p>View list.</p>
Note: This field may return null, indicating that no valid values can be obtained.
 * @method array getProcs() Obtain <p>Stored procedure list.</p>
Note: This field may return null, indicating that no valid values can be obtained.
 * @method void setProcs(array $Procs) Set <p>Stored procedure list.</p>
Note: This field may return null, indicating that no valid values can be obtained.
 * @method array getFuncs() Obtain <p>Function list.</p>
Note: This field may return null, indicating that no valid values can be obtained.
 * @method void setFuncs(array $Funcs) Set <p>Function list.</p>
Note: This field may return null, indicating that no valid values can be obtained.
 * @method string getRequestId() Obtain The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
 * @method void setRequestId(string $RequestId) Set The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
 */
class DescribeDatabaseObjectsResponse extends AbstractModel
{
    /**
     * @var string <p>Passthrough input parameter.</p>
     */
    public $InstanceId;

    /**
     * @var string <p>Database name.</p>
     */
    public $DbName;

    /**
     * @var array <p>Table list.</p>
Note: This field may return null, indicating that no valid values can be obtained.
     */
    public $Tables;

    /**
     * @var array <p>View list.</p>
Note: This field may return null, indicating that no valid values can be obtained.
     */
    public $Views;

    /**
     * @var array <p>Stored procedure list.</p>
Note: This field may return null, indicating that no valid values can be obtained.
     */
    public $Procs;

    /**
     * @var array <p>Function list.</p>
Note: This field may return null, indicating that no valid values can be obtained.
     */
    public $Funcs;

    /**
     * @var string The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    public $RequestId;

    /**
     * @param string $InstanceId <p>Passthrough input parameter.</p>
     * @param string $DbName <p>Database name.</p>
     * @param array $Tables <p>Table list.</p>
Note: This field may return null, indicating that no valid values can be obtained.
     * @param array $Views <p>View list.</p>
Note: This field may return null, indicating that no valid values can be obtained.
     * @param array $Procs <p>Stored procedure list.</p>
Note: This field may return null, indicating that no valid values can be obtained.
     * @param array $Funcs <p>Function list.</p>
Note: This field may return null, indicating that no valid values can be obtained.
     * @param string $RequestId The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    function __construct()
    {

    }

    /**
     * For internal only. DO NOT USE IT.
     */
    public function deserialize($param)
    {
        if ($param === null) {
            return;
        }
        if (array_key_exists("InstanceId",$param) and $param["InstanceId"] !== null) {
            $this->InstanceId = $param["InstanceId"];
        }

        if (array_key_exists("DbName",$param) and $param["DbName"] !== null) {
            $this->DbName = $param["DbName"];
        }

        if (array_key_exists("Tables",$param) and $param["Tables"] !== null) {
            $this->Tables = [];
            foreach ($param["Tables"] as $key => $value){
                $obj = new DatabaseTable();
                $obj->deserialize($value);
                array_push($this->Tables, $obj);
            }
        }

        if (array_key_exists("Views",$param) and $param["Views"] !== null) {
            $this->Views = [];
            foreach ($param["Views"] as $key => $value){
                $obj = new DatabaseView();
                $obj->deserialize($value);
                array_push($this->Views, $obj);
            }
        }

        if (array_key_exists("Procs",$param) and $param["Procs"] !== null) {
            $this->Procs = [];
            foreach ($param["Procs"] as $key => $value){
                $obj = new DatabaseProcedure();
                $obj->deserialize($value);
                array_push($this->Procs, $obj);
            }
        }

        if (array_key_exists("Funcs",$param) and $param["Funcs"] !== null) {
            $this->Funcs = [];
            foreach ($param["Funcs"] as $key => $value){
                $obj = new DatabaseFunction();
                $obj->deserialize($value);
                array_push($this->Funcs, $obj);
            }
        }

        if (array_key_exists("RequestId",$param) and $param["RequestId"] !== null) {
            $this->RequestId = $param["RequestId"];
        }
    }
}
