<?php
/*
 * Copyright (c) 2017-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
namespace TencentCloud\Cbs\V20170312\Models;
use TencentCloud\Common\AbstractModel;

/**
 * DescribeSnapshotOverview response structure.
 *
 * @method integer getTotalNums() Obtain Current number of valid snapshots.
 * @method void setTotalNums(integer $TotalNums) Set Current number of valid snapshots.
 * @method float getTotalSize() Obtain Total used snapshot capacity. unit: GiB.
 * @method void setTotalSize(float $TotalSize) Set Total used snapshot capacity. unit: GiB.
 * @method float getFreeQuota() Obtain Snapshot free quota size in GiB.
 * @method void setFreeQuota(float $FreeQuota) Set Snapshot free quota size in GiB.
 * @method float getRealTradeSize() Obtain Snapshot actual cost of total capacity in GiB.
 * @method void setRealTradeSize(float $RealTradeSize) Set Snapshot actual cost of total capacity in GiB.
 * @method string getRequestId() Obtain The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
 * @method void setRequestId(string $RequestId) Set The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
 */
class DescribeSnapshotOverviewResponse extends AbstractModel
{
    /**
     * @var integer Current number of valid snapshots.
     */
    public $TotalNums;

    /**
     * @var float Total used snapshot capacity. unit: GiB.
     */
    public $TotalSize;

    /**
     * @var float Snapshot free quota size in GiB.
     */
    public $FreeQuota;

    /**
     * @var float Snapshot actual cost of total capacity in GiB.
     */
    public $RealTradeSize;

    /**
     * @var string The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    public $RequestId;

    /**
     * @param integer $TotalNums Current number of valid snapshots.
     * @param float $TotalSize Total used snapshot capacity. unit: GiB.
     * @param float $FreeQuota Snapshot free quota size in GiB.
     * @param float $RealTradeSize Snapshot actual cost of total capacity in GiB.
     * @param string $RequestId The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    function __construct()
    {

    }

    /**
     * For internal only. DO NOT USE IT.
     */
    public function deserialize($param)
    {
        if ($param === null) {
            return;
        }
        if (array_key_exists("TotalNums",$param) and $param["TotalNums"] !== null) {
            $this->TotalNums = $param["TotalNums"];
        }

        if (array_key_exists("TotalSize",$param) and $param["TotalSize"] !== null) {
            $this->TotalSize = $param["TotalSize"];
        }

        if (array_key_exists("FreeQuota",$param) and $param["FreeQuota"] !== null) {
            $this->FreeQuota = $param["FreeQuota"];
        }

        if (array_key_exists("RealTradeSize",$param) and $param["RealTradeSize"] !== null) {
            $this->RealTradeSize = $param["RealTradeSize"];
        }

        if (array_key_exists("RequestId",$param) and $param["RequestId"] !== null) {
            $this->RequestId = $param["RequestId"];
        }
    }
}
