<?php
/*
 * Copyright (c) 2017-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
namespace TencentCloud\Apm\V20210622\Models;
use TencentCloud\Common\AbstractModel;

/**
 * DescribeApmAllVulCount response structure.
 *
 * @method array getVulnerabilityList() Obtain Vulnerability metrics as well as number of business systems	
 * @method void setVulnerabilityList(array $VulnerabilityList) Set Vulnerability metrics as well as number of business systems	
 * @method integer getVulnerabilityCount() Obtain Total number of vulnerabilities
 * @method void setVulnerabilityCount(integer $VulnerabilityCount) Set Total number of vulnerabilities
 * @method integer getImportantVulnerabilityCount() Obtain Number of critical vulnerabilities
 * @method void setImportantVulnerabilityCount(integer $ImportantVulnerabilityCount) Set Number of critical vulnerabilities
 * @method integer getCriticalVulnerabilityCount() Obtain High-risk vulnerability count
 * @method void setCriticalVulnerabilityCount(integer $CriticalVulnerabilityCount) Set High-risk vulnerability count
 * @method string getRequestId() Obtain The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
 * @method void setRequestId(string $RequestId) Set The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
 */
class DescribeApmAllVulCountResponse extends AbstractModel
{
    /**
     * @var array Vulnerability metrics as well as number of business systems	
     */
    public $VulnerabilityList;

    /**
     * @var integer Total number of vulnerabilities
     */
    public $VulnerabilityCount;

    /**
     * @var integer Number of critical vulnerabilities
     */
    public $ImportantVulnerabilityCount;

    /**
     * @var integer High-risk vulnerability count
     */
    public $CriticalVulnerabilityCount;

    /**
     * @var string The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    public $RequestId;

    /**
     * @param array $VulnerabilityList Vulnerability metrics as well as number of business systems	
     * @param integer $VulnerabilityCount Total number of vulnerabilities
     * @param integer $ImportantVulnerabilityCount Number of critical vulnerabilities
     * @param integer $CriticalVulnerabilityCount High-risk vulnerability count
     * @param string $RequestId The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    function __construct()
    {

    }

    /**
     * For internal only. DO NOT USE IT.
     */
    public function deserialize($param)
    {
        if ($param === null) {
            return;
        }
        if (array_key_exists("VulnerabilityList",$param) and $param["VulnerabilityList"] !== null) {
            $this->VulnerabilityList = [];
            foreach ($param["VulnerabilityList"] as $key => $value){
                $obj = new ApmMetricRecord();
                $obj->deserialize($value);
                array_push($this->VulnerabilityList, $obj);
            }
        }

        if (array_key_exists("VulnerabilityCount",$param) and $param["VulnerabilityCount"] !== null) {
            $this->VulnerabilityCount = $param["VulnerabilityCount"];
        }

        if (array_key_exists("ImportantVulnerabilityCount",$param) and $param["ImportantVulnerabilityCount"] !== null) {
            $this->ImportantVulnerabilityCount = $param["ImportantVulnerabilityCount"];
        }

        if (array_key_exists("CriticalVulnerabilityCount",$param) and $param["CriticalVulnerabilityCount"] !== null) {
            $this->CriticalVulnerabilityCount = $param["CriticalVulnerabilityCount"];
        }

        if (array_key_exists("RequestId",$param) and $param["RequestId"] !== null) {
            $this->RequestId = $param["RequestId"];
        }
    }
}
