<?php
/*
 * Copyright (c) 2017-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
namespace TencentCloud\Trocket\V20230308\Models;
use TencentCloud\Common\AbstractModel;

/**
 * DoHealthCheckOnMigratingTopic response structure.
 *
 * @method boolean getPassed() Obtain Whether to Pass		
 * @method void setPassed(boolean $Passed) Set Whether to Pass		
 * @method string getReason() Obtain Error information returned by health check.
NotChecked indicates the check is not executed. 
Unknown error. 
TopicNotImported. specifies the topic is not imported.
TopicNotExistsInSourceCluster specifies the topic does not exist in the source cluster. 
Topic does not exist in the target cluster. 
ConsumerConnectedOnTarget specifies whether consumer connections exist on the target cluster. 
SourceTopicHasNewMessagesIn5Minutes indicates that new messages were written to the source cluster topic in the last 5 minutes. 
TargetTopicHasNewMessagesIn5Minutes specifies whether new messages were written to the target cluster topic in the last 5 minutes. 
SourceTopicHasNoMessagesIn5Minutes specifies no new messages were written to the source cluster in the last 5 minutes. 
TargetTopicHasNoMessagesIn5Minutes specifies that no new messages were written to the source cluster in the last 5 minutes. 
Inconsistent number of subscription groups. 
SourceTopicHasUnconsumedMessages specifies that unconsumed messages exist in the source cluster topic.
Note: This field may return null, indicating that no valid values can be obtained.
 * @method void setReason(string $Reason) Set Error information returned by health check.
NotChecked indicates the check is not executed. 
Unknown error. 
TopicNotImported. specifies the topic is not imported.
TopicNotExistsInSourceCluster specifies the topic does not exist in the source cluster. 
Topic does not exist in the target cluster. 
ConsumerConnectedOnTarget specifies whether consumer connections exist on the target cluster. 
SourceTopicHasNewMessagesIn5Minutes indicates that new messages were written to the source cluster topic in the last 5 minutes. 
TargetTopicHasNewMessagesIn5Minutes specifies whether new messages were written to the target cluster topic in the last 5 minutes. 
SourceTopicHasNoMessagesIn5Minutes specifies no new messages were written to the source cluster in the last 5 minutes. 
TargetTopicHasNoMessagesIn5Minutes specifies that no new messages were written to the source cluster in the last 5 minutes. 
Inconsistent number of subscription groups. 
SourceTopicHasUnconsumedMessages specifies that unconsumed messages exist in the source cluster topic.
Note: This field may return null, indicating that no valid values can be obtained.
 * @method array getReasonList() Obtain List of error information returned by health check.
Note: This field may return null, indicating that no valid values can be obtained.
 * @method void setReasonList(array $ReasonList) Set List of error information returned by health check.
Note: This field may return null, indicating that no valid values can be obtained.
 * @method string getRequestId() Obtain The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
 * @method void setRequestId(string $RequestId) Set The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
 */
class DoHealthCheckOnMigratingTopicResponse extends AbstractModel
{
    /**
     * @var boolean Whether to Pass		
     */
    public $Passed;

    /**
     * @var string Error information returned by health check.
NotChecked indicates the check is not executed. 
Unknown error. 
TopicNotImported. specifies the topic is not imported.
TopicNotExistsInSourceCluster specifies the topic does not exist in the source cluster. 
Topic does not exist in the target cluster. 
ConsumerConnectedOnTarget specifies whether consumer connections exist on the target cluster. 
SourceTopicHasNewMessagesIn5Minutes indicates that new messages were written to the source cluster topic in the last 5 minutes. 
TargetTopicHasNewMessagesIn5Minutes specifies whether new messages were written to the target cluster topic in the last 5 minutes. 
SourceTopicHasNoMessagesIn5Minutes specifies no new messages were written to the source cluster in the last 5 minutes. 
TargetTopicHasNoMessagesIn5Minutes specifies that no new messages were written to the source cluster in the last 5 minutes. 
Inconsistent number of subscription groups. 
SourceTopicHasUnconsumedMessages specifies that unconsumed messages exist in the source cluster topic.
Note: This field may return null, indicating that no valid values can be obtained.
     */
    public $Reason;

    /**
     * @var array List of error information returned by health check.
Note: This field may return null, indicating that no valid values can be obtained.
     */
    public $ReasonList;

    /**
     * @var string The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    public $RequestId;

    /**
     * @param boolean $Passed Whether to Pass		
     * @param string $Reason Error information returned by health check.
NotChecked indicates the check is not executed. 
Unknown error. 
TopicNotImported. specifies the topic is not imported.
TopicNotExistsInSourceCluster specifies the topic does not exist in the source cluster. 
Topic does not exist in the target cluster. 
ConsumerConnectedOnTarget specifies whether consumer connections exist on the target cluster. 
SourceTopicHasNewMessagesIn5Minutes indicates that new messages were written to the source cluster topic in the last 5 minutes. 
TargetTopicHasNewMessagesIn5Minutes specifies whether new messages were written to the target cluster topic in the last 5 minutes. 
SourceTopicHasNoMessagesIn5Minutes specifies no new messages were written to the source cluster in the last 5 minutes. 
TargetTopicHasNoMessagesIn5Minutes specifies that no new messages were written to the source cluster in the last 5 minutes. 
Inconsistent number of subscription groups. 
SourceTopicHasUnconsumedMessages specifies that unconsumed messages exist in the source cluster topic.
Note: This field may return null, indicating that no valid values can be obtained.
     * @param array $ReasonList List of error information returned by health check.
Note: This field may return null, indicating that no valid values can be obtained.
     * @param string $RequestId The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
     */
    function __construct()
    {

    }

    /**
     * For internal only. DO NOT USE IT.
     */
    public function deserialize($param)
    {
        if ($param === null) {
            return;
        }
        if (array_key_exists("Passed",$param) and $param["Passed"] !== null) {
            $this->Passed = $param["Passed"];
        }

        if (array_key_exists("Reason",$param) and $param["Reason"] !== null) {
            $this->Reason = $param["Reason"];
        }

        if (array_key_exists("ReasonList",$param) and $param["ReasonList"] !== null) {
            $this->ReasonList = $param["ReasonList"];
        }

        if (array_key_exists("RequestId",$param) and $param["RequestId"] !== null) {
            $this->RequestId = $param["RequestId"];
        }
    }
}
