<?php
/*
 * Copyright (c) 2017-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
namespace TencentCloud\Vod\V20180717\Models;
use TencentCloud\Common\AbstractModel;

/**
 * VOD file information
 *
 * @method MediaBasicInfo getBasicInfo() Obtain <p>Basic information. Include video name, category, playback address, cover image.</p>
Note: This field may return null, indicating that no valid values can be obtained.
 * @method void setBasicInfo(MediaBasicInfo $BasicInfo) Set <p>Basic information. Include video name, category, playback address, cover image.</p>
Note: This field may return null, indicating that no valid values can be obtained.
 * @method MediaMetaData getMetaData() Obtain <p>Meta information, including size, duration, video stream information, and audio stream information.</p>
Note: This field may return null, indicating that no valid values can be obtained.
 * @method void setMetaData(MediaMetaData $MetaData) Set <p>Meta information, including size, duration, video stream information, and audio stream information.</p>
Note: This field may return null, indicating that no valid values can be obtained.
 * @method MediaTranscodeInfo getTranscodeInfo() Obtain <p>Transcoding result information, including domain names or IP addresses, specifications, bitrates, and resolutions of various types of videos generated by video transcoding.</p>
Note: This field may return null, indicating that no valid values can be obtained.
 * @method void setTranscodeInfo(MediaTranscodeInfo $TranscodeInfo) Set <p>Transcoding result information, including domain names or IP addresses, specifications, bitrates, and resolutions of various types of videos generated by video transcoding.</p>
Note: This field may return null, indicating that no valid values can be obtained.
 * @method MediaAnimatedGraphicsInfo getAnimatedGraphicsInfo() Obtain <p>AnimatedGraphicsInfo. Information related to the animated graphics (such as gif) after video-to-gif conversion.</p>
Note: This field may return null, indicating that no valid values can be obtained.
 * @method void setAnimatedGraphicsInfo(MediaAnimatedGraphicsInfo $AnimatedGraphicsInfo) Set <p>AnimatedGraphicsInfo. Information related to the animated graphics (such as gif) after video-to-gif conversion.</p>
Note: This field may return null, indicating that no valid values can be obtained.
 * @method MediaSampleSnapshotInfo getSampleSnapshotInfo() Obtain <p>Sampling screenshot information. Screenshot information related to the video after sampling screenshot taking.</p>
Note: This field may return null, indicating that no valid values can be obtained.
 * @method void setSampleSnapshotInfo(MediaSampleSnapshotInfo $SampleSnapshotInfo) Set <p>Sampling screenshot information. Screenshot information related to the video after sampling screenshot taking.</p>
Note: This field may return null, indicating that no valid values can be obtained.
 * @method MediaImageSpriteInfo getImageSpriteInfo() Obtain <p>Sprite image information. Relevant information of the sprite after capturing CSS sprites from the video.</p>
Note: This field may return null, indicating that no valid values can be obtained.
 * @method void setImageSpriteInfo(MediaImageSpriteInfo $ImageSpriteInfo) Set <p>Sprite image information. Relevant information of the sprite after capturing CSS sprites from the video.</p>
Note: This field may return null, indicating that no valid values can be obtained.
 * @method MediaSnapshotByTimeOffsetInfo getSnapshotByTimeOffsetInfo() Obtain <p>Screenshot information at the specified time point. Information of each screenshot after capturing the video at the specified time point.</p>
Note: This field may return null, indicating that no valid values can be obtained.
 * @method void setSnapshotByTimeOffsetInfo(MediaSnapshotByTimeOffsetInfo $SnapshotByTimeOffsetInfo) Set <p>Screenshot information at the specified time point. Information of each screenshot after capturing the video at the specified time point.</p>
Note: This field may return null, indicating that no valid values can be obtained.
 * @method MediaKeyFrameDescInfo getKeyFrameDescInfo() Obtain <p>Video timestamp information. Each dotting information set for the video.</p>
Note: This field may return null, indicating that no valid values can be obtained.
 * @method void setKeyFrameDescInfo(MediaKeyFrameDescInfo $KeyFrameDescInfo) Set <p>Video timestamp information. Each dotting information set for the video.</p>
Note: This field may return null, indicating that no valid values can be obtained.
 * @method MediaAdaptiveDynamicStreamingInfo getAdaptiveDynamicStreamingInfo() Obtain <p>Adaptive Bitrate Streaming information. Includes specification, encryption type, packaging format and information related to.</p>
Note: This field may return null, indicating that no valid values can be obtained.
 * @method void setAdaptiveDynamicStreamingInfo(MediaAdaptiveDynamicStreamingInfo $AdaptiveDynamicStreamingInfo) Set <p>Adaptive Bitrate Streaming information. Includes specification, encryption type, packaging format and information related to.</p>
Note: This field may return null, indicating that no valid values can be obtained.
 * @method MediaMiniProgramReviewInfo getMiniProgramReviewInfo() Obtain <p>miniProgramReviewInfo</p>
Note: This field may return null, indicating that no valid values can be obtained.
 * @method void setMiniProgramReviewInfo(MediaMiniProgramReviewInfo $MiniProgramReviewInfo) Set <p>miniProgramReviewInfo</p>
Note: This field may return null, indicating that no valid values can be obtained.
 * @method MediaSubtitleInfo getSubtitleInfo() Obtain <p>Subtitle information.</p>
Note: This field may return null, indicating that no valid values can be obtained.
 * @method void setSubtitleInfo(MediaSubtitleInfo $SubtitleInfo) Set <p>Subtitle information.</p>
Note: This field may return null, indicating that no valid values can be obtained.
 * @method string getFileId() Obtain <p>Media file unique identifier ID.</p>
 * @method void setFileId(string $FileId) Set <p>Media file unique identifier ID.</p>
 * @method FileReviewInfo getReviewInfo() Obtain <p>Verification information.</p>
Note: This field may return null, indicating that no valid values can be obtained.
 * @method void setReviewInfo(FileReviewInfo $ReviewInfo) Set <p>Verification information.</p>
Note: This field may return null, indicating that no valid values can be obtained.
 * @method MPSAiMediaInfo getMPSAiMediaInfo() Obtain <p>MPS intelligent media asset information</p>
 * @method void setMPSAiMediaInfo(MPSAiMediaInfo $MPSAiMediaInfo) Set <p>MPS intelligent media asset information</p>
 * @method ImageUnderstandingInfo getImageUnderstandingInfo() Obtain <p>Image understanding information.</p>
Note: This field may return null, indicating that no valid values can be obtained.
 * @method void setImageUnderstandingInfo(ImageUnderstandingInfo $ImageUnderstandingInfo) Set <p>Image understanding information.</p>
Note: This field may return null, indicating that no valid values can be obtained.
 * @method KnowledgeBasesInfo getKnowledgeBasesInfo() Obtain <p>Intelligent library information.</p>
 * @method void setKnowledgeBasesInfo(KnowledgeBasesInfo $KnowledgeBasesInfo) Set <p>Intelligent library information.</p>
 * @method FaceRecognitionInfo getFaceRecognitionInfo() Obtain <p>Facial recognition information.</p>
 * @method void setFaceRecognitionInfo(FaceRecognitionInfo $FaceRecognitionInfo) Set <p>Facial recognition information.</p>
 */
class MediaInfo extends AbstractModel
{
    /**
     * @var MediaBasicInfo <p>Basic information. Include video name, category, playback address, cover image.</p>
Note: This field may return null, indicating that no valid values can be obtained.
     */
    public $BasicInfo;

    /**
     * @var MediaMetaData <p>Meta information, including size, duration, video stream information, and audio stream information.</p>
Note: This field may return null, indicating that no valid values can be obtained.
     */
    public $MetaData;

    /**
     * @var MediaTranscodeInfo <p>Transcoding result information, including domain names or IP addresses, specifications, bitrates, and resolutions of various types of videos generated by video transcoding.</p>
Note: This field may return null, indicating that no valid values can be obtained.
     */
    public $TranscodeInfo;

    /**
     * @var MediaAnimatedGraphicsInfo <p>AnimatedGraphicsInfo. Information related to the animated graphics (such as gif) after video-to-gif conversion.</p>
Note: This field may return null, indicating that no valid values can be obtained.
     */
    public $AnimatedGraphicsInfo;

    /**
     * @var MediaSampleSnapshotInfo <p>Sampling screenshot information. Screenshot information related to the video after sampling screenshot taking.</p>
Note: This field may return null, indicating that no valid values can be obtained.
     */
    public $SampleSnapshotInfo;

    /**
     * @var MediaImageSpriteInfo <p>Sprite image information. Relevant information of the sprite after capturing CSS sprites from the video.</p>
Note: This field may return null, indicating that no valid values can be obtained.
     */
    public $ImageSpriteInfo;

    /**
     * @var MediaSnapshotByTimeOffsetInfo <p>Screenshot information at the specified time point. Information of each screenshot after capturing the video at the specified time point.</p>
Note: This field may return null, indicating that no valid values can be obtained.
     */
    public $SnapshotByTimeOffsetInfo;

    /**
     * @var MediaKeyFrameDescInfo <p>Video timestamp information. Each dotting information set for the video.</p>
Note: This field may return null, indicating that no valid values can be obtained.
     */
    public $KeyFrameDescInfo;

    /**
     * @var MediaAdaptiveDynamicStreamingInfo <p>Adaptive Bitrate Streaming information. Includes specification, encryption type, packaging format and information related to.</p>
Note: This field may return null, indicating that no valid values can be obtained.
     */
    public $AdaptiveDynamicStreamingInfo;

    /**
     * @var MediaMiniProgramReviewInfo <p>miniProgramReviewInfo</p>
Note: This field may return null, indicating that no valid values can be obtained.
     */
    public $MiniProgramReviewInfo;

    /**
     * @var MediaSubtitleInfo <p>Subtitle information.</p>
Note: This field may return null, indicating that no valid values can be obtained.
     */
    public $SubtitleInfo;

    /**
     * @var string <p>Media file unique identifier ID.</p>
     */
    public $FileId;

    /**
     * @var FileReviewInfo <p>Verification information.</p>
Note: This field may return null, indicating that no valid values can be obtained.
     */
    public $ReviewInfo;

    /**
     * @var MPSAiMediaInfo <p>MPS intelligent media asset information</p>
     */
    public $MPSAiMediaInfo;

    /**
     * @var ImageUnderstandingInfo <p>Image understanding information.</p>
Note: This field may return null, indicating that no valid values can be obtained.
     */
    public $ImageUnderstandingInfo;

    /**
     * @var KnowledgeBasesInfo <p>Intelligent library information.</p>
     */
    public $KnowledgeBasesInfo;

    /**
     * @var FaceRecognitionInfo <p>Facial recognition information.</p>
     */
    public $FaceRecognitionInfo;

    /**
     * @param MediaBasicInfo $BasicInfo <p>Basic information. Include video name, category, playback address, cover image.</p>
Note: This field may return null, indicating that no valid values can be obtained.
     * @param MediaMetaData $MetaData <p>Meta information, including size, duration, video stream information, and audio stream information.</p>
Note: This field may return null, indicating that no valid values can be obtained.
     * @param MediaTranscodeInfo $TranscodeInfo <p>Transcoding result information, including domain names or IP addresses, specifications, bitrates, and resolutions of various types of videos generated by video transcoding.</p>
Note: This field may return null, indicating that no valid values can be obtained.
     * @param MediaAnimatedGraphicsInfo $AnimatedGraphicsInfo <p>AnimatedGraphicsInfo. Information related to the animated graphics (such as gif) after video-to-gif conversion.</p>
Note: This field may return null, indicating that no valid values can be obtained.
     * @param MediaSampleSnapshotInfo $SampleSnapshotInfo <p>Sampling screenshot information. Screenshot information related to the video after sampling screenshot taking.</p>
Note: This field may return null, indicating that no valid values can be obtained.
     * @param MediaImageSpriteInfo $ImageSpriteInfo <p>Sprite image information. Relevant information of the sprite after capturing CSS sprites from the video.</p>
Note: This field may return null, indicating that no valid values can be obtained.
     * @param MediaSnapshotByTimeOffsetInfo $SnapshotByTimeOffsetInfo <p>Screenshot information at the specified time point. Information of each screenshot after capturing the video at the specified time point.</p>
Note: This field may return null, indicating that no valid values can be obtained.
     * @param MediaKeyFrameDescInfo $KeyFrameDescInfo <p>Video timestamp information. Each dotting information set for the video.</p>
Note: This field may return null, indicating that no valid values can be obtained.
     * @param MediaAdaptiveDynamicStreamingInfo $AdaptiveDynamicStreamingInfo <p>Adaptive Bitrate Streaming information. Includes specification, encryption type, packaging format and information related to.</p>
Note: This field may return null, indicating that no valid values can be obtained.
     * @param MediaMiniProgramReviewInfo $MiniProgramReviewInfo <p>miniProgramReviewInfo</p>
Note: This field may return null, indicating that no valid values can be obtained.
     * @param MediaSubtitleInfo $SubtitleInfo <p>Subtitle information.</p>
Note: This field may return null, indicating that no valid values can be obtained.
     * @param string $FileId <p>Media file unique identifier ID.</p>
     * @param FileReviewInfo $ReviewInfo <p>Verification information.</p>
Note: This field may return null, indicating that no valid values can be obtained.
     * @param MPSAiMediaInfo $MPSAiMediaInfo <p>MPS intelligent media asset information</p>
     * @param ImageUnderstandingInfo $ImageUnderstandingInfo <p>Image understanding information.</p>
Note: This field may return null, indicating that no valid values can be obtained.
     * @param KnowledgeBasesInfo $KnowledgeBasesInfo <p>Intelligent library information.</p>
     * @param FaceRecognitionInfo $FaceRecognitionInfo <p>Facial recognition information.</p>
     */
    function __construct()
    {

    }

    /**
     * For internal only. DO NOT USE IT.
     */
    public function deserialize($param)
    {
        if ($param === null) {
            return;
        }
        if (array_key_exists("BasicInfo",$param) and $param["BasicInfo"] !== null) {
            $this->BasicInfo = new MediaBasicInfo();
            $this->BasicInfo->deserialize($param["BasicInfo"]);
        }

        if (array_key_exists("MetaData",$param) and $param["MetaData"] !== null) {
            $this->MetaData = new MediaMetaData();
            $this->MetaData->deserialize($param["MetaData"]);
        }

        if (array_key_exists("TranscodeInfo",$param) and $param["TranscodeInfo"] !== null) {
            $this->TranscodeInfo = new MediaTranscodeInfo();
            $this->TranscodeInfo->deserialize($param["TranscodeInfo"]);
        }

        if (array_key_exists("AnimatedGraphicsInfo",$param) and $param["AnimatedGraphicsInfo"] !== null) {
            $this->AnimatedGraphicsInfo = new MediaAnimatedGraphicsInfo();
            $this->AnimatedGraphicsInfo->deserialize($param["AnimatedGraphicsInfo"]);
        }

        if (array_key_exists("SampleSnapshotInfo",$param) and $param["SampleSnapshotInfo"] !== null) {
            $this->SampleSnapshotInfo = new MediaSampleSnapshotInfo();
            $this->SampleSnapshotInfo->deserialize($param["SampleSnapshotInfo"]);
        }

        if (array_key_exists("ImageSpriteInfo",$param) and $param["ImageSpriteInfo"] !== null) {
            $this->ImageSpriteInfo = new MediaImageSpriteInfo();
            $this->ImageSpriteInfo->deserialize($param["ImageSpriteInfo"]);
        }

        if (array_key_exists("SnapshotByTimeOffsetInfo",$param) and $param["SnapshotByTimeOffsetInfo"] !== null) {
            $this->SnapshotByTimeOffsetInfo = new MediaSnapshotByTimeOffsetInfo();
            $this->SnapshotByTimeOffsetInfo->deserialize($param["SnapshotByTimeOffsetInfo"]);
        }

        if (array_key_exists("KeyFrameDescInfo",$param) and $param["KeyFrameDescInfo"] !== null) {
            $this->KeyFrameDescInfo = new MediaKeyFrameDescInfo();
            $this->KeyFrameDescInfo->deserialize($param["KeyFrameDescInfo"]);
        }

        if (array_key_exists("AdaptiveDynamicStreamingInfo",$param) and $param["AdaptiveDynamicStreamingInfo"] !== null) {
            $this->AdaptiveDynamicStreamingInfo = new MediaAdaptiveDynamicStreamingInfo();
            $this->AdaptiveDynamicStreamingInfo->deserialize($param["AdaptiveDynamicStreamingInfo"]);
        }

        if (array_key_exists("MiniProgramReviewInfo",$param) and $param["MiniProgramReviewInfo"] !== null) {
            $this->MiniProgramReviewInfo = new MediaMiniProgramReviewInfo();
            $this->MiniProgramReviewInfo->deserialize($param["MiniProgramReviewInfo"]);
        }

        if (array_key_exists("SubtitleInfo",$param) and $param["SubtitleInfo"] !== null) {
            $this->SubtitleInfo = new MediaSubtitleInfo();
            $this->SubtitleInfo->deserialize($param["SubtitleInfo"]);
        }

        if (array_key_exists("FileId",$param) and $param["FileId"] !== null) {
            $this->FileId = $param["FileId"];
        }

        if (array_key_exists("ReviewInfo",$param) and $param["ReviewInfo"] !== null) {
            $this->ReviewInfo = new FileReviewInfo();
            $this->ReviewInfo->deserialize($param["ReviewInfo"]);
        }

        if (array_key_exists("MPSAiMediaInfo",$param) and $param["MPSAiMediaInfo"] !== null) {
            $this->MPSAiMediaInfo = new MPSAiMediaInfo();
            $this->MPSAiMediaInfo->deserialize($param["MPSAiMediaInfo"]);
        }

        if (array_key_exists("ImageUnderstandingInfo",$param) and $param["ImageUnderstandingInfo"] !== null) {
            $this->ImageUnderstandingInfo = new ImageUnderstandingInfo();
            $this->ImageUnderstandingInfo->deserialize($param["ImageUnderstandingInfo"]);
        }

        if (array_key_exists("KnowledgeBasesInfo",$param) and $param["KnowledgeBasesInfo"] !== null) {
            $this->KnowledgeBasesInfo = new KnowledgeBasesInfo();
            $this->KnowledgeBasesInfo->deserialize($param["KnowledgeBasesInfo"]);
        }

        if (array_key_exists("FaceRecognitionInfo",$param) and $param["FaceRecognitionInfo"] !== null) {
            $this->FaceRecognitionInfo = new FaceRecognitionInfo();
            $this->FaceRecognitionInfo->deserialize($param["FaceRecognitionInfo"]);
        }
    }
}
